### ISSUE TITLE
parse_strings_as_datetimes is not implemented for SQLAlchemy (database) datasources

### ISSUE THREAD

**Issue by Vasilije1990** [fivetran/great_expectations#1097]
When running the function bellow, an error occurs: 

sql_dataset.expect_column_max_to_be_between('inserted_at', datetime(2020,2,18), datetime(2020,2,19), parse_strings_as_datetimes=True)

Appending the traceback
`
Traceback (most recent call last):
  File "/Users/ekaterinavolkova/.virtualenvs/data-airflow/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3319, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-10-de1300becab3>", line 1, in <module>
    sql_dataset.expect_column_max_to_be_between('inserted_at', datetime(2020,2,18), datetime(2020,2,19), parse_strings_as_datetimes=True)
  File "/Users/ekaterinavolkova/.virtualenvs/data-airflow/lib/python3.7/site-packages/great_expectations/data_asset/util.py", line 85, in f
    return self.mthd(obj, *args, **kwargs)
  File "/Users/ekaterinavolkova/.virtualenvs/data-airflow/lib/python3.7/site-packages/great_expectations/data_asset/data_asset.py", line 236, in wrapper
    raise err
  File "/Users/ekaterinavolkova/.virtualenvs/data-airflow/lib/python3.7/site-packages/great_expectations/data_asset/data_asset.py", line 223, in wrapper
    return_obj = func(self, **evaluation_args)
  File "/Users/ekaterinavolkova/.virtualenvs/data-airflow/lib/python3.7/site-packages/great_expectations/dataset/dataset.py", line 108, in inner_wrapper
    evaluation_result = func(self, column, *args, **kwargs)
  File "/Users/ekaterinavolkova/.virtualenvs/data-airflow/lib/python3.7/site-packages/great_expectations/dataset/dataset.py", line 3345, in expect_column_max_to_be_between
    column_max = self.get_column_max(column, parse_strings_as_datetimes)
  File "/Users/ekaterinavolkova/.virtualenvs/data-airflow/lib/python3.7/site-packages/great_expectations/dataset/sqlalchemy_dataset.py", line 340, in get_column_max
    raise NotImplementedError
NotImplementedError`

**Comment by eugmandel** [comment]
@Vasilije1990 Thank you for reporting this.
Every expectation type should have its own implementation for each of the currently supported "datasources" (data compute backends) - Pandas, PySpark, SQL databases.
Some expectation types (e.g., parse_strings_as_datetimes) were not implemented for SQLAlchemy datasources.

I renamed the issue to make it more specific.

**Comment by jcampbell** [comment]
Two things here:

1. Is the column you're working with stored as a datetime type on your backend? If so, you should be able to simply remove the `parse_strings_as_datetimes` flag; that was originally designed for a pandas-specific case where datetimes were read from CSV as strings.

2. This is a really important issue, and unfortunately I think it's more a function of the fact that `parse_strings_as_datetimes` is a confusing parameter that is mostly meaningful only on pandas. The feature will be removed in a future release.
