### ISSUE TITLE
Docs Build --site-name bug

### ISSUE THREAD

**Issue by ddaltonrtr** [fivetran/great_expectations#1378]
**Describe the bug**
If you have a local site and S3 site configured in the yml and run the command `great_expectations docs build --site-name local_site`, great expectations still tries to verify the S3 credentials and run stuff related to the S3 site in the background.

This is an issue because a user testing locally should not need access to the production S3 credentials (or any AWS credentials).

**Temporary Workaround**
If you add `--no-view` to the end of the command (so the command becomes `great_expectations docs build --site-name local_site --no-view`) you can circumvent this error and achieve the expected behavior. This isn't exactly obvious though to the end user without being told.

**To Reproduce**
1. Put something like the below in the grea_expectations.yml file:
```
data_docs_sites:
  # Data Docs make it simple to visualize data quality in your project. These
  # include Expectations, Validations & Profiles. The are built for all
  # Datasources from JSON artifacts in the local repo including validations &
  # profiles from the uncommitted directory. Read more at https://docs.greatexpectations.io/en/latest/features/data_docs.html
  local_site:
    class_name: SiteBuilder
    # set to false to hide how-to buttons in Data Docs
    # show_how_to_buttons: false
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/data_docs/local_site/
    site_index_builder:
      class_name: DefaultSiteIndexBuilder
  s3_site:
    class_name: SiteBuilder
    store_backend:
      class_name: TupleS3StoreBackend
      bucket: bucket_name
      prefix: sub_directory
```
2. Run `great_expectations docs build --site-name local_site`
3. See error
```
Running great_expectations docs build --site-name local_site
Building Data Docs...
The following Data Docs sites were built:
 - local_site: file:///great_expectations/uncommitted/data_docs/local_site/index.html
Traceback (most recent call last):
  File "/usr/local/bin/great_expectations", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/great_expectations/cli/cli.py", line 67, in main
    cli()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/great_expectations/cli/docs.py", line 40, in docs_build
    build_docs(context, site_name=site_name, view=view)
  File "/usr/local/lib/python3.7/site-packages/great_expectations/cli/docs.py", line 147, in build_docs
    context.open_data_docs()
  File "/usr/local/lib/python3.7/site-packages/great_expectations/core/usage_statistics/usage_statistics.py", line 215, in usage_statistics_wrapped_method
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/great_expectations/data_context/data_context.py", line 428, in open_data_docs
    data_docs_urls = self.get_docs_sites_urls(resource_identifier=resource_identifier)
  File "/usr/local/lib/python3.7/site-packages/great_expectations/data_context/data_context.py", line 411, in get_docs_sites_urls
    url = site_builder.get_resource_url(resource_identifier=resource_identifier)
  File "/usr/local/lib/python3.7/site-packages/great_expectations/render/renderer/site_builder.py", line 253, in get_resource_url
    return self.target_store.get_url_for_resource(resource_identifier=resource_identifier)
  File "/usr/local/lib/python3.7/site-packages/great_expectations/data_context/store/html_site_store.py", line 168, in get_url_for_resource
    return store_backend.get_url_for_key(key)
  File "/usr/local/lib/python3.7/site-packages/great_expectations/data_context/store/tuple_store_backend.py", line 380, in get_url_for_key
    location = boto3.client('s3').get_bucket_location(Bucket=self.bucket)['LocationConstraint']
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidAccessKeyId) when calling the GetBucketLocation operation: The AWS Access Key Id you provided does not exist in our records.
```

**Expected behavior**
I expect that by specifying `local_site`, only the local site will be updated and surfaced. Great_expectations will not try to validate/open/update the S3 site.

**Environment (please complete the following information):**
 - python:3.7.6-slim base docker image
 - GE Version: 0.10.6

**Additional context**
I discussed this via slack with @jcampbell and he recommended opening an issue here.

**Comment by Aylr** [comment]
Thanks @ddaltonrtr for this excellent and detailed write up. I plan on shipping a fix for this by mid week!
