### ISSUE TITLE
Lack of optional dependency crashes init

### ISSUE THREAD

**Issue by kokes** [fivetran/great_expectations#1443]
When I install Great Expectations without SQL Alchemy, `great_expectations init` will fail due to a missing type information.

**To Reproduce**

```
docker run -it --rm python:3-slim bash
pip3 install great_expectations
great_expectations init
```

**Expected behavior**
I expected init to run. (After I manually installed sqlachemy, it did work.)

The reason for this is that you allow SQL Alchemy to be not imported (https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/dataset/util.py#L16), but later require its type information (https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/dataset/util.py#L578).

**Environment (please complete the following information):**
 - OS: macOS, Ubuntu
 - GE Version: latest, 0.10.11

**Additional context**

traceback:

<details>
<pre>
$ great_expectations -v init
Traceback (most recent call last):
  File "/Users/okokes/.pyenv/versions/3.7.7/bin/great_expectations", line 5, in <module>
    from great_expectations.cli import main
  File "/Users/okokes/.pyenv/versions/3.7.7/lib/python3.7/site-packages/great_expectations/__init__.py", line 7, in <module>
    from great_expectations.data_context import DataContext
  File "/Users/okokes/.pyenv/versions/3.7.7/lib/python3.7/site-packages/great_expectations/data_context/__init__.py", line 3, in <module>
    from .data_context import BaseDataContext, DataContext, ExplorerDataContext
  File "/Users/okokes/.pyenv/versions/3.7.7/lib/python3.7/site-packages/great_expectations/data_context/data_context.py", line 20, in <module>
    from great_expectations.core.usage_statistics.usage_statistics import (
  File "/Users/okokes/.pyenv/versions/3.7.7/lib/python3.7/site-packages/great_expectations/core/usage_statistics/usage_statistics.py", line 20, in <module>
    from great_expectations.core.usage_statistics.anonymizers.data_docs_site_anonymizer import (
  File "/Users/okokes/.pyenv/versions/3.7.7/lib/python3.7/site-packages/great_expectations/core/usage_statistics/anonymizers/data_docs_site_anonymizer.py", line 2, in <module>
    from great_expectations.core.usage_statistics.anonymizers.site_builder_anonymizer import (
  File "/Users/okokes/.pyenv/versions/3.7.7/lib/python3.7/site-packages/great_expectations/core/usage_statistics/anonymizers/site_builder_anonymizer.py", line 2, in <module>
    from great_expectations.render.renderer.site_builder import (
  File "/Users/okokes/.pyenv/versions/3.7.7/lib/python3.7/site-packages/great_expectations/render/renderer/__init__.py", line 7, in <module>
    from .other_section_renderer import ProfilingResultsOverviewSectionRenderer
  File "/Users/okokes/.pyenv/versions/3.7.7/lib/python3.7/site-packages/great_expectations/render/renderer/other_section_renderer.py", line 4, in <module>
    from great_expectations.profile.basic_dataset_profiler import BasicDatasetProfiler
  File "/Users/okokes/.pyenv/versions/3.7.7/lib/python3.7/site-packages/great_expectations/profile/__init__.py", line 1, in <module>
    from .basic_dataset_profiler import BasicDatasetProfiler
  File "/Users/okokes/.pyenv/versions/3.7.7/lib/python3.7/site-packages/great_expectations/profile/basic_dataset_profiler.py", line 3, in <module>
    from great_expectations.profile.base import (
  File "/Users/okokes/.pyenv/versions/3.7.7/lib/python3.7/site-packages/great_expectations/profile/base.py", line 8, in <module>
    from ..dataset import Dataset
  File "/Users/okokes/.pyenv/versions/3.7.7/lib/python3.7/site-packages/great_expectations/dataset/__init__.py", line 3, in <module>
    from .dataset import Dataset
  File "/Users/okokes/.pyenv/versions/3.7.7/lib/python3.7/site-packages/great_expectations/dataset/dataset.py", line 13, in <module>
    from great_expectations.dataset.util import (
  File "/Users/okokes/.pyenv/versions/3.7.7/lib/python3.7/site-packages/great_expectations/dataset/util.py", line 578, in <module>
    selects: List[WithinGroup], sql_engine_dialect: DefaultDialect
NameError: name 'WithinGroup' is not defined
</pre>
</details>

**Comment by eugmandel** [comment]
@kokes SQLAlchemy is one of the optional dependencies in GE. We made the decision to make it optional in order to keep the size of the package smaller and not to force dependencies that some users do not need. Same logic applies to pyspark.

When you run the CLI and choose to connect to a database, the command displays an error message saying that SQLAlchemy is missing. 

We just had a hackathon where one of the projects goes one step beyond displaying the error - the command offers to install SQLAlchemy and keep running. This feels like a more pleasant user experience and we are planning to finalize and merge this change.

**Comment by kokes** [comment]
@eugmandel I understand that, but GE crashes *before* I connect to a database, before I do anything, really. And it’s not a “I don’t have SQLAlchemy error”, it’s due to a lack of type information.

I even included a trivial way to reproduce the problem.
