### ISSUE TITLE
MetricStore backend cannot accept a `connection_string`

### ISSUE THREAD

**Issue by Aylr** [fivetran/great_expectations#1630]
**Describe the bug**
MetricStore backend cannot accept a `connection_string`.

**To Reproduce**

1. configure a metric store as follows

```yaml
metrics_store:  # You can choose any name for your metric store
    class_name: MetricStore
    store_backend:
        class_name: DatabaseStoreBackend
        # These credentials can be the same as those used in a Datasource configuration
        credentials:
          connection_string: sqlite:///metric_store.db
```
2. run `great_expectations suite list` and note error output:

```
$ great_expectations suite list
Traceback (most recent call last):
  File "c:\users\t.gluck\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\t.gluck\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\t.gluck\Anaconda3\Scripts\great_expectations.exe\__main__.py", line 9, in <module>
  File "c:\users\t.gluck\anaconda3\lib\site-packages\great_expectations\cli\cli.py", line 65, in main
    cli()
  File "c:\users\t.gluck\anaconda3\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\t.gluck\anaconda3\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\t.gluck\anaconda3\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\t.gluck\anaconda3\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\t.gluck\anaconda3\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\t.gluck\anaconda3\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\t.gluck\anaconda3\lib\site-packages\great_expectations\cli\suite.py", line 450, in suite_list
    context = toolkit.load_data_context_with_error_handling(directory)
  File "c:\users\t.gluck\anaconda3\lib\site-packages\great_expectations\cli\toolkit.py", line 402, in load_data_context_with_error_handling
    context = DataContext(directory)
  File "c:\users\t.gluck\anaconda3\lib\site-packages\great_expectations\data_context\data_context.py", line 2147, in __init__
    project_config, context_root_directory, runtime_environment
  File "c:\users\t.gluck\anaconda3\lib\site-packages\great_expectations\core\usage_statistics\usage_statistics.py", line 245, in usage_statistics_wrapped_method
    result = func(*args, **kwargs)
  File "c:\users\t.gluck\anaconda3\lib\site-packages\great_expectations\data_context\data_context.py", line 168, in __init__
    self._init_stores(self._project_config_with_variables_substituted.stores)
  File "c:\users\t.gluck\anaconda3\lib\site-packages\great_expectations\data_context\data_context.py", line 220, in _init_stores
    self._build_store(store_name, store_config)
  File "c:\users\t.gluck\anaconda3\lib\site-packages\great_expectations\data_context\data_context.py", line 190, in _build_store
    config_defaults={"module_name": module_name},
  File "c:\users\t.gluck\anaconda3\lib\site-packages\great_expectations\data_context\util.py", line 101, in instantiate_class_from_config
    class_instance = class_(**config_with_defaults)
  File "c:\users\t.gluck\anaconda3\lib\site-packages\great_expectations\data_context\store\metric_store.py", line 51, in __init__
    super().__init__(store_backend=store_backend)
  File "c:\users\t.gluck\anaconda3\lib\site-packages\great_expectations\data_context\store\store.py", line 35, in __init__
    config_defaults={"module_name": module_name},
  File "c:\users\t.gluck\anaconda3\lib\site-packages\great_expectations\data_context\util.py", line 101, in instantiate_class_from_config
    class_instance = class_(**config_with_defaults)
  File "c:\users\t.gluck\anaconda3\lib\site-packages\great_expectations\data_context\store\database_store_backend.py", line 43, in __init__
    drivername = credentials.pop("drivername")
KeyError: 'drivername'
```

**Expected behavior**

**Environment (please complete the following information):**
 - OS: [e.g. iOS] macOS ge 0.11.3, Windows 10 GE 0.11.4
 - GE Version: [e.g. 0.10.0]

**Additional context**

**Comment by talagluck** [comment]
```
$ great_expectations suite list
Traceback (most recent call last):
  File "c:\users\t.gluck\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\t.gluck\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\t.gluck\Anaconda3\Scripts\great_expectations.exe\__main__.py", line 9, in <module>
  File "c:\users\t.gluck\anaconda3\lib\site-packages\great_expectations\cli\cli.py", line 65, in main
    cli()
  File "c:\users\t.gluck\anaconda3\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\t.gluck\anaconda3\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\t.gluck\anaconda3\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\t.gluck\anaconda3\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\t.gluck\anaconda3\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\t.gluck\anaconda3\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\t.gluck\anaconda3\lib\site-packages\great_expectations\cli\suite.py", line 450, in suite_list
    context = toolkit.load_data_context_with_error_handling(directory)
  File "c:\users\t.gluck\anaconda3\lib\site-packages\great_expectations\cli\toolkit.py", line 402, in load_data_context_with_error_handling
    context = DataContext(directory)
  File "c:\users\t.gluck\anaconda3\lib\site-packages\great_expectations\data_context\data_context.py", line 2147, in __init__
    project_config, context_root_directory, runtime_environment
  File "c:\users\t.gluck\anaconda3\lib\site-packages\great_expectations\core\usage_statistics\usage_statistics.py", line 245, in usage_statistics_wrapped_method
    result = func(*args, **kwargs)
  File "c:\users\t.gluck\anaconda3\lib\site-packages\great_expectations\data_context\data_context.py", line 168, in __init__
    self._init_stores(self._project_config_with_variables_substituted.stores)
  File "c:\users\t.gluck\anaconda3\lib\site-packages\great_expectations\data_context\data_context.py", line 220, in _init_stores
    self._build_store(store_name, store_config)
  File "c:\users\t.gluck\anaconda3\lib\site-packages\great_expectations\data_context\data_context.py", line 190, in _build_store
    config_defaults={"module_name": module_name},
  File "c:\users\t.gluck\anaconda3\lib\site-packages\great_expectations\data_context\util.py", line 101, in instantiate_class_from_config
    class_instance = class_(**config_with_defaults)
  File "c:\users\t.gluck\anaconda3\lib\site-packages\great_expectations\data_context\store\metric_store.py", line 51, in __init__
    super().__init__(store_backend=store_backend)
  File "c:\users\t.gluck\anaconda3\lib\site-packages\great_expectations\data_context\store\store.py", line 35, in __init__
    config_defaults={"module_name": module_name},
  File "c:\users\t.gluck\anaconda3\lib\site-packages\great_expectations\data_context\util.py", line 101, in instantiate_class_from_config
    class_instance = class_(**config_with_defaults)
  File "c:\users\t.gluck\anaconda3\lib\site-packages\great_expectations\data_context\store\database_store_backend.py", line 43, in __init__
    drivername = credentials.pop("drivername")
KeyError: 'drivername'
```
