### ISSUE TITLE
Several problems with `datasource new` for Snowflake

### ISSUE THREAD

**Issue by spbail** [fivetran/great_expectations#1855]
**Describe the bug**
Unsure whether this is specific to Snowflake connections or general, but I found several types of unexpected behavior when creating a new Snowflake datasource with the same name as an existing one

**To Reproduce**

- I have an existing datasource `my_snowflake_db` with credentials stored in config_variables.yml
- I run `ge datasource new` and just hit enter on the prompt to use the default (empty strings)
This will produce the output I've posted below. It will also overwrite the existing credentials in config_variables.yml with the empty strings.

**Expected behavior**
This actually did 3 things I did not expect:

1. I was not prompted whether I wanted to overwrite the existing datasource with the same name. I would expect that to happen immediately after selecting the same name.
2. The CLI actually continued after "Attempting to connect to your database. This may take a moment..." - I would expect it to detect that the connection isn't working, and prompt to re-enter the creds.
3. Even though the datasource creation failed, it overwrote the creds in config_variables.yml with the blank defaults. I would not expect GE to write any configs if there's a failure in the CLI workflow. I filed a separate issue in #1859 since this seems to happen with all db engines.

**Environment (please complete the following information):**
 - OS: Mac OS
 - GE Version: 0.12.0

**Additional context**
Terminal dump:

```What data would you like Great Expectations to connect to?
    1. Files on a filesystem (for processing with Pandas or Spark)
    2. Relational database (SQL)
: 2

Which database backend are you using?
    1. MySQL
    2. Postgres
    3. Redshift
    4. Snowflake
    5. BigQuery
    6. other - Do you have a working SQLAlchemy connection string?
: 4

Give your new Datasource a short name.
 [my_snowflake_db]:

Next, we will configure database credentials and store them in the `my_snowflake_db` section
of this config file: great_expectations/uncommitted/config_variables.yml:

What authentication method would you like to use?
    1. User and Password
    2. Single sign-on (SSO)
    3. Key pair authentication
: 1
What is the user login name for the snowflake connection? []:
What is the account name for the snowflake connection (include region -- ex 'ABCD.us-east-1')? []:
What is database name for the snowflake connection? (optional -- leave blank for none) []:
What is schema name for the snowflake connection? (optional -- leave blank for none) []:
What is warehouse name for the snowflake connection? (optional -- leave blank for none) []:
What is role name for the snowflake connection? (optional -- leave blank for none) []:
What is the password for the snowflake connection?:
Attempting to connect to your database. This may take a moment...

Great Expectations will now add a new Datasource 'my_snowflake_db' to your deployment, by adding this entry to your great_expectations.yml:

  my_snowflake_db:
    credentials: ${my_snowflake_db}
    data_asset_type:
      class_name: SqlAlchemyDataset
      module_name: great_expectations.dataset
    class_name: SqlAlchemyDatasource
    module_name: great_expectations.datasource

The credentials will be saved in uncommitted/config_variables.yml under the key 'my_snowflake_db'

Would you like to proceed? [Y/n]:
Traceback (most recent call last):
  File "/opt/miniconda3/bin/great_expectations", line 8, in <module>
    sys.exit(main())
  File "/opt/miniconda3/lib/python3.7/site-packages/great_expectations/cli/cli.py", line 73, in main
    cli()
  File "/opt/miniconda3/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/miniconda3/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/miniconda3/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/miniconda3/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/miniconda3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/miniconda3/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/miniconda3/lib/python3.7/site-packages/great_expectations/cli/datasource.py", line 83, in datasource_new
    datasource_name, data_source_type = add_datasource(context)
  File "/opt/miniconda3/lib/python3.7/site-packages/great_expectations/cli/datasource.py", line 332, in add_datasource
    datasource_name = _add_sqlalchemy_datasource(context)
  File "/opt/miniconda3/lib/python3.7/site-packages/great_expectations/cli/datasource.py", line 532, in _add_sqlalchemy_datasource
    context.add_datasource(name=datasource_name, **configuration)
  File "/opt/miniconda3/lib/python3.7/site-packages/great_expectations/data_context/data_context.py", line 2346, in add_datasource
    new_datasource = super().add_datasource(name, **kwargs)
  File "/opt/miniconda3/lib/python3.7/site-packages/great_expectations/core/usage_statistics/usage_statistics.py", line 257, in usage_statistics_wrapped_method
    result = func(*args, **kwargs)
  File "/opt/miniconda3/lib/python3.7/site-packages/great_expectations/data_context/data_context.py", line 1061, in add_datasource
    name, self._project_config_with_variables_substituted.datasources[name]
  File "/opt/miniconda3/lib/python3.7/site-packages/great_expectations/data_context/data_context.py", line 1103, in _build_datasource_from_config
    config_defaults={"module_name": module_name},
  File "/opt/miniconda3/lib/python3.7/site-packages/great_expectations/data_context/util.py", line 84, in instantiate_class_from_config
    class_instance = class_(**config_with_defaults)
  File "/opt/miniconda3/lib/python3.7/site-packages/great_expectations/datasource/sqlalchemy_datasource.py", line 260, in __init__
    self.engine = create_engine(options, **create_engine_kwargs)
  File "/opt/miniconda3/lib/python3.7/site-packages/sqlalchemy/engine/__init__.py", line 500, in create_engine
    return strategy.create(*args, **kwargs)
  File "/opt/miniconda3/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 98, in create
    (cargs, cparams) = dialect.create_connect_args(u)
  File "/opt/miniconda3/lib/python3.7/site-packages/snowflake/sqlalchemy/snowdialect.py", line 158, in create_connect_args
    if '.snowflakecomputing.com' not in opts['host'] and not opts.get(
KeyError: 'host'```

**Comment by eugmandel** [comment]
Triaged today. This looks like a potential regression. Adding to the queue, but don't have a ETA yet.
