### ISSUE TITLE
great_expectations init with snowflake causes idna<2.10 error

### ISSUE THREAD

**Issue by joshuataylor** [fivetran/great_expectations#1878]
**Describe the bug**
When running `great_expectations init` for the first time, the following error occurs:
```
$ great_expectations init
  ___              _     ___                  _        _   _
 / __|_ _ ___ __ _| |_  | __|_ ___ __  ___ __| |_ __ _| |_(_)___ _ _  ___                                                                                                 
| (_ | '_/ -_) _` |  _| | _|\ \ / '_ \/ -_) _|  _/ _` |  _| / _ \ ' \(_-<                                                                                                 
 \___|_| \___\__,_|\__| |___/_\_\ .__/\___\__|\__\__,_|\__|_\___/_||_/__/                                                                                                 
                                |_|                                                                                                                                       
             ~ Always know what to expect from your data ~                                                                                                                

Let's configure a new Data Context.

First, Great Expectations will create a new directory:

    great_expectations
    |-- great_expectations.yml
    |-- expectations
    |-- checkpoints
    |-- notebooks
    |-- plugins
    |-- .gitignore
    |-- uncommitted
        |-- config_variables.yml
        |-- documentation
        |-- validations

OK to proceed? [Y/n]: y

================================================================================

Would you like to configure a Datasource? [Y/n]: y

What data would you like Great Expectations to connect to?
    1. Files on a filesystem (for processing with Pandas or Spark)
    2. Relational database (SQL)
: 2
Great Expectations relies on the library `sqlalchemy` to connect to your data, but the package `sqlalchemy` containing this library is not installed.
    Would you like Great Expectations to try to execute `pip install sqlalchemy` for you? [Y/n]: y
pip install sqlalchemy  [####################################]  100%          

Which database backend are you using?
    1. MySQL
    2. Postgres
    3. Redshift
    4. Snowflake
    5. BigQuery
    6. other - Do you have a working SQLAlchemy connection string?
: 4

Give your new Datasource a short name.
 [my_snowflake_db]: foobar_snowflake

Next, we will configure database credentials and store them in the `foobar_snowflake` section
of this config file: great_expectations/uncommitted/config_variables.yml:

Great Expectations relies on the library `snowflake.sqlalchemy.snowdialect` to connect to your data, but the package `snowflake-sqlalchemy` containing this library is not installed.
    Would you like Great Expectations to try to execute `pip install snowflake-sqlalchemy` for you? [Y/n]: y
pip install snowflake-sqlalchemy  [####################################]  100%          
Traceback (most recent call last):
  File "/home/josh/dev/foobar-great-expectations/venv/bin/great_expectations", line 8, in <module>
    sys.exit(main())
  File "/home/josh/dev/foobar-great-expectations/venv/lib/python3.8/site-packages/great_expectations/cli/cli.py", line 73, in main
    cli()
  File "/home/josh/dev/foobar-great-expectations/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/josh/dev/foobar-great-expectations/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/josh/dev/foobar-great-expectations/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/josh/dev/foobar-great-expectations/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/josh/dev/foobar-great-expectations/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/josh/dev/foobar-great-expectations/venv/lib/python3.8/site-packages/great_expectations/cli/init.py", line 127, in init
    datasource_name, data_source_type = add_datasource_impl(
  File "/home/josh/dev/foobar-great-expectations/venv/lib/python3.8/site-packages/great_expectations/cli/datasource.py", line 332, in add_datasource
    datasource_name = _add_sqlalchemy_datasource(context)
  File "/home/josh/dev/foobar-great-expectations/venv/lib/python3.8/site-packages/great_expectations/cli/datasource.py", line 474, in _add_sqlalchemy_datasource
    if not _verify_snowflake_dependent_modules():
  File "/home/josh/dev/foobar-great-expectations/venv/lib/python3.8/site-packages/great_expectations/cli/datasource.py", line 1381, in _verify_snowflake_dependent_modules
    return verify_library_dependent_modules(
  File "/home/josh/dev/foobar-great-expectations/venv/lib/python3.8/site-packages/great_expectations/cli/util.py", line 146, in verify_library_dependent_modules
    library_status_code = library_install_load_check(
  File "/home/josh/dev/foobar-great-expectations/venv/lib/python3.8/site-packages/great_expectations/cli/util.py", line 212, in library_install_load_check
    distr: Distribution = pkg_resources.get_distribution(dist=pip_library_name)
  File "/home/josh/dev/foobar-great-expectations/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 481, in get_distribution
    dist = get_provider(dist)
  File "/home/josh/dev/foobar-great-expectations/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 357, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/home/josh/dev/foobar-great-expectations/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/josh/dev/foobar-great-expectations/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (idna 2.10 (/home/josh/dev/foobar-great-expectations/venv/lib/python3.8/site-packages), Requirement.parse('idna<2.10'), {'snowflake-connector-python'})
```

**To Reproduce**
1. Setup a new environment with just great expectations
2. Run init
3. Choose the options to create snowflake, installing the dependencies.

**Expected behavior**
It does not error.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - GE Version: 0.12.1

**Comment by eugmandel** [comment]
@joshuataylor Thank you for reporting this issue! The great_expectations CLI offers the user to install the Snowflake SQLAlchemy connector if it is missing. If the user agrees, the CLI just calls pip install. 

Could you please check if this issue persists if you install the connector yourself before installing Great Expectations?

**Comment by joshuataylor** [comment]
Yep, sorry, I should have clarified that after quitting out and installing it manually, the install works as expected.
