### ISSUE TITLE
ERROR: TypeError: Keys in TupleS3StoreBackend must be instances of <class 'tuple'>, not <class 'great_expectations.data_context.types.resource_identifiers.ValidationResultIdentifier'>

### ISSUE THREAD

**Issue by eugmandel** [fivetran/great_expectations#1907]
A few users reported this error, but we do not have precise steps to reproduce this - in progress...
TODO: fill in the details

**Describe the bug**
TODO

**To Reproduce**
TODO

**Expected behavior**
Error should not happen

**Environment (please complete the following information):**
 - GE Version: [e.g. 0.10.0]

**Additional context**

**Comment by jameskeegan** [comment]
Got this same issue when trying to build data docs to our company site.

Issue goes away when you delete the existing contents of the site from s3 and then run validations, but then of course reappears the next time.

Happening on 0.12.0 of GE on Windows and 0.12.1 on Ubuntu.

**Comment by spbail** [comment]
Another example here: https://greatexpectationstalk.slack.com/archives/CUUMYDJAX/p1597954314013700

See this Slack message for the same with `ExpectationSuite` instead of `ValidationResultIdentifier`: https://greatexpectationstalk.slack.com/archives/CUTCNHN82/p1600718063029700

**Comment by eugmandel** [comment]
Triaged - this is a real bug, the core team is working on reproducing and fixing it.

**Comment by lcorneliussen** [comment]
I have the same problem. Getting GE and Prefect running on Azure Container Instances - a week in, after having fought 20 other things :D

As this worked earlier, I tried to track down which dependencies might be involved - but doesn't seem to be a dependency. These are versions of dependencies that changed in september, here with the original version from sept 1st:

```
toolz==0.10.0
numpy==1.19.1
pandas==1.1.1
attrs==20.1.0
pyrsistent==0.16.0
zipp==3.1.0
importlib-metadata==1.7.0
traitlets==5.0.0
pygments==2.6.1
bleach==3.1.5
nbconvert==5.6.1
cffi==1.14.2
terminado==0.8.3
notebook==6.1.3
ruamel.yaml.clib==0.2.0
ruamel.yaml==0.16.10
great-expectations==0.12.0
marshmallow==3.7.1
dask==2.25.0
distributed==2.25.0
prefect==0.13.5
botocore==1.17.53
boto3==1.14.53
```

**Comment by lcorneliussen** [comment]
@eugmandel I get this error when running GE based on the docker image `45110011/pyodbc-base:v1`

**Comment by anthonyburdi** [comment]
Hi all - we have been trying many different configurations over the past few days to try to reproduce this bug. 

The closest we have come is to remove validations from our validation store (.json), but leave them in our data docs validations directory (.html). The error we reproduced was not exactly the same as what is mentioned as this issue (and deserves attention):
```
ParamValidationError: Parameter validation failed:
Invalid type for parameter Prefix, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
```
However - can anyone help with a specific set of steps to reproduce? Perhaps with a simple Great Expectations setup using just s3 and local filesystem (and no sensitive info so we can share). Please share your great_expectations.yml, the version of GE you are using, your OS, python version, any other configuration details (e.g. output of `pip freeze`) and what was / wasn't in your metadata store bucket(s) when you encounter the error (actually a `tree` of your buckets would be super helpful!).

**Comment by lcorneliussen** [comment]
What about a debugging zoom call on monday? And if we can’t fix it, I can give access to my repo or share all files

_
Lars Corneliussen
________________________________
Von: anthonyburdi <notifications@github.com>
Gesendet: Friday, September 25, 2020 9:26:10 PM
An: great-expectations/great_expectations <great_expectations@noreply.github.com>
Cc: Lars Corneliussen <lars@corneliussen.de>; Comment <comment@noreply.github.com>
Betreff: Re: [great-expectations/great_expectations] ERROR: TypeError: Keys in TupleS3StoreBackend must be instances of <class 'tuple'>, not <class 'great_expectations.data_context.types.resource_identifiers.ValidationResultIdentifier'> (#1907)


Hi all - we have been trying many different configurations over the past few days to try to reproduce this bug.

The closest we have come is to remove validations from our validation store (.json), but leave them in our data docs validations directory (.html). The error we reproduced was not exactly the same as what is mentioned as this issue (and deserves attention):

ParamValidationError: Parameter validation failed:
Invalid type for parameter Prefix, value: None, type: <class 'NoneType'>, valid types: <class 'str'>


However - can anyone help with a specific set of steps to reproduce? Perhaps with a simple Great Expectations setup using just s3 and local filesystem (and no sensitive info so we can share). Please share your great_expectations.yml, the version of GE you are using, your OS, python version, any other configuration details (e.g. output of pip freeze) and what was / wasn't in your metadata store bucket(s) when you encounter the error (actually a tree of your buckets would be super helpful!).

**Comment by NiallRees** [comment]
This error crops up weekly for me so if you've not tracked it down next time it occurs I will do some debugging.

**Comment by melaoni** [comment]
Hi, I was able to get a stacktrace of when the "must be tuple not ValidationResultIdentifier" error is happening. For my case, the issue starts at [site_builder.py#L769](https://github.com/great-expectations/great_expectations/blame/29190428e345c2a89671d94054478693211a36da/great_expectations/render/renderer/site_builder.py#L769).

Below is a screenshot of the stacktrace:
![stacktrace](https://user-images.githubusercontent.com/9522388/94506600-c173f600-01db-11eb-8457-2d3e359e291a.png)

**Environment:**
Running inside a Centos dev container, Python 3.7.7
```
great-expectations==0.12.1
boto3==1.13.22
botocore==1.16.22
numpy==1.18.4
pandas==0.25.3
```

**Metadata store yaml configs sample:**
```
stores:
  expectations_store:
    class_name: ExpectationsStore
    store_backend:
      class_name: TupleS3StoreBackend
      bucket: myBucket
      prefix: stores/expectations/
 
  validations_store:
    class_name: ValidationsStore
    store_backend:
      class_name: TupleS3StoreBackend
      bucket: myBucket
      prefix: stores/validations/

data_docs_sites:
  s3_site:
    class_name: SiteBuilder
    show_how_to_buttons: false
    store_backend:
      class_name: TupleS3StoreBackend
      bucket: myBucket
      prefix: docs/
    site_index_builder:
      class_name: DefaultSiteIndexBuilder
```
**Other notes:**
I couldn't get a tree of the bucket content due to my S3 permission restrictions. I am in the process of migrating from GE 0.10.x to 0.12.1, the bucket has files/directories with the old naming convention (pre 0.11.x) that I have yet to move over. 
However, I'm not sure if those files are the cause of issue. In https://greatexpectationstalk.slack.com/archives/CUTCNHN82/p1599650889160100, it was mentioned that the ExpectationSuiteIdentifier version of the exception occurs whenever there is previous validation in the store.

Please let me know if there's more info I could provide!

**Comment by lcorneliussen** [comment]
We did some debugging with @anthonyburdi yesterday. It seems that GE is getting the current contents of the S3 bucket, then running some kind of validation (maybe determining if the file should be kept in S3 or deleted) and storing that in a `ValidationResultIdentifier` which is created using `from_tuple` [here](https://github.com/great-expectations/great_expectations/blob/29190428e345c2a89671d94054478693211a36da/great_expectations/render/renderer/site_builder.py#L710)

Then it figures out which of theses to remove, and runs the deletion using ValidationResultIdentifier instead of the corresponding tuple that specifies the path.

A naive fix in [site_builder.py](https://github.com/great-expectations/great_expectations/blob/29190428e345c2a89671d94054478693211a36da/great_expectations/render/renderer/site_builder.py#L721) replacing `.remove_key(expectation_suite_site_key)` with `.remove_key(expectation_suite_site_key.to_tuple())` yielded a different error. But at least it is a starting point.

```
validation_and_profiling_result_source_keys = self.data_context.stores[
    self.site_section_builders_config[source_store].get("source_store_name")
].list_keys()
validation_and_profiling_result_site_keys = [
>>  ValidationResultIdentifier.from_tuple(validation_result_tuple)
    for validation_result_tuple in self.target_store.store_backends[
        ValidationResultIdentifier
    ].list_keys()
]

if skip_and_clean_missing:
    cleaned_keys = []
    for (
        validation_result_site_key
    ) in validation_and_profiling_result_site_keys:
        if (
            validation_result_site_key
            not in validation_and_profiling_result_source_keys
        ):
            self.target_store.store_backends[
                ValidationResultIdentifier
>>          ].remove_key(validation_result_site_key)
        else:
            cleaned_keys.append(validation_result_site_key)
    validation_and_profiling_result_site_keys = cleaned_keys
```

**Comment by lcorneliussen** [comment]
Seems like the code that has problems was introduced here:
https://github.com/great-expectations/great_expectations/commit/3216afe1d755d0d6327c8358fafeb8e4952cb4b0

Currently in my case it is failing everytime I redeploy my container, as this also resets the validation results. I guess I'd have to use some kind of store to keep validations around, so they are rebuilt as part of the data docs generation?

**Comment by lcorneliussen** [comment]
It would be nice if one could set skip_and_clean_missing to false from yaml. In my case where I launch fresh containers this would be useful anyway. And it would, for now, most probably give a workaround for the bug.

https://github.com/great-expectations/great_expectations/blob/29190428e345c2a89671d94054478693211a36da/great_expectations/render/renderer/site_builder.py#L292

**Comment by anthonyburdi** [comment]
Just a heads up - I was able to replicate this issue locally and am working on a fix. Thank you for all the help and I will keep you posted!

**Comment by anthonyburdi** [comment]
It turned out to be a tiny fix to Great Expectations v0.12.3 - if you have time please use the branch from the linked PR here and let me know if you still get errors in your environment. If this fix is successful, it will roll out in the next release of Great Expectations. 🤞

**Comment by NiallRees** [comment]
@anthonyburdi That's done it for me! Thanks.

**Comment by melaoni** [comment]
My particular issue was fixed after upgrading to just v0.12.3!
It seems to be done by this pull request: https://github.com/great-expectations/great_expectations/pull/1912 that was released in v0.12.3.

**Comment by melaoni** [comment]
Thank you for looking at the issue! 😄

**Comment by sivamohank** [comment]
ip-10-192-20-158.us-east-2.compute.internal
*** Reading remote log from Cloudwatch log_group: airflow-MWAAAIR1-Task log_stream: dag_id=snowflake_data_validation_gx/run_id=manual__2024-10-13T19_22_39.150804+00_00/task_id=validate_snowflake_data/attempt=1.log.
[2024-10-13, 19:22:44 UTC] {local_task_job_runner.py:123} ▶ Pre task execution logs
[2024-10-13, 19:22:44 UTC] {great_expectations.py:581} INFO - Running validation with Great Expectations...
[2024-10-13, 19:22:44 UTC] {great_expectations.py:583} INFO - Instantiating Data Context...
[2024-10-13, 19:22:44 UTC] {context_factory.py:390} INFO - Could not find local file-backed GX project
[2024-10-13, 19:22:44 UTC] {config.py:187} INFO - Loading 'datasources' ->
[]
[2024-10-13, 19:22:45 UTC] {great_expectations.py:599} INFO - Creating Checkpoint...
[2024-10-13, 19:22:45 UTC] {great_expectations.py:618} INFO - Running Checkpoint...
[2024-10-13, 19:22:45 UTC] {batch_filter.py:251} INFO - batch_slice: -1 was parsed to: slice(-1, None, None)
[2024-10-13, 19:22:45 UTC] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.11.9, Platform: Linux-5.10.226-214.879.amzn2.x86_64-x86_64-with-glibc2.34
[2024-10-13, 19:22:45 UTC] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2024-10-13, 19:22:45 UTC] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-10-13, 19:22:46 UTC] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2024-10-13, 19:22:46 UTC] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2024-10-13, 19:22:46 UTC] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2024-10-13, 19:22:47 UTC] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2024-10-13, 19:22:47 UTC] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2024-10-13, 19:22:47 UTC] {validator.py:1467} INFO - 	3 expectation(s) included in expectation_suite.
[2024-10-13, 19:22:47 UTC] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/great_expectations_provider/operators/great_expectations.py", line 625, in execute
    result = self.checkpoint.run()
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/great_expectations/checkpoint/checkpoint.py", line 1264, in run
    return super().run(
           ^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/great_expectations/core/usage_statistics/usage_statistics.py", line 266, in usage_statistics_wrapped_method
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/great_expectations/checkpoint/checkpoint.py", line 305, in run
    self._run_validation(
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/great_expectations/checkpoint/checkpoint.py", line 531, in _run_validation
    async_validation_operator_result = async_executor.submit(
                                       ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/great_expectations/core/async_executor.py", line 106, in submit
    return AsyncResult(value=fn(*args, **kwargs))
                             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/great_expectations/validation_operators/validation_operators.py", line 380, in run
    async_executor.submit(
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/great_expectations/core/async_executor.py", line 106, in submit
    return AsyncResult(value=fn(*args, **kwargs))
                             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/great_expectations/validator/validator.py", line 1632, in validate
    data_context.evaluation_parameter_store.get_bind_params(run_id)
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/great_expectations/data_context/store/metric_store.py", line 109, in get_bind_params
    params[key.to_evaluation_parameter_urn()] = self.get(key)  # type: ignore[attr-defined]
                                                ^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/great_expectations/data_context/store/store.py", line 206, in get
    self._validate_key(key)
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/great_expectations/data_context/store/store.py", line 128, in _validate_key
    raise TypeError(
TypeError: key must be an instance of ValidationMetricIdentifier, not <class 'str'>
[2024-10-13, 19:22:47 UTC] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=snowflake_data_validation_gx, task_id=validate_snowflake_data, run_id=manual__2024-10-13T19:22:39.150804+00:00, execution_date=20241013T192239, start_date=20241013T192244, end_date=20241013T192247
[2024-10-13, 19:22:47 UTC] {taskinstance.py:340} ▶ Post task execution logs
