### ISSUE TITLE
S3 datadocs failing to build - 0.12.3

### ISSUE THREAD

**Issue by NiallRees** [fivetran/great_expectations#1965]
**Describe the bug**
Randomly started in the middle of the night. I will do a bit of debugging this morning to try and work out what's going on, but here's a stack trace:

```
ERROR:great_expectations.validation_operators.validation_operators:Error running action with name update_data_docs
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/great_expectations/validation_operators/validation_operators.py", line 384, in _run_actions
    payload=batch_actions_results,
  File "/usr/local/lib/python3.7/site-packages/great_expectations/validation_operators/actions.py", line 50, in run
    **kwargs
  File "/usr/local/lib/python3.7/site-packages/great_expectations/validation_operators/actions.py", line 442, in _run
    resource_identifiers=[validation_result_suite_identifier],
  File "/usr/local/lib/python3.7/site-packages/great_expectations/core/usage_statistics/usage_statistics.py", line 257, in usage_statistics_wrapped_method
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/great_expectations/data_context/data_context.py", line 1575, in build_data_docs
    resource_identifiers
  File "/usr/local/lib/python3.7/site-packages/great_expectations/render/renderer/site_builder.py", line 292, in build
    index_page_resource_identifier_tuple = self.site_index_builder.build()
  File "/usr/local/lib/python3.7/site-packages/great_expectations/render/renderer/site_builder.py", line 769, in build
    ].remove_key(validation_result_site_key)
  File "/usr/local/lib/python3.7/site-packages/great_expectations/data_context/store/tuple_store_backend.py", line 590, in remove_key
    Bucket=self.bucket, Prefix=self.prefix
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 337, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 629, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 677, in _convert_to_request_dict
    api_params, operation_model)
  File "/usr/local/lib/python3.7/site-packages/botocore/validate.py", line 297, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter Prefix, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
```

**Comment by NiallRees** [comment]
Done some digging:

Is it 'normal' that TupleS3StoreBackend should be instantiated with a prefix of None? There's a catch here I can't understand:

https://github.com/great-expectations/great_expectations/blob/93419b01c226bb52c5f87076c4884f63092e6b88/great_expectations/data_context/store/tuple_store_backend.py#L396-L404

What's happening is that 

https://github.com/great-expectations/great_expectations/blob/93419b01c226bb52c5f87076c4884f63092e6b88/great_expectations/data_context/store/tuple_store_backend.py#L589-L591

is failing, with a response of

```
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter Prefix, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
```

because the prefix is None, and is then not getting caught here

https://github.com/great-expectations/great_expectations/blob/93419b01c226bb52c5f87076c4884f63092e6b88/great_expectations/data_context/store/tuple_store_backend.py#L602

**Comment by NiallRees** [comment]
Tested and fixed by https://github.com/great-expectations/great_expectations/pull/1937
