### ISSUE TITLE
custom_sql parameter in SQLAlchemyDataset throws an error in Teradata

### ISSUE THREAD

**Issue by DXcarlos** [fivetran/great_expectations#2047]
**Describe the bug**
Hey guys custm_sql in SqlAlchemyDataset doesn't work in Teradata because it's translate to "CREATE TEMPORARY TABLE ..." and in Teradata Temporary Table doesn't exists, we should use VOLATILE TABLE instead.

**To Reproduce**
First create a database engine with a Teradata connecttion and use the custom_sql parameter in SqlAlchemyDataset

``` python
mt_dataset = SqlAlchemyDataset(custom_sql="SELECT * FROM dbi_min.mt_online_dataset_replica 
WHERE periodo_planta='2020-09-01'", engine=t_conn)
``` 

``` python
Traceback (most recent call last):
  File "/srv/BigData/dev_sandbox/BI/anaconda3/envs/dev_avybd/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/srv/BigData/dev_sandbox/BI/anaconda3/envs/dev_avybd/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
  File "/srv/BigData/dev_sandbox/BI/anaconda3/envs/dev_avybd/lib/python3.8/site-packages/teradatasql/__init__.py", line 649, in execute
    self.executemany (sOperation, None, ignoreErrors)
  File "/srv/BigData/dev_sandbox/BI/anaconda3/envs/dev_avybd/lib/python3.8/site-packages/teradatasql/__init__.py", line 896, in executemany
    raise OperationalError (sErr)
teradatasql.OperationalError: [Version 17.0.0.6] [Session 40290350] [Teradata Database] [Error 3707] Syntax error, expected something like a 'METHOD' keyword between the 'CREATE' keyword and the 'TEMPORARY' keyword.
 at gosqldriver/teradatasql.(*teradataConnection).formatDatabaseError TeradataConnection.go:1138
 at gosqldriver/teradatasql.(*teradataConnection).makeChainedDatabaseError TeradataConnection.go:1154
 at gosqldriver/teradatasql.(*teradataConnection).processErrorParcel TeradataConnection.go:1217
 at gosqldriver/teradatasql.(*TeradataRows).processResponseBundle TeradataRows.go:1662
 at gosqldriver/teradatasql.(*TeradataRows).executeSQLRequest TeradataRows.go:498
 at gosqldriver/teradatasql.newTeradataRows TeradataRows.go:364
 at gosqldriver/teradatasql.(*teradataStatement).QueryContext TeradataStatement.go:122
 at gosqldriver/teradatasql.(*teradataConnection).QueryContext TeradataConnection.go:2083
 at database/sql.ctxDriverQuery ctxutil.go:48
 at database/sql.(*DB).queryDC.func1 sql.go:1579
 at database/sql.withLock sql.go:3204
 at database/sql.(*DB).queryDC sql.go:1574
 at database/sql.(*Conn).QueryContext sql.go:1823
 at main.goCreateRows goside.go:652
 at main._cgoexpwrap_44b509ff564b_goCreateRows _cgo_gotypes.go:363
 at runtime.cgocallbackg1 cgocall.go:332
 at runtime.cgocallbackg cgocall.go:207
 at runtime.cgocallback_gofunc asm_amd64.s:793
 at runtime.goexit asm_amd64.s:1373
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/srv/BigData/dev_sandbox/BI/anaconda3/envs/dev_avybd/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-11c36e32aadb>", line 1, in <module>
    mt_dataset = SqlAlchemyDataset(custom_sql="SELECT * FROM dbi_min.mt_online_dataset_replica WHERE periodo_planta='2020-09-01'", engine=t_conn)
  File "/srv/BigData/dev_sandbox/BI/anaconda3/envs/dev_avybd/lib/python3.8/site-packages/great_expectations/dataset/sqlalchemy_dataset.py", line 546, in __init__
    self.create_temporary_table(table_name, custom_sql, schema_name=schema)
  File "/srv/BigData/dev_sandbox/BI/anaconda3/envs/dev_avybd/lib/python3.8/site-packages/great_expectations/dataset/sqlalchemy_dataset.py", line 1207, in create_temporary_table
    self.engine.execute(stmt)
  File "/srv/BigData/dev_sandbox/BI/anaconda3/envs/dev_avybd/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2235, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/srv/BigData/dev_sandbox/BI/anaconda3/envs/dev_avybd/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1003, in execute
    return self._execute_text(object_, multiparams, params)
  File "/srv/BigData/dev_sandbox/BI/anaconda3/envs/dev_avybd/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1172, in _execute_text
    ret = self._execute_context(
  File "/srv/BigData/dev_sandbox/BI/anaconda3/envs/dev_avybd/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/srv/BigData/dev_sandbox/BI/anaconda3/envs/dev_avybd/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/srv/BigData/dev_sandbox/BI/anaconda3/envs/dev_avybd/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/srv/BigData/dev_sandbox/BI/anaconda3/envs/dev_avybd/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/srv/BigData/dev_sandbox/BI/anaconda3/envs/dev_avybd/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
  File "/srv/BigData/dev_sandbox/BI/anaconda3/envs/dev_avybd/lib/python3.8/site-packages/teradatasql/__init__.py", line 649, in execute
    self.executemany (sOperation, None, ignoreErrors)
  File "/srv/BigData/dev_sandbox/BI/anaconda3/envs/dev_avybd/lib/python3.8/site-packages/teradatasql/__init__.py", line 896, in executemany
    raise OperationalError (sErr)
sqlalchemy.exc.OperationalError: (teradatasql.OperationalError) [Version 17.0.0.6] [Session 40290350] [Teradata Database] [Error 3707] Syntax error, expected something like a 'METHOD' keyword between the 'CREATE' keyword and the 'TEMPORARY' keyword.
 at gosqldriver/teradatasql.(*teradataConnection).formatDatabaseError TeradataConnection.go:1138
 at gosqldriver/teradatasql.(*teradataConnection).makeChainedDatabaseError TeradataConnection.go:1154
 at gosqldriver/teradatasql.(*teradataConnection).processErrorParcel TeradataConnection.go:1217
 at gosqldriver/teradatasql.(*TeradataRows).processResponseBundle TeradataRows.go:1662
 at gosqldriver/teradatasql.(*TeradataRows).executeSQLRequest TeradataRows.go:498
 at gosqldriver/teradatasql.newTeradataRows TeradataRows.go:364
 at gosqldriver/teradatasql.(*teradataStatement).QueryContext TeradataStatement.go:122
 at gosqldriver/teradatasql.(*teradataConnection).QueryContext TeradataConnection.go:2083
 at database/sql.ctxDriverQuery ctxutil.go:48
 at database/sql.(*DB).queryDC.func1 sql.go:1579
 at database/sql.withLock sql.go:3204
 at database/sql.(*DB).queryDC sql.go:1574
 at database/sql.(*Conn).QueryContext sql.go:1823
 at main.goCreateRows goside.go:652
 at main._cgoexpwrap_44b509ff564b_goCreateRows _cgo_gotypes.go:363
 at runtime.cgocallbackg1 cgocall.go:332
 at runtime.cgocallbackg cgocall.go:207
 at runtime.cgocallback_gofunc asm_amd64.s:793
 at runtime.goexit asm_amd64.s:1373
[SQL: CREATE TEMPORARY TABLE "ge_tmp_2705ebb6" AS SELECT * FROM dbi_min.mt_online_dataset_replica WHERE periodo_planta='2020-09-01']
(Background on this error at: http://sqlalche.me/e/13/e3q8)
```

**Expected behavior**
Create a SQLAlchemyDataset to make expectations

**Environment (please complete the following information):**
 - OS: Linux 64 bits
 - GE Version: 0.12.4

**Comment by eugmandel** [comment]
@DXcarlos thank you for reporting this! We use SQLAlchemy to talk to databases. There are a few areas where various database engines tend to be inconsistent. One these areas is handling of temp tables. Judging the stack trace that you posted, this is the case here.

Teradata is not fully supported by Great Expectations yet: https://github.com/great-expectations/great_expectations/issues/1969

We would love to find community contributors to make Teradata fully work, since users who work with a particular database engine are the best candidates to make these fixes. Is this something you would be interested in? If yes, we will support you through the process of creating and reviewing the PR.
