### ISSUE TITLE
Error in slack_notification Action

### ISSUE THREAD

**Issue by rubenssoto** [fivetran/great_expectations#2062]
Hi Guys,
I have 3 pipelines with great expectations, but one pipeline started to give some errors:

`Error running action with name notify_slack
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/great_expectations/validation_operators/validation_operators.py", line 384, in _run_actions
    payload=batch_actions_results,
  File "/usr/local/lib/python3.7/site-packages/great_expectations/validation_operators/actions.py", line 55, in run
    **kwargs,
  File "/usr/local/lib/python3.7/site-packages/great_expectations/validation_operators/actions.py", line 170, in _run
    validation_result_suite, data_docs_pages, self.notify_with
  File "/usr/local/lib/python3.7/site-packages/great_expectations/render/renderer/slack_renderer.py", line 101, in render
    report_element = self._get_report_element(docs_link)
  File "/usr/local/lib/python3.7/site-packages/great_expectations/render/renderer/slack_renderer.py", line 155, in _get_report_element
    if "file:///" in docs_link:
TypeError: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "fact_demand_coverage_datalake_datasets_job.py", line 90, in <module>
    expectation_suite=expectation_suite_name_for_validations
  File "/mnt1/yarn/usercache/hadoop/appcache/application_1603978914184_5458/container_1603978914184_5458_01_000001/data_quality.zip/data_quality/ge_validation.py", line 174, in validate
  File "/usr/local/lib/python3.7/site-packages/great_expectations/core/usage_statistics/usage_statistics.py", line 257, in usage_statistics_wrapped_method
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/great_expectations/data_context/data_context.py", line 1022, in run_validation_operator
    **kwargs,
  File "/usr/local/lib/python3.7/site-packages/great_expectations/validation_operators/validation_operators.py", line 334, in run
    run_id,
  File "/usr/local/lib/python3.7/site-packages/great_expectations/validation_operators/validation_operators.py", line 399, in _run_actions
    raise e
  File "/usr/local/lib/python3.7/site-packages/great_expectations/validation_operators/validation_operators.py", line 384, in _run_actions
    payload=batch_actions_results,
  File "/usr/local/lib/python3.7/site-packages/great_expectations/validation_operators/actions.py", line 55, in run
    **kwargs,
  File "/usr/local/lib/python3.7/site-packages/great_expectations/validation_operators/actions.py", line 170, in _run
    validation_result_suite, data_docs_pages, self.notify_with
  File "/usr/local/lib/python3.7/site-packages/great_expectations/render/renderer/slack_renderer.py", line 101, in render
    report_element = self._get_report_element(docs_link)
  File "/usr/local/lib/python3.7/site-packages/great_expectations/render/renderer/slack_renderer.py", line 155, in _get_report_element
    if "file:///" in docs_link:
TypeError: argument of type 'NoneType' is not iterable`

The stranger thing with this error, the error doesn't happen every day, for example yesterday it worked fine.

**Comment by rubenssoto** [comment]
I'm running GE on spark.

**Comment by eugmandel** [comment]
Thank you for reporting this, @rubenssoto ! We will triage today.

**Comment by rubenssoto** [comment]
I don't know, may be related to the problem that I showed you on data docs.

**Comment by eugmandel** [comment]
Acknowledging this as a bug - the core team will provide a fix.
