### ISSUE TITLE
expect_compound_columns_to_be_unique divide by zero error when no rows

### ISSUE THREAD

**Issue by jdimatteo** [fivetran/great_expectations#2451]
**Describe the bug**
[expect_compound_columns_to_be_unique](https://docs.greatexpectations.io/en/0.13.8/autoapi/great_expectations/expectations/core/expect_compound_columns_to_be_unique/index.html) errors with a divide by zero error when the table contains no rows as shown in this example stack trace from version 0.12.7:

```
float division by zero
Traceback (most recent call last):
    ...
  File "py_deps/pypi__great_expectations/great_expectations/data_asset/util.py", line 80, in f
    return self.mthd(obj, *args, **kwargs)
  File "py_deps/pypi__great_expectations/great_expectations/data_asset/data_asset.py", line 275, in wrapper
    raise err
  File "py_deps/pypi__great_expectations/great_expectations/data_asset/data_asset.py", line 260, in wrapper
    return_obj = func(self, **evaluation_args)
  File "py_deps/pypi__great_expectations/great_expectations/dataset/sqlalchemy_dataset.py", line 1380, in expect_compound_columns_to_be_unique
    "result": {"unexpected_percent": 100.0 * unexpected_count / total_count}
ZeroDivisionError: 
```

**To Reproduce**
1. Use expect_compound_columns_to_be_unique on a table with zero rows

**Expected behavior**
Expectation should pass.

**Environment (please complete the following information):**
 - Operating System: [e.g. Linux, MacOS, Windows]
 - Great Expectations Version: reproduced on 0.12.7 and 0.13.9

**Additional context**

**Comment by jdimatteo** [comment]
I'm fixing this with https://github.com/great-expectations/great_expectations/pull/2454

**Comment by eugmandel** [comment]
Thank you for filing this, @jdimatteo ! Even better, thank you for creating a PR to address this issue - I'll review it a bit later today.
