### ISSUE TITLE
It is not possible to use RuntimeDataConnector with batch_data and partition_request parameters

### ISSUE THREAD

**Issue by sorendaugaard** [fivetran/great_expectations#2524]
**Describe the bug**
When trying to load a Pandas dataframe as a batch following this [guide](https://docs.greatexpectations.io/en/latest/guides/how_to_guides/creating_batches/how_to_load_a_pandas_dataframe_as_a_batch.html) from the documentation I run into the following exception when initializing the validator:
```
Traceback (most recent call last):
  File "ge_test.py", line 58, in <module>
    my_validator = context.get_validator(
  File "/Users/soren.daugaard/Code/data-pipelines/.direnv/python-3.8.6/lib/python3.8/site-packages/great_expectations/data_context/data_context.py", line 1602, in get_validator
    self.get_batch(
  File "/Users/soren.daugaard/Code/data-pipelines/.direnv/python-3.8.6/lib/python3.8/site-packages/great_expectations/data_context/data_context.py", line 1402, in get_batch
    return self._get_batch_v3(
  File "/Users/soren.daugaard/Code/data-pipelines/.direnv/python-3.8.6/lib/python3.8/site-packages/great_expectations/data_context/data_context.py", line 1204, in _get_batch_v3
    batch_list: List[Batch] = self.get_batch_list(
  File "/Users/soren.daugaard/Code/data-pipelines/.direnv/python-3.8.6/lib/python3.8/site-packages/great_expectations/data_context/data_context.py", line 1499, in get_batch_list
    return datasource.get_batch_list_from_batch_request(
  File "/Users/soren.daugaard/Code/data-pipelines/.direnv/python-3.8.6/lib/python3.8/site-packages/great_expectations/datasource/new_datasource.py", line 117, in get_batch_list_from_batch_request
    ] = data_connector.get_batch_definition_list_from_batch_request(
  File "/Users/soren.daugaard/Code/data-pipelines/.direnv/python-3.8.6/lib/python3.8/site-packages/great_expectations/datasource/data_connector/runtime_data_connector.py", line 146, in get_batch_definition_list_from_batch_request
    return self._get_batch_definition_list_from_batch_request(
  File "/Users/soren.daugaard/Code/data-pipelines/.direnv/python-3.8.6/lib/python3.8/site-packages/great_expectations/datasource/data_connector/runtime_data_connector.py", line 154, in _get_batch_definition_list_from_batch_request
    self._validate_batch_request(batch_request=batch_request)
  File "/Users/soren.daugaard/Code/data-pipelines/.direnv/python-3.8.6/lib/python3.8/site-packages/great_expectations/datasource/data_connector/runtime_data_connector.py", line 271, in _validate_batch_request
    raise ge_exceptions.DataConnectorError(
great_expectations.exceptions.exceptions.DataConnectorError: RuntimeDataConnector "in_memory_data_connector" requires batch_data and partition_request to be both present or
                both absent in the batch_request parameter.
```

**To Reproduce**
The following script reproduces the problem:
```
import great_expectations as ge
from great_expectations.core.batch import BatchRequest

import pandas as pd

# Load dataframe
dataframe = pd.read_csv("20210130-accounts.csv")
# Make sure its loaded and the correct type
print(type(dataframe))

context = ge.get_context()

ds = context.get_datasource('in_memory_pandas')

suite = context.get_expectation_suite("frontend.accounts")

# Initialize batch request
batch_request = BatchRequest(
    datasource_name="in_memory_pandas",
    data_connector_name="in_memory_data_connector",
    batch_data=dataframe,
    data_asset_name="IN_MEMORY_DATA_ASSET",
    partition_request={
        "batch_identifiers": {
            "run_id": "run 18"
        }
    }
)

# Print out batch data & partition request for manual inspection
print(type(batch_request.batch_data))
print(batch_request.partition_request)


# Ensure that batch_data and batch_request satisfy the "if and only if" condition that seems to fail in GE
if not (
        (
                batch_request.batch_data is None
                and (
                        batch_request.partition_request is None
                        or not
batch_request.partition_request.get("batch_identifiers")
                )
        )
        or (
                batch_request.batch_data is not None
                and batch_request.partition_request
                and batch_request.partition_request.get("batch_identifiers")
        )
):
    print(
        f"""RuntimeDataConnector requires batch_data and
partition_request to be both present or  both absent in the batch_request parameter.
        """
    )
else:
    print("All good!")

# This is where it throws an exception 
my_validator = context.get_validator(
    batch_request=batch_request,
    expectation_suite=suite
)
```
The script produces the following output:
```
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
{'batch_identifiers': {'run_id': 'run 18'}}
All good!
Traceback (most recent call last):
  File "ge_test.py", line 58, in <module>
    my_validator = context.get_validator(
  File "/Users/soren.daugaard/Code/data-pipelines/.direnv/python-3.8.6/lib/python3.8/site-packages/great_expectations/data_context/data_context.py", line 1602, in get_validator
    self.get_batch(
  File "/Users/soren.daugaard/Code/data-pipelines/.direnv/python-3.8.6/lib/python3.8/site-packages/great_expectations/data_context/data_context.py", line 1402, in get_batch
    return self._get_batch_v3(
  File "/Users/soren.daugaard/Code/data-pipelines/.direnv/python-3.8.6/lib/python3.8/site-packages/great_expectations/data_context/data_context.py", line 1204, in _get_batch_v3
    batch_list: List[Batch] = self.get_batch_list(
  File "/Users/soren.daugaard/Code/data-pipelines/.direnv/python-3.8.6/lib/python3.8/site-packages/great_expectations/data_context/data_context.py", line 1499, in get_batch_list
    return datasource.get_batch_list_from_batch_request(
  File "/Users/soren.daugaard/Code/data-pipelines/.direnv/python-3.8.6/lib/python3.8/site-packages/great_expectations/datasource/new_datasource.py", line 117, in get_batch_list_from_batch_request
    ] = data_connector.get_batch_definition_list_from_batch_request(
  File "/Users/soren.daugaard/Code/data-pipelines/.direnv/python-3.8.6/lib/python3.8/site-packages/great_expectations/datasource/data_connector/runtime_data_connector.py", line 146, in get_batch_definition_list_from_batch_request
    return self._get_batch_definition_list_from_batch_request(
  File "/Users/soren.daugaard/Code/data-pipelines/.direnv/python-3.8.6/lib/python3.8/site-packages/great_expectations/datasource/data_connector/runtime_data_connector.py", line 154, in _get_batch_definition_list_from_batch_request
    self._validate_batch_request(batch_request=batch_request)
  File "/Users/soren.daugaard/Code/data-pipelines/.direnv/python-3.8.6/lib/python3.8/site-packages/great_expectations/datasource/data_connector/runtime_data_connector.py", line 271, in _validate_batch_request
    raise ge_exceptions.DataConnectorError(
great_expectations.exceptions.exceptions.DataConnectorError: RuntimeDataConnector "in_memory_data_connector" requires batch_data and partition_request to be both present or
                both absent in the batch_request parameter.
```

The datasource is defined the `great_expectations.yml` file as:
```
datasources:
  in_memory_pandas:
    class_name: Datasource
    execution_engine:
      class_name: PandasExecutionEngine
    data_connectors:
      in_memory_data_connector:
        module_name: great_expectations.datasource.data_connector
        class_name: RuntimeDataConnector
        runtime_keys:
          - run_id
```

**Expected behavior**
I expected the validator to be initialized and assigned to `my_validator`. 

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: 0.13.12

**Additional context**

**Comment by eugmandel** [comment]
@sorendaugaard We are iterating on the interface and the pattern of usage of RuntimeDataConnector - an improvement is coming shortly.
