### ISSUE TITLE
data_context_id must be valid UUID

### ISSUE THREAD

**Issue by Hanish-FD** [fivetran/great_expectations#2534]
**Describe the bug**
Recently, over the weekend an implementation of great_expectations on an Airflow dag started to return this new error: 'data_context_id must be valid UUID.' I had recently shifted from using a yaml configuration file to using a BaseDataContext and a python configuration file in order to build a context. It is when building the context that the error is thrown in my devstack environment. I have tried to explicitly provide a valid UUID as it's data_context_id, I've set up various print statements to see if data_context_id was being changed, nothing. I also checked these data_context_ids to make sure they were UUID compliant. 

**To Reproduce**
1. Create airflow DAG using branch python operator to validate task. Import a GE config file that populates the credentials for a database connection. This configuration method worked last week and ran without a hitch, so I'm not sure that is where the issue is. I could be wrong though, so I've provided a full tree of what my local environment consists of (see Tree, below).

2. On my local machine, using a console, I'm able to go through these steps, swimmingly, without err, it's only when running on airflow that the error for UUID manifests itself. I've provided the code that I run both to populate the config file as well as what is run with the airflow operator.

Here is the error log:

```
[2021-03-11 17:26:59,094] {taskinstance.py:1150} ERROR - data_context_id must be a valid uuid
Traceback (most recent call last):
  File "/opt/airflow/venv/lib/python3.6/site-packages/great_expectations/data_context/types/base.py", line 693, in data_context_id
    uuid.UUID(data_context_id)
  File "/usr/lib/python3.6/uuid.py", line 140, in __init__
    raise ValueError('badly formed hexadecimal UUID string')
ValueError: badly formed hexadecimal UUID string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/airflow/venv/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/venv/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 141, in execute
    branch = super(BranchPythonOperator, self).execute(context)
  File "/opt/airflow/venv/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/opt/airflow/venv/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ge_validation/great_expectations_validation.py", line 73, in validate_task
    context = BaseDataContext(project_config=config, context_root_dir=data_context_root)
  File "/opt/airflow/venv/lib/python3.6/site-packages/great_expectations/core/usage_statistics/usage_statistics.py", line 261, in usage_statistics_wrapped_method
    result = func(*args, **kwargs)
  File "/opt/airflow/venv/lib/python3.6/site-packages/great_expectations/data_context/data_context.py", line 288, in __init__
    self._data_context_id
  File "/opt/airflow/venv/lib/python3.6/site-packages/great_expectations/data_context/types/base.py", line 696, in data_context_id
    "data_context_id must be a valid uuid"
great_expectations.exceptions.exceptions.InvalidConfigError: data_context_id must be a valid uuid
[2021-03-11 17:26:59,147] {taskinstance.py:1194} INFO - Marking task as UP_FOR_RETRY. dag_id=great_expectations_validation, task_id=ge_validation, execution_date=20210310T030000, start_date=20210311T172655, end_date=20210311T172659
[2021-03-11 17:26:59,730] {local_task_job.py:102} INFO - Task exited with return code 1
```
 
Below I have marked where the error is occurring.

**Expected behavior**
Expected behaviour is to have a clean context built and run, here is a log from a successful run:

```
[2021-03-10 14:36:41,803] {data_asset.py:636} INFO - 	6 expectation(s) included in expectation_suite.
[2021-03-10 14:55:13,429] {python_operator.py:114} INFO - Done. Returned value was: ge_validation_success
[2021-03-10 14:55:13,444] {skipmixin.py:78} INFO - Following branch ge_validation_success
[2021-03-10 14:55:13,473] {skipmixin.py:101} INFO - Skipping tasks ['ge_validation_failed']
[2021-03-10 14:55:13,558] {taskinstance.py:1070} INFO - Marking task as SUCCESS.dag_id=great_expectations_validation, task_id=ge_validation, execution_date=20210310T142508, start_date=20210310T143638, end_date=20210310T145513
[2021-03-10 14:55:16,917] {local_task_job.py:102} INFO - Task exited with return code 0
```

**Environment (please complete the following information):**
 - Operating System: Linux
 - Great Expectations Version: 0.13.11

**Additional context**
DAG Excerpt:
```
def validate_task(ds, **kwargs):
    data_context_root = "/opt/airflow/dags/ge_validation"

    config = DataContextConfig(
        config_version=2,
        plugins_directory=None,
        config_variables_file_path=None,
        datasources=ge_config.data_sources,
        stores=ge_config.stores,
        expectations_store_name=ge_config.expectations_store_name,
        validations_store_name=ge_config.validations_store_name,
        evaluation_parameter_store_name=ge_config.evaluation_parameter_store_name,
        data_docs_sites=ge_config.data_docs,
        validation_operators=ge_config.validation_operators,
    )

    context = BaseDataContext(project_config=config, context_root_dir=data_context_root)

    suite = context.get_expectation_suite("etl_log.expectations")

    batch_kwargs = {
        "data_asset_name": "main_table",
        "schema": "dev",
        "table": "main_table",
        "datasource": "postgres_development",
    }

    batch = context.get_batch(batch_kwargs, suite)
    results = context.run_validation_operator(
        "action_list_operator", assets_to_validate=[batch], run_id="airflow_validation_run"
    )

    if not results["success"]:
        return "ge_validation_failed"
    return "ge_validation_success"

...

my_ge_task = BranchPythonOperator(
    task_id="ge_validation", python_callable=validate_task, provide_context=True, dag=main_dag
)
```

Configuration File: 
```
from airflow.hooks.postgres_hook import PostgresHook
from psycopg2.extensions import ConnectionInfo

redshift = PostgresHook(postgres_conn_id="dw_redshift")
redshift_conn = redshift.get_conn()


data_sources = {
    "pandas_development": {
        "data_asset_type": {
            "class_name": "PandasDataset",
            "module_name": "great_expectations.dataset",
        },
        "batch_kwargs_generator": {
            "subdir_reader": {
                "class_name": "SubdirReaderBatchKwargsGenerator",
                "base_directory": "../ge_validation",
            }
        },
        "class_name": "PandasDatasource",
        "module_name": "great_expectations.datasource",
    },
    "postgres_development": {
        "data_asset_type": {
            "class_name": "SqlAlchemyDataset",
            "module_name": "great_expectations.dataset",
        },
        "credentials": {
            "drivername": "postgres",
            "host": ConnectionInfo(redshift_conn).host,
            "port": ConnectionInfo(redshift_conn).port,
            "username": ConnectionInfo(redshift_conn).user,
            "password": ConnectionInfo(redshift_conn).password,
            "database": ConnectionInfo(redshift_conn).dbname,
        },
        "module_name": "great_expectations.datasource",
        "class_name": "SqlAlchemyDatasource",
    },
}
stores = {
    "expectations_store": {
        "class_name": "ExpectationsStore",
        "store_backend": {
            "class_name": "TupleFilesystemStoreBackend",
            "base_directory": "expectations/",
        },
    },
    "validations_store": {
        "class_name": "ValidationsStore",
        "store_backend": {
            "class_name": "TupleS3StoreBackend",
            "bucket": "great-expectations",
            "prefix": "validations/",
        },
    },
    "evaluation_parameter_store": {"class_name": "EvaluationParameterStore"},
}

expectations_store_name = "expectations_store"
validations_store_name = "validations_store"
evaluation_parameter_store_name = "evaluation_parameter_store"

validation_operators = {
    "action_list_operator": {
        "class_name": "ActionListValidationOperator",
        "action_list": [
            {
                "name": "store_validation_result",
                "action": {"class_name": "StoreValidationResultAction"},
            },
            {
                "name": "store_evaluation_params",
                "action": {"class_name": "StoreEvaluationParametersAction"},
            },
            {"name": "update_data_docs", "action": {"class_name": "UpdateDataDocsAction"}},
        ],
    }
}
data_docs = {
    "local_site": {
        "class_name": "SiteBuilder",
        "show_how_to_buttons": True,
        "store_backend": {
            "class_name": "TupleS3StoreBackend",
            "bucket": "great-expectations",
            "prefix": "data_docs/",
        },
        "site_index_builder": {"class_name": "DefaultSiteIndexBuilder"},
    },
    "s3_site": {
        "class_name": "SiteBuilder",
        "store_backend": {
            "class_name": "TupleS3StoreBackend",
            "bucket": "great-expectations",
            "prefix": "data_docs/",
        },
        "site_index_builder": {"class_name": "DefaultSiteIndexBuilder", "show_cta_footer": True},
    },
}

```
Tree: 
```
.
├── __pycache__
│   └── ge_config.cpython-36.pyc
├── expectations
│   ├── table_1
│   │   └── expectations.json
│   ├── table_2
│   │   └── expectations.json
│   ├── table_3
│   │   └── expectations.json
│   ├── table_4
│   │   └── expectations.json
│   └── main_table
│       └── expectations.json
├── ge_config.py
├── ge_validation.yml
├── great_expectations_validation.py
├── plugins
│   └── custom_data_docs
│       ├── renderers
│       ├── styles
│       │   └── data_docs_custom_styles.css
│       └── views
└── uncommitted
    ├── config_variables.yml
    ├── data_docs
    │   └── local_site
    │       ├── expectations
    │       │   ├── table_1
    │       │   │   └── expectations.html
    │       │   ├── table_2
    │       │   │   └── expectations.html
    │       │   ├── table_3
    │       │   │   └── expectations.html
    │       │   ├── table_4
    │       │   │   └── expectations.html
    │       │   └── main_table
    │       │       └── expectations.html
    │       ├── index.html
    │       ├── static
    │       │   ├── fonts
    │       │   │   └── HKGrotesk
    │       │   │       ├── HKGrotesk-Bold.otf
    │       │   │       ├── HKGrotesk-BoldItalic.otf
    │       │   │       ├── HKGrotesk-Italic.otf
    │       │   │       ├── HKGrotesk-Light.otf
    │       │   │       ├── HKGrotesk-LightItalic.otf
    │       │   │       ├── HKGrotesk-Medium.otf
    │       │   │       ├── HKGrotesk-MediumItalic.otf
    │       │   │       ├── HKGrotesk-Regular.otf
    │       │   │       ├── HKGrotesk-SemiBold.otf
    │       │   │       └── HKGrotesk-SemiBoldItalic.otf
    │       │   ├── images
    │       │   │   ├── favicon.ico
    │       │   │   ├── glossary_scroller.gif
    │       │   │   ├── iterative-dev-loop.png
    │       │   │   ├── logo-long-vector.svg
    │       │   │   ├── logo-long.png
    │       │   │   ├── short-logo-vector.svg
    │       │   │   ├── short-logo.png
    │       │   │   └── validation_failed_unexpected_values.gif
    │       │   └── styles
    │       │       ├── data_docs_custom_styles_template.css
    │       │       └── data_docs_default_styles.css
    │       └── validations
    │           └── ...        
    │             
    ├── edit_table_1.expectations.ipynb
    ├── edit_table_2.expectations.ipynb
    ├── edit_table_4.expectations.ipynb
    ├── edit_main_table.expectations.ipynb
    ├── edit_fdg.dim_fdg_main_table.warning.ipynb
    ├── scaffold_table_1.expectations.ipynb
    ├── scaffold_table_1.warnin.ipynb
    ├── scaffold_table_2.expectations.ipynb
    ├── scaffold_table_3.expectations.ipynb
    ├── scaffold_table_4.expectations.ipynb
    ├── scaffold_main_table.expectations.ipynb
    └── validations
        └── ...   

```

**Comment by eugmandel** [comment]
@moolhans Thank you for reporting this issue - adding to the core team's queue to investigate and fix.

**Comment by moritzkoerber** [comment]
Did you have a look into this? I still run into this issue. Here's my code:
```
config_dict = {
    "stores": {
        "expectations_s3_store": {
            "class_name": "ExpectationsStore",
            "store_backend": {
                "class_name": "TupleS3StoreBackend",
                "bucket": f"{s3_bucket}",
                "prefix": "expectations",
            },
        },
        "validations_s3_store": {
            "class_name": "ValidationsStore",
            "store_backend": {
                "class_name": "TupleS3StoreBackend",
                "bucket": f"{s3_bucket}",
                "prefix": "validations",
            },
        },
        "checkpoints_s3_store": {
            "class_name": "CheckpointStore",
            "store_backend": {
                "class_name": "TupleS3StoreBackend",
                "bucket": f"{s3_bucket}",
                "prefix": "checkpoints",
            },
        },
        "evaluation_parameter_store": {"class_name": "EvaluationParameterStore"},
    },
    "expectations_store_name": "expectations_s3_store",
    "validations_store_name": "validations_s3_store",
    "checkpoint_store_name": "checkpoints_s3_store",
    "evaluation_parameter_store_name": "evaluation_parameter_store",
    "anonymous_usage_statistics": {
        "enabled": False,
        "data_context_id": "ee03c210-16c2-4692-ba66-cb114f2bf6f9",
    },
}

from great_expectations.data_context import BaseDataContext
from great_expectations.data_context.types.base import DataContextConfig

data_context_config = DataContextConfig(**config_dict)
context = BaseDataContext(project_config=data_context_config)
```
Returns:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/.pyenv/versions/3.8.2/lib/python3.8/site-packages/great_expectations/data_context/types/base.py in data_context_id(self, data_context_id)
    917         try:
--> 918             uuid.UUID(data_context_id)
    919         except ValueError:

~/.pyenv/versions/3.8.2/lib/python3.8/uuid.py in __init__(self, hex, bytes, bytes_le, fields, int, version, is_safe)
    168             if len(hex) != 32:
--> 169                 raise ValueError('badly formed hexadecimal UUID string')
    170             int = int_(hex, 16)

ValueError: badly formed hexadecimal UUID string

During handling of the above exception, another exception occurred:

InvalidConfigError                        Traceback (most recent call last)
/var/folders/z8/hcytzhfx41n8lzl81sbv0jmh0000gn/T/ipykernel_14211/3918381886.py in <module>
----> 1 context = BaseDataContext(project_config=data_context_config)

~/.pyenv/versions/3.8.2/lib/python3.8/site-packages/great_expectations/core/usage_statistics/usage_statistics.py in usage_statistics_wrapped_method(*args, **kwargs)
    305                     nested_update(event_payload, args_payload_fn(*args, **kwargs))
    306 
--> 307                 result = func(*args, **kwargs)
    308                 message["success"] = True
    309             except Exception:

~/.pyenv/versions/3.8.2/lib/python3.8/site-packages/great_expectations/data_context/data_context.py in __init__(self, project_config, context_root_dir, runtime_environment, ge_cloud_mode, ge_cloud_config)
    358 
    359         # Override the project_config data_context_id if an expectations_store was already set up
--> 360         self._project_config.anonymous_usage_statistics.data_context_id = (
    361             self._data_context_id
    362         )

~/.pyenv/versions/3.8.2/lib/python3.8/site-packages/great_expectations/data_context/types/base.py in data_context_id(self, data_context_id)
    918             uuid.UUID(data_context_id)
    919         except ValueError:
--> 920             raise ge_exceptions.InvalidConfigError(
    921                 "data_context_id must be a valid uuid"
    922             )

InvalidConfigError: data_context_id must be a valid uuid
```

Edit: For anyone running into the same error: The issue was that the uuid stored in `.ge_store_backend_id` in the expectations s3 store was invalid.
