### ISSUE TITLE
Can't run validation with context.run_validation_operator

### ISSUE THREAD

**Issue by Danissss** [fivetran/great_expectations#2597]
**Describe the bug**

Error in a.
```
You appear to be using a legacy capability with the latest config version (3.0).
    Your data context with this configuration version uses validation_operators, which are being deprecated.  Please update your configuration to be compatible with the version number 3.

Traceback (most recent call last):
  File "scripts/great_expectation_test.py", line 34, in <module>
    main()
  File "scripts/great_expectation_test.py", line 28, in main
    context.run_validation_operator('action_list_operator', assets_to_validate=batch, run_name="test_validation")
  File "/Users/xuan.cao/opt/anaconda3/envs/snowflake-data-profiling/lib/python3.8/site-packages/great_expectations/core/usage_statistics/usage_statistics.py", line 262, in usage_statistics_wrapped_method
    result = func(*args, **kwargs)
  File "/Users/xuan.cao/opt/anaconda3/envs/snowflake-data-profiling/lib/python3.8/site-packages/great_expectations/data_context/data_context.py", line 1266, in run_validation_operator
    for batch in assets_to_validate:
TypeError: 'SqlAlchemyDataset' object is not iterable
```

Error in b.
```
great_expectations.exceptions.exceptions.InvalidDataContextConfigError: Error while processing DataContextConfig: perform_action_list_operator
```

**To Reproduce**
a. here is my yaml file
```yml
validation_operators:
  action_list_operator:
    class_name: ActionListValidationOperator
    action_list:
      - name: store_validation_result
        action:
          class_name: StoreValidationResultAction
          target_store_name: validations_store
```
I am using following to do the validation
```
context.run_validation_operator('action_list_operator', assets_to_validate=batch, run_name="test_validation")
```
b. here is my changed yaml file
```yml
perform_action_list_operator:  # this is the name you will use when you invoke the operator
  class_name: ActionListValidationOperator
  action_list:
    - name: store_validation_result
      action:
        class_name: StoreValidationResultAction
        target_store_name: validations_store
```
I am using following to do the validation
```
context.run_validation_operator('perform_action_list_operator', assets_to_validate=batch, run_name="test_validation")
```

**Expected behavior**

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: 0.13.14  pyha770c72_0  conda-forge
 - Python Version: 3.8.8

**Comment by eugmandel** [comment]
@Danissss Thank you for reporting this. We will triage and respond.

**Comment by AlexNae** [comment]
I have the same problem, I think it is still relevant. Can someone please reopen this issue? Or should I create an identical one?
