### ISSUE TITLE
Invalid object name 'tempdb.pdw.columns' creating expectations with Azure Synapse

### ISSUE THREAD

**Issue by dcoueron** [fivetran/great_expectations#2623]
**Describe the bug**
I'm trying to make great_expectations work with Azure Synapse (formerly Azure SQL Datawarehouse) and it produces an error any time I try to scaffold default expectations or to create new ones in a notebook.

I did some research and it is apparently a known limitation of Synapse that you can't query system views on tempdb like tempdb.sys.columns. 

**To Reproduce**
After creating a new suite with the CLI : `great_expectations suite new`, just tried to run the first notebook cell and got the error below.

**Environment (please complete the following information):**
 - Operating System: Linux
 - Great Expectations Version: 0.13.15

**Additional context**
Detailed error report from Jupyter :

```
2021-03-30T12:12:20+0200 - INFO - Great Expectations logging enabled at 20 level by JupyterUX module.
2021-03-30T12:12:22+0200 - INFO - Generating query from table batch_kwargs based on limit and offset
---------------------------------------------------------------------------
ProgrammingError                          Traceback (most recent call last)
~/test_ge/.venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py in _execute_context(self, dialect, constructor, statement, parameters, *args)
   1276                     self.dialect.do_execute(
-> 1277                         cursor, statement, parameters, context
   1278                     )

~/test_ge/.venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py in do_execute(self, cursor, statement, parameters, context)
    607     def do_execute(self, cursor, statement, parameters, context=None):
--> 608         cursor.execute(statement, parameters)
    609 

ProgrammingError: ('42S02', "[42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'tempdb.pdw.columns'. (208) (SQLExecDirectW)")

The above exception was the direct cause of the following exception:

ProgrammingError                          Traceback (most recent call last)
<ipython-input-1-13e9a4dc9d03> in <module>
     14 
     15 batch_kwargs = {'data_asset_name': 'XXXX.XXXX', 'datasource': 'sqldw', 'limit': 1000, 'schema': 'XXXX', 'table': 'XXXX'}
---> 16 batch = context.get_batch(batch_kwargs, suite)
     17 batch.head()

~/test_ge/.venv/lib/python3.6/site-packages/great_expectations/data_context/data_context.py in get_batch(self, arg1, arg2, arg3, **kwargs)
   1423             expectation_suite_name=expectation_suite_name,
   1424             data_asset_type=data_asset_type,
-> 1425             batch_parameters=batch_parameters,
   1426         )
   1427 

~/test_ge/.venv/lib/python3.6/site-packages/great_expectations/data_context/data_context.py in _get_batch_v2(self, batch_kwargs, expectation_suite_name, data_asset_type, batch_parameters)
   1145             expectation_engine=data_asset_type,
   1146         )
-> 1147         return validator.get_dataset()
   1148 
   1149     def _get_batch_v3(

~/test_ge/.venv/lib/python3.6/site-packages/great_expectations/validator/validator.py in get_dataset(self)
   1436                 expectation_suite=self.expectation_suite,
   1437                 **init_kwargs,
-> 1438                 **self.batch.batch_kwargs.get("dataset_options", {}),
   1439             )
   1440 

~/test_ge/.venv/lib/python3.6/site-packages/great_expectations/dataset/sqlalchemy_dataset.py in __init__(self, table_name, engine, connection_string, custom_sql, schema, *args, **kwargs)
    596         # Use fallback because for mssql reflection doesn't throw an error but returns an empty list
    597         if len(self.columns) == 0:
--> 598             self.columns = self.column_reflection_fallback()
    599 
    600         # Only call super once connection is established and table_name and columns known to allow autoinspection

~/test_ge/.venv/lib/python3.6/site-packages/great_expectations/dataset/sqlalchemy_dataset.py in column_reflection_fallback(self)
   1322                 """
   1323             )
-> 1324             col_info_tuples_list = self.engine.execute(col_info_query).fetchall()
   1325             col_info_dict_list = [
   1326                 {"name": col_name, "type": getattr(type_module, col_type.upper())()}

~/test_ge/.venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py in execute(self, object_, *multiparams, **params)
   1009             )
   1010         else:
-> 1011             return meth(self, multiparams, params)
   1012 
   1013     def _execute_function(self, func, multiparams, params):

~/test_ge/.venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py in _execute_on_connection(self, connection, multiparams, params)
    296     def _execute_on_connection(self, connection, multiparams, params):
    297         if self.supports_execution:
--> 298             return connection._execute_clauseelement(self, multiparams, params)
    299         else:
    300             raise exc.ObjectNotExecutableError(self)

~/test_ge/.venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py in _execute_clauseelement(self, elem, multiparams, params)
   1128             distilled_params,
   1129             compiled_sql,
-> 1130             distilled_params,
   1131         )
   1132         if self._has_events or self.engine._has_events:

~/test_ge/.venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py in _execute_context(self, dialect, constructor, statement, parameters, *args)
   1315         except BaseException as e:
   1316             self._handle_dbapi_exception(
-> 1317                 e, statement, parameters, cursor, context
   1318             )
   1319 

~/test_ge/.venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py in _handle_dbapi_exception(self, e, statement, parameters, cursor, context)
   1509             elif should_wrap:
   1510                 util.raise_(
-> 1511                     sqlalchemy_exception, with_traceback=exc_info[2], from_=e
   1512                 )
   1513             else:

~/test_ge/.venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py in raise_(***failed resolving arguments***)
    180 
    181         try:
--> 182             raise exception
    183         finally:
    184             # credit to

~/test_ge/.venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py in _execute_context(self, dialect, constructor, statement, parameters, *args)
   1275                 if not evt_handled:
   1276                     self.dialect.do_execute(
-> 1277                         cursor, statement, parameters, context
   1278                     )
   1279 

~/test_ge/.venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py in do_execute(self, cursor, statement, parameters, context)
    606 
    607     def do_execute(self, cursor, statement, parameters, context=None):
--> 608         cursor.execute(statement, parameters)
    609 
    610     def do_execute_no_params(self, cursor, statement, context=None):

ProgrammingError: (pyodbc.ProgrammingError) ('42S02', "[42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'tempdb.pdw.columns'. (208) (SQLExecDirectW)")
[SQL: 
SELECT
    cols.NAME, ty.NAME
FROM
    tempdb.sys.columns AS cols
JOIN
    sys.types AS ty
ON
    cols.user_type_id = ty.user_type_id
WHERE
    object_id = OBJECT_ID('tempdb..#ge_tmp_0dcc3540')
                ]
(Background on this error at: http://sqlalche.me/e/13/f405)
```

**Comment by hmandsager** [comment]
I came across the same issue when building some suites for our data warehouse. This bug occurred from me when I tried to use the CLI or a sub-query but I was able to successfully profile tables when I included the entire table. I ended up profiling against our daily staging tables as they mimic the fact table structure but with a manageable subset of data. If that's not an option you can CTAS a subset of data and profile that. I also had some trouble with profiling `BIGINT` columns so I created an `included_columns` list that excluded them from the profiling. Here's the workaround I used just in case that would be helpful for you.

```python
context = ge.data_context.DataContext()

expectation_suite_name = "expectation-suite-name"
suite = context.create_expectation_suite(
    expectation_suite_name, overwrite_existing=True
)

batch_kwargs = {
    "table": "table-name",
    "schema": "schema-name",
    "data_asset_name": "data-asset-name",
    "datasource": "datasource",
}
batch = context.get_batch(batch_kwargs, suite)
context.save_expectation_suite(suite, expectation_suite_name)
batch.head()

scaffold_config = {
    "included_columns": included_columns,
    #"excluded_columns": excluded_columns,
    # "included_expectations": [], 
    # "excluded_expectations": [],
}
suite, evr = BasicSuiteBuilderProfiler().profile(batch, profiler_configuration=scaffold_config)
batch.save_expectation_suite(discard_failed_expectations=False)
```

**Comment by dcoueron** [comment]
Hi @hmandsager ,

Thanks for the reply. I tried your code and received an error on `context.get_batch` :
```python
Exception has occurred: ProgrammingError
(pyodbc.ProgrammingError) ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]'ident_seed' is not a recognized built-in function name. (104162) (SQLExecDirectW)")
[SQL: select ident_seed('MYSCHEMA.MYTABLE'), ident_incr('MYSCHEMA.MYTABLE')]
(Background on this error at: http://sqlalche.me/e/13/f405)
  File "/home/datalab/test_ge/great_expectations/test_expectation.py", line 14, in <module>
    batch = context.get_batch(batch_kwargs, suite)
```

Did you get something like that as well ? 
Were you using Azure Synapse SQL Pool ?

**Comment by hmandsager** [comment]
I'm running Azure Synapse SQL Pool but I have not seen that error. Is there more information in the stack trace? I couldn't find any references to `ident_seed` in GE.

**Comment by eugmandel** [comment]
@dcoueron We have not tested Great Expectations on Azure Synapse (Azure SQL Datawarehouse) yet. Database engines are not consistent in their approach to temp tables. PRs with adjustments to these special cases typically come from the community members that use that particular database engine. If you are interested in doing this for Synapse, it would be awesome. You can search for "athena" in the code base for examples of this kind of database engine specific handling. 

Also in the near future we will add an option to not create temporary tables.

**Comment by dcoueron** [comment]
Hi @hmandsager, sorry for the delay, I tried with another table and did not receive the ident_seed error but I did receive another error though :-/ I'll find some time later this week to post the full stack traces.

@eugmandel, I'm not sure I have the right skills to do this job but I'll give it a try ! Also, I'm not sure the problem is only with temp tables considering the ident_seed message I received.

**Comment by dcoueron** [comment]
> I'm running Azure Synapse SQL Pool but I have not seen that error. Is there more information in the stack trace? I couldn't find any references to `ident_seed` in GE.

Below is the full stack trace. I think it may be related to the types of data I have in my table because I tested it on a different table and managed to make it work (I had to remove the "included_columns" config that was not interpreted correctly though).

```
Traceback (most recent call last):
  File "/home/datalab/test_ge/.venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/datalab/test_ge/.venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
pyodbc.ProgrammingError: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]'ident_seed' is not a recognized built-in function name. (104162) (SQLExecDirectW)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/datalab/test_ge/great_expectations/edit_SCHEMA_NAME_TABLE_NAME.py", line 17, in <module>
    batch = context.get_batch(batch_kwargs, suite)
  File "/home/datalab/test_ge/.venv/lib/python3.6/site-packages/great_expectations/data_context/data_context.py", line 1425, in get_batch
    batch_parameters=batch_parameters,
  File "/home/datalab/test_ge/.venv/lib/python3.6/site-packages/great_expectations/data_context/data_context.py", line 1147, in _get_batch_v2
    return validator.get_dataset()
  File "/home/datalab/test_ge/.venv/lib/python3.6/site-packages/great_expectations/validator/validator.py", line 1438, in get_dataset
    **self.batch.batch_kwargs.get("dataset_options", {}),
  File "/home/datalab/test_ge/.venv/lib/python3.6/site-packages/great_expectations/dataset/sqlalchemy_dataset.py", line 590, in __init__
    self.columns = insp.get_columns(table_name, schema=schema)
  File "/home/datalab/test_ge/.venv/lib/python3.6/site-packages/sqlalchemy/engine/reflection.py", line 391, in get_columns
    self.bind, table_name, schema, info_cache=self.info_cache, **kw
  File "<string>", line 2, in get_columns
  File "/home/datalab/test_ge/.venv/lib/python3.6/site-packages/sqlalchemy/engine/reflection.py", line 52, in cache
    ret = fn(self, con, *args, **kw)
  File "/home/datalab/test_ge/.venv/lib/python3.6/site-packages/sqlalchemy/dialects/mssql/base.py", line 2215, in wrap
    **kw
  File "/home/datalab/test_ge/.venv/lib/python3.6/site-packages/sqlalchemy/dialects/mssql/base.py", line 2229, in _switch_db
    return fn(*arg, **kw)
  File "/home/datalab/test_ge/.venv/lib/python3.6/site-packages/sqlalchemy/dialects/mssql/base.py", line 2778, in get_columns
    % (table_fullname, table_fullname)
  File "/home/datalab/test_ge/.venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1003, in execute
    return self._execute_text(object_, multiparams, params)
  File "/home/datalab/test_ge/.venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1178, in _execute_text
    parameters,
  File "/home/datalab/test_ge/.venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/datalab/test_ge/.venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/datalab/test_ge/.venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/datalab/test_ge/.venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/datalab/test_ge/.venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]'ident_seed' is not a recognized built-in function name. (104162) (SQLExecDirectW)")
[SQL: select ident_seed('SCHEMA_NAME.TABLE_NAME'), ident_incr('SCHEMA_NAME.TABLE_NAME')]
(Background on this error at: http://sqlalche.me/e/13/f405)
```

**Comment by AFineDayFor** [comment]
Howdy @dcoueron,
We're going to close this because it appears to be an issue limited to v2; however, if it's in v3 please feel free to re-open this issue.
If it's something you'd like to address, we'd be glad to accept the contribution

**Comment by bayees** [comment]
This is still an issue since there are no tempdb to query against
