### ISSUE TITLE
Building docs is failing in latest version

### ISSUE THREAD

**Issue by Naveen-8451** [fivetran/great_expectations#2728]
**Describe the bug**
we are trying to build the data docs using context.build_data_docs(), but we are having weird issue seeing after few days before it was working as expected.

**Error**
ERROR:great_expectations.validation_operators.validation_operators:Error running action with name update_data_docs
Traceback (most recent call last):
  File "/databricks/python/lib/python3.7/site-packages/great_expectations/validation_operators/validation_operators.py", line 392, in _run_actions
    action_result = self.actions[action["name"]].run(
  File "/databricks/python/lib/python3.7/site-packages/great_expectations/checkpoint/actions.py", line 62, in run
    )
  File "/databricks/python/lib/python3.7/site-packages/great_expectations/checkpoint/actions.py", line 939, in _run
  File "/databricks/python/lib/python3.7/site-packages/great_expectations/core/usage_statistics/usage_statistics.py", line 262, in usage_statistics_wrapped_method
    # We try to get the handler only now, so that it *could* be initialized in func, e.g. if it is an
  File "/databricks/python/lib/python3.7/site-packages/great_expectations/data_context/data_context.py", line 2389, in build_data_docs
    # We don't need the datasource object, but this line serves to check if the datasource by the name passed as
  File "/databricks/python/lib/python3.7/site-packages/great_expectations/render/renderer/site_builder.py", line 293, in build
    site_section_builder.build(resource_identifiers=resource_identifiers)
  File "/databricks/python/lib/python3.7/site-packages/great_expectations/render/renderer/site_builder.py", line 388, in build
    source_store_keys = self.source_store.list_keys()
  File "/databricks/python/lib/python3.7/site-packages/great_expectations/data_context/store/store.py", line 142, in list_keys
    return [self.tuple_to_key(key) for key in keys_without_store_backend_id]
  File "/databricks/python/lib/python3.7/site-packages/great_expectations/data_context/store/store.py", line 142, in <listcomp>
    return [self.tuple_to_key(key) for key in keys_without_store_backend_id]
  File "/databricks/python/lib/python3.7/site-packages/great_expectations/data_context/store/store.py", line 110, in tuple_to_key
    return self._key_class.from_tuple(tuple_)
  File "/databricks/python/lib/python3.7/site-packages/great_expectations/data_context/types/resource_identifiers.py", line 164, in from_tuple
    RunIdentifier.from_tuple((tuple_[-3], tuple_[-2])),
IndexError: tuple index out of range

**Comment by eugmandel** [comment]
@Naveen0217 Could you please provide all the information that our bug template asks for? (https://github.com/great-expectations/great_expectations/issues/new?assignees=&labels=&template=bug_report.md&title=)

**Comment by BenGale93** [comment]
I came across this same issue I would recommend reading this piece of documentation, particularly "2a. Validations Store Backends" https://legacy.docs.greatexpectations.io/en/latest/guides/how_to_guides/migrating_versions.html

Basically there aren't enough folder levels in your stores.

**Comment by talagluck** [comment]
Closing, as I believe this was resolved by #3377 and proper configuration.
