### ISSUE TITLE
context.run_checkpoint() gets KeyError, can't find defined datasource

### ISSUE THREAD

**Issue by if-gh** [fivetran/great_expectations#2793]
**Describe the bug**
When using `context.run_checkpoint()`, it could not find the datasource I've defined and throws a `KeyError`

**To Reproduce**
1. Defined `SimpleSqlalchemyDatasource` in `great_expectations.yml`:
    ```yaml
    config_version: 3
    datasources:
      my_datasource:
        introspection:
          whole_table:
            data_asset_name_suffix: __whole_table
        class_name: SimpleSqlalchemyDatasource
        module_name: great_expectations.datasource
        data_asset_type:
          class_name: CustomSqlAlchemyDataset
          module_name: custom_module.custom_dataset
        credentials:
          host: localhost
          port: '5432'
          username: postgres
          password: ***
          database: postgres
          drivername: postgresql
    ```
2. Defined `Checkpoint` as:
    ```yaml
    name: my_checkpoint
    config_version: 1
    class_name: Checkpoint
    validations:
      - batch_request:
          datasource_name: my_datasource
          data_asset_name: my_data_asset
          data_connector_name: my_data_connector
          data_connector_query:
            index: 0
        expectation_suite_name: my_expectation_suite
    ```
3. Python script I ran:
    ```python
    import great_expectations as ge
    ...
    context = ge.get_context()
    result = context.run_checkpoint(checkpoint_name="my_checkpoint", batch_request=None, run_name=None)
    ...
    ```
```
Traceback (most recent call last):
  File "great_expectations/validations/validate.py", line 34, in <module>
    main()
  File "great_expectations/validations/validate.py", line 11, in main
    checkpoint_name="my_checkpoint", batch_request=None, run_name=None,
  File "/Users/yifangu/.pyenv/versions/ge/lib/python3.7/site-packages/great_expectations/data_context/data_context.py", line 3067, in run_checkpoint
    **kwargs,
  File "/Users/yifangu/.pyenv/versions/ge/lib/python3.7/site-packages/great_expectations/checkpoint/checkpoint.py", line 269, in run
    expectation_suite_name=expectation_suite_name,
  File "/Users/yifangu/.pyenv/versions/ge/lib/python3.7/site-packages/great_expectations/data_context/data_context.py", line 1700, in get_validator
    **kwargs,
  File "/Users/yifangu/.pyenv/versions/ge/lib/python3.7/site-packages/great_expectations/data_context/data_context.py", line 1421, in get_batch
    **kwargs,
  File "/Users/yifangu/.pyenv/versions/ge/lib/python3.7/site-packages/great_expectations/data_context/data_context.py", line 1235, in _get_batch_v3
    **kwargs,
  File "/Users/yifangu/.pyenv/versions/ge/lib/python3.7/site-packages/great_expectations/data_context/data_context.py", line 1517, in get_batch_list
    datasource: Datasource = cast(Datasource, self.datasources[datasource_name])
KeyError: 'my_datasource'
```

**Expected behavior**
`run_checkpoint()` should be able to locate the defined datasource that's referenced in checkpoint config.

**Environment (please complete the following information):**
 - Operating System: MacOS, Python 3.7.10
 - Great Expectations Version: `0.13.19`

**Additional context**
The `get_batch_list` in the stack trace is using `context.datasources` [here](https://github.com/great-expectations/great_expectations/blob/58631698d6bc2f62ac52af49d2e8402d3399000f/great_expectations/data_context/data_context.py#L1517) which is not properly initialized:
```python
>>> context = ge.get_context()
>>> print(context.datasources)
{}
```
where as `context.list_datasources()` shows the datasource correctly
```python
>>> print (context.list_datasources())
[{'data_asset_type': {'module_name': 'custom_module.custom_dataset', 'class_name': 'CustomSqlAlchemyDataset'}, 'class_name': 'SimpleSqlalchemyDatasource', 'credentials': {'host': 'localhost', 'port': '5432', 'username': 'postgres', 'password': '***', 'database': 'postgres', 'drivername': 'postgresql'}, 'module_name': 'great_expectations.datasource', 'introspection': {'whole_table': {'data_asset_name_suffix': '__whole_table'}}, 'name': 'my_datasource'}]
```

**Comment by eugmandel** [comment]
@YFGu0618 There is an issue in your datasource config - "data_asset_type" key exists only in V2 API and should not be provided in your configuration that otherwise looks like V3.
