### ISSUE TITLE
"great_expectations init" seems to think sqlalchemy is optional but fails when it is not present

### ISSUE THREAD

**Issue by mcallaway** [fivetran/great_expectations#2957]
**Describe the bug**

This happened the very first time I attempted to run "great_expectations init" with the intent on using PostgreSQL as a data source:

    great_expectations init
    ... things seem to be working well ...
    Great Expectations connected to your database!
    
    ================================================================================
    
    Would you like to profile new Expectations for a single data asset within your new Datasource? [Y/n]:
    Traceback (most recent call last):
      File "/Users/gmmqs/git/ge-pairwisedb/.venv/bin/great_expectations", line 8, in <module>
        sys.exit(main())
      File "/Users/gmmqs/git/ge-pairwisedb/.venv/lib/python3.9/site-packages/great_expectations/cli/cli.py", line 161, in main
        cli()
      File "/Users/gmmqs/git/ge-pairwisedb/.venv/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
        return self.main(*args, **kwargs)
      File "/Users/gmmqs/git/ge-pairwisedb/.venv/lib/python3.9/site-packages/click/core.py", line 1062, in main
        rv = self.invoke(ctx)
      File "/Users/gmmqs/git/ge-pairwisedb/.venv/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/Users/gmmqs/git/ge-pairwisedb/.venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/Users/gmmqs/git/ge-pairwisedb/.venv/lib/python3.9/site-packages/click/core.py", line 763, in invoke
        return __callback(*args, **kwargs)
      File "/Users/gmmqs/git/ge-pairwisedb/.venv/lib/python3.9/site-packages/great_expectations/cli/v012/init.py", line 151, in init
        ) = toolkit.create_expectation_suite(
      File "/Users/gmmqs/git/ge-pairwisedb/.venv/lib/python3.9/site-packages/great_expectations/cli/v012/toolkit.py", line 119, in create_expectation_suite
        ) = get_batch_kwargs(
      File "/Users/gmmqs/git/ge-pairwisedb/.venv/lib/python3.9/site-packages/great_expectations/cli/v012/datasource.py", line 1039, in get_batch_kwargs
        data_asset_name, batch_kwargs = _get_batch_kwargs_for_sqlalchemy_datasource(
      File "/Users/gmmqs/git/ge-pairwisedb/.venv/lib/python3.9/site-packages/great_expectations/cli/v012/datasource.py", line 1262, in _get_batch_kwargs_for_sqlalchemy_datasource
        default_schema = _get_default_schema(datasource)
      File "/Users/gmmqs/git/ge-pairwisedb/.venv/lib/python3.9/site-packages/great_expectations/cli/v012/datasource.py", line 1246, in _get_default_schema
        inspector = sqlalchemy.inspect(datasource.engine)
    AttributeError: 'NoneType' object has no attribute 'inspect'

**To Reproduce**

1. Run "great_expectations init" in a python virtualenv that does not currently have sqlalchemy installed.

**Expected behavior**

"great_expectations init" should run to completion without a python traceback.

**Environment (please complete the following information):**

- Mac OSX 10.15.7
- python 3.9.5
- great-expectations 0.13.20

**Additional context**

Consider the error message:

      File "/Users/gmmqs/git/ge-pairwisedb/.venv/lib/python3.9/site-packages/great_expectations/cli/v012/datasource.py", line 1246, in _get_default_schema
        inspector = sqlalchemy.inspect(datasource.engine)
    AttributeError: 'NoneType' object has no attribute 'inspect'

Then see these lines of code in datasource.py:

    1245 def _get_default_schema(datasource):
    1246     inspector = sqlalchemy.inspect(datasource.engine)
    1247     return inspector.default_schema_name

So `sqlalchemy` is None at this point. But see at the top of the file:

    45 try:
    46     import sqlalchemy
    47 except ImportError:
    48     logger.debug(
    49         "Unable to load SqlAlchemy context; install optional sqlalchemy dependency for support"
    50     )
    51     sqlalchemy = None

So this problem happened during a first run, which led to the `pip install sqlalchemy`. The code reads as if sqlalchemy is optional, but installs it anyway, but then fails later when it's not present from the first load. So the first run fails but runs after sqlalchemy is present succeed.

**Comment by talagluck** [comment]
Thanks for submitting, @mcallaway and apologies for delays! We will review internally and be in touch.

**Comment by talagluck** [comment]
Hi @mcallaway - thanks for raising this! This does indeed appear to be a bug, however, I believe it was resolved in V3. We aren't currently able to prioritize fixes for V2. That said, we always welcome community contributions, and I'm happy to offer guidance and support if you or another user are interested in submitting a fix.

**Comment by talagluck** [comment]
Linked to #4490
