### ISSUE TITLE
expectations_store of TupleS3StoreBackend causes error: Expecting property name enclosed in double quotes

### ISSUE THREAD

**Issue by scoyne2** [fivetran/great_expectations#3384]
**Describe the bug**
Starting Sept 9th 2021 I am seeing error when attempting to run an expectation_suite. I am on version 0.13.22 of great expectations, but see the same error on 0.13.33.

```
This error occurs in the jupyter notebook when creating a new expectation, and also when i run the checkpoint
ERROR - Error running action with name store_evaluation_params
ERROR - Expecting property name enclosed in double quotes: line 17 column 7 (char 452)
```

Our expectations were working without issue on September 8th and started failing with the above September 9th.
We are using S3 as the expectation store and redshift as our data source.

**To Reproduce**
1. Upload the following expectation to S3 s3://YOUR_S3_BUCKET/great_expectations/expectations/goodrx.test_table.json
```
{
  "data_asset_type": "Dataset",
  "expectation_suite_name": "goodrx.test_table",
  "expectations": [
    {
      "expectation_type": "expect_column_values_to_not_be_null",
      "kwargs": {
        "column": "person_id",
        "mostly": 0.97
      },
      "meta": {}
    }
  ],
  "meta": {
    "great_expectations_version": "0.13.22"
  }
}
```

2. Clone the great-expectations repo
3. From command line run `pip install great-expectations==0.13.22`
4. Run `great-expectations init` and select SQL -> Redshift and allow great expectations to install all of the psycog2 libraries
5. Run `pip install boto3==1.17.92`
6. Edit `great-expectations.yml` and use TupleS3StoreBackend for expectations_store
```
  expectations_store:
    class_name: ExpectationsStore
    store_backend:
      class_name: TupleS3StoreBackend
      bucket: YOUR_S3_BUCKET
      prefix: great_expectations/expectations/
```
7 Run `great_expectations suite edit goodrx.test_table`
8. See error:
```
2021-09-10T18:48:03-0700 - INFO - Setting run_name to: 20210911T014803.236045Z
2021-09-10T18:48:03-0700 - INFO - 	1 expectation(s) included in expectation_suite.
2021-09-10T18:48:06-0700 - ERROR - Error running action with name store_evaluation_params
Traceback (most recent call last):
  File "/Users/seancoyne/.pyenv/shims/versions/3.8.11/envs/great_expectations_public/lib/python3.8/site-packages/great_expectations/validation_operators/validation_operators.py", line 388, in _run_actions
    action_result = self.actions[action["name"]].run(
  File "/Users/seancoyne/.pyenv/shims/versions/3.8.11/envs/great_expectations_public/lib/python3.8/site-packages/great_expectations/checkpoint/actions.py", line 58, in run
    return self._run(
  File "/Users/seancoyne/.pyenv/shims/versions/3.8.11/envs/great_expectations_public/lib/python3.8/site-packages/great_expectations/checkpoint/actions.py", line 789, in _run
    self.data_context.store_evaluation_parameters(validation_result_suite)
  File "/Users/seancoyne/.pyenv/shims/versions/3.8.11/envs/great_expectations_public/lib/python3.8/site-packages/great_expectations/data_context/data_context.py", line 2406, in store_evaluation_parameters
    self._compile_evaluation_parameter_dependencies()
  File "/Users/seancoyne/.pyenv/shims/versions/3.8.11/envs/great_expectations_public/lib/python3.8/site-packages/great_expectations/data_context/data_context.py", line 2438, in _compile_evaluation_parameter_dependencies
    expectation_suite = self.expectations_store.get(key)
  File "/Users/seancoyne/.pyenv/shims/versions/3.8.11/envs/great_expectations_public/lib/python3.8/site-packages/great_expectations/data_context/store/store.py", line 153, in get
    return self.deserialize(key, value)
  File "/Users/seancoyne/.pyenv/shims/versions/3.8.11/envs/great_expectations_public/lib/python3.8/site-packages/great_expectations/data_context/store/expectations_store.py", line 181, in deserialize
    return self._expectationSuiteSchema.loads(value)
  File "/Users/seancoyne/.pyenv/shims/versions/3.8.11/envs/great_expectations_public/lib/python3.8/site-packages/great_expectations/marshmallow__shade/schema.py", line 768, in loads
    data = self.opts.render_module.loads(json_data, **kwargs)
  File "/Users/seancoyne/.pyenv/shims/versions/3.8.11/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Users/seancoyne/.pyenv/shims/versions/3.8.11/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/seancoyne/.pyenv/shims/versions/3.8.11/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 17 column 7 (char 452)
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
/var/folders/qb/_65zlxk52_v4_z6zrqk3hr0m0000gp/T/ipykernel_42283/4134278341.py in <module>
      1 batch.save_expectation_suite(discard_failed_expectations=False)
      2 
----> 3 results = LegacyCheckpoint(
      4     name="_temp_checkpoint",
      5     data_context=context,

~/.pyenv/shims/versions/3.8.11/envs/great_expectations_public/lib/python3.8/site-packages/great_expectations/checkpoint/checkpoint.py in run(self, run_id, evaluation_parameters, run_name, run_time, result_format, **kwargs)
    597                     f'running Checkpoint "{self.name}". Using default action_list_operator.'
    598                 )
--> 599             results = self._run_default_validation_operator(
    600                 assets_to_validate=batches_to_validate,
    601                 run_id=run_id,

~/.pyenv/shims/versions/3.8.11/envs/great_expectations_public/lib/python3.8/site-packages/great_expectations/checkpoint/checkpoint.py in _run_default_validation_operator(self, assets_to_validate, run_id, evaluation_parameters, run_name, run_time, result_format)
    547 
    548         if evaluation_parameters is None:
--> 549             return default_validation_operator.run(
    550                 assets_to_validate=assets_to_validate,
    551                 run_id=run_id,

~/.pyenv/shims/versions/3.8.11/envs/great_expectations_public/lib/python3.8/site-packages/great_expectations/validation_operators/validation_operators.py in run(self, assets_to_validate, run_id, evaluation_parameters, run_name, run_time, result_format)
    330             )
    331             run_result_obj["validation_result"] = batch_validation_result
--> 332             batch_actions_results = self._run_actions(
    333                 batch,
    334                 expectation_suite_identifier,

~/.pyenv/shims/versions/3.8.11/envs/great_expectations_public/lib/python3.8/site-packages/great_expectations/validation_operators/validation_operators.py in _run_actions(self, batch, expectation_suite_identifier, expectation_suite, batch_validation_result, run_id)
    405                     "Error running action with name {}".format(action["name"])
    406                 )
--> 407                 raise e
    408 
    409         return batch_actions_results

~/.pyenv/shims/versions/3.8.11/envs/great_expectations_public/lib/python3.8/site-packages/great_expectations/validation_operators/validation_operators.py in _run_actions(self, batch, expectation_suite_identifier, expectation_suite, batch_validation_result, run_id)
    386             )
    387             try:
--> 388                 action_result = self.actions[action["name"]].run(
    389                     validation_result_suite_identifier=validation_result_id,
    390                     validation_result_suite=batch_validation_result,

~/.pyenv/shims/versions/3.8.11/envs/great_expectations_public/lib/python3.8/site-packages/great_expectations/checkpoint/actions.py in run(self, validation_result_suite, validation_result_suite_identifier, data_asset, **kwargs)
     56         :return:
     57         """
---> 58         return self._run(
     59             validation_result_suite,
     60             validation_result_suite_identifier,

~/.pyenv/shims/versions/3.8.11/envs/great_expectations_public/lib/python3.8/site-packages/great_expectations/checkpoint/actions.py in _run(self, validation_result_suite, validation_result_suite_identifier, data_asset, payload)
    787             )
    788 
--> 789         self.data_context.store_evaluation_parameters(validation_result_suite)
    790 
    791 

~/.pyenv/shims/versions/3.8.11/envs/great_expectations_public/lib/python3.8/site-packages/great_expectations/data_context/data_context.py in store_evaluation_parameters(self, validation_results, target_store_name)
   2404     def store_evaluation_parameters(self, validation_results, target_store_name=None):
   2405         if not self._evaluation_parameter_dependencies_compiled:
-> 2406             self._compile_evaluation_parameter_dependencies()
   2407 
   2408         if target_store_name is None:

~/.pyenv/shims/versions/3.8.11/envs/great_expectations_public/lib/python3.8/site-packages/great_expectations/data_context/data_context.py in _compile_evaluation_parameter_dependencies(self)
   2436         self._evaluation_parameter_dependencies = {}
   2437         for key in self.expectations_store.list_keys():
-> 2438             expectation_suite = self.expectations_store.get(key)
   2439             if not expectation_suite:
   2440                 continue

~/.pyenv/shims/versions/3.8.11/envs/great_expectations_public/lib/python3.8/site-packages/great_expectations/data_context/store/store.py in get(self, key)
    151 
    152         if value:
--> 153             return self.deserialize(key, value)
    154         else:
    155             return None

~/.pyenv/shims/versions/3.8.11/envs/great_expectations_public/lib/python3.8/site-packages/great_expectations/data_context/store/expectations_store.py in deserialize(self, key, value)
    179             return self._expectationSuiteSchema.load(value)
    180         else:
--> 181             return self._expectationSuiteSchema.loads(value)
    182 
    183     def self_check(self, pretty_print):

~/.pyenv/shims/versions/3.8.11/envs/great_expectations_public/lib/python3.8/site-packages/great_expectations/marshmallow__shade/schema.py in loads(self, json_data, many, partial, unknown, **kwargs)
    766             if invalid data are passed.
    767         """
--> 768         data = self.opts.render_module.loads(json_data, **kwargs)
    769         return self.load(data, many=many, partial=partial, unknown=unknown)
    770 

~/.pyenv/shims/versions/3.8.11/lib/python3.8/json/__init__.py in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    355             parse_int is None and parse_float is None and
    356             parse_constant is None and object_pairs_hook is None and not kw):
--> 357         return _default_decoder.decode(s)
    358     if cls is None:
    359         cls = JSONDecoder

~/.pyenv/shims/versions/3.8.11/lib/python3.8/json/decoder.py in decode(self, s, _w)
    335 
    336         """
--> 337         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338         end = _w(s, end).end()
    339         if end != len(s):

~/.pyenv/shims/versions/3.8.11/lib/python3.8/json/decoder.py in raw_decode(self, s, idx)
    351         """
    352         try:
--> 353             obj, end = self.scan_once(s, idx)
    354         except StopIteration as err:
    355             raise JSONDecodeError("Expecting value", s, err.value) from None

JSONDecodeError: Expecting property name enclosed in double quotes: line 17 column 7 (char 452)
```

**Expected behavior**

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: 0.13.22 and 0.13.33

Pyenv virtualenv with python 3.8.11 and the following installed
```
Package             Version
------------------- ---------
altair              4.1.0
appnope             0.1.2
argon2-cffi         21.1.0
attrs               21.2.0
backcall            0.2.0
backports.zoneinfo  0.2.1
bleach              4.1.0
boto3               1.17.92
botocore            1.20.112
certifi             2021.5.30
cffi                1.14.6
charset-normalizer  2.0.4
click               8.0.1
debugpy             1.4.3
decorator           5.0.9
defusedxml          0.7.1
entrypoints         0.3
great-expectations  0.13.33
greenlet            1.1.1
idna                3.2
importlib-metadata  4.8.1
ipykernel           6.4.1
ipython             7.27.0
ipython-genutils    0.2.0
ipywidgets          7.6.4
jedi                0.18.0
Jinja2              3.0.1
jmespath            0.10.0
jsonpatch           1.32
jsonpointer         2.1
jsonschema          3.2.0
jupyter-client      7.0.2
jupyter-core        4.7.1
jupyterlab-pygments 0.1.2
jupyterlab-widgets  1.0.1
MarkupSafe          2.0.1
matplotlib-inline   0.1.3
mistune             0.8.4
nbclient            0.5.4
nbconvert           6.1.0
nbformat            5.1.3
nest-asyncio        1.5.1
notebook            6.4.3
numpy               1.21.2
packaging           21.0
pandas              1.3.2
pandocfilters       1.4.3
parso               0.8.2
pexpect             4.8.0
pickleshare         0.7.5
pip                 21.1.1
prometheus-client   0.11.0
prompt-toolkit      3.0.20
psycopg2-binary     2.9.1
ptyprocess          0.7.0
pycparser           2.20
Pygments            2.10.0
pyparsing           2.4.7
pyrsistent          0.18.0
python-dateutil     2.8.2
pytz                2021.1
pyzmq               22.2.1
requests            2.26.0
ruamel.yaml         0.17.16
ruamel.yaml.clib    0.2.6
s3transfer          0.4.2
scipy               1.7.1
Send2Trash          1.8.0
setuptools          56.0.0
six                 1.16.0
SQLAlchemy          1.4.23
sqlalchemy-redshift 0.8.5
termcolor           1.1.0
terminado           0.12.1
testpath            0.5.0
toolz               0.11.1
tornado             6.1
tqdm                4.62.2
traitlets           5.1.0
tzlocal             3.0
urllib3             1.26.6
wcwidth             0.2.5
webencodings        0.5.1
widgetsnbextension  3.5.1
zipp                3.5.0
```

**Additional context**
We use redshift as our data store
This ONLY occurs when using `expectations_store` of `TupleS3StoreBackend`

**Comment by NathanFarmer** [comment]
Thanks for opening this issue @scoyne2! We will take a look and respond over the next few days. One initial question I have is in the last line did you mean to say `TupleS3StoreBackend` instead of `TupleFilesystemStoreBackend`?

**Comment by scoyne2** [comment]
@NathanFarmer oops, good eye. Yes, I have corrected

**Comment by scoyne2** [comment]
ive been digging into this error deeper, it appears this is actually occurring during data doc build, from the following in my code

```context.build_data_docs()```

**Comment by scoyne2** [comment]
Actually, this was 100% human error, i needed to add `"mostly": 1` to my checkpoint, else the data docs failed

```
    {
      "expectation_type": "expect_column_values_to_not_be_null",
      "kwargs": {
        "column": "anonymous_id",
        "mostly": 1
      },
      "meta": {}
    }
```

once i add `"mostly": 1` this is now working on 0.13.35 so i am closing this out
