### ISSUE TITLE
[DOCS] Checkpoint without ".yml" file

### ISSUE THREAD

**Issue by tnorlund-dsc** [fivetran/great_expectations#3404]
**Is your feature request related to a problem? Please describe.**
I've been able to [create a context without a ".yml" file](https://docs.greatexpectations.io/docs/guides/setup/configuring_data_contexts/how_to_instantiate_a_data_context_without_a_yml_file) in AWS EMR. I then created a validator using an [in-memory Spark data frame](in-memory).

I now have an S3 bucket with the expectations ".json" file, the data docs static site, and a directory to hold my validations. I'd like to generate a checkpoint *without* the CLI or a ".yml" file.

I was recommended to write the ".yml" file as a string, and parse it out with a `yaml.load()`, but I think we could do better.

**Describe the solution you'd like**
Documentation for `context.add_checkpoint()` without a ".yml" file. I'd really like keyword arguments like you guys have for [creating a context without a ".yml" file](https://docs.greatexpectations.io/docs/guides/setup/configuring_data_contexts/how_to_instantiate_a_data_context_without_a_yml_file).

**Additional context**
Really good product, but you guys need more documentation for people that aren't reliant on the CLI.

**Comment by NathanFarmer** [comment]
Thanks for submitting this issue @tnorlund-dsc! We are actively adding to the new documentation site, and I agree that this would be value added that also does not exist in the legacy docs to my knowledge. Would you be interested in submitting a PR for this? I am happy to offer any guidance needed.

**Comment by tnorlund-dsc** [comment]
I'd love to help out. I'm currently having difficulty while adding the checkpoint with a Spark DF.

I've followed the steps in the [create a context without a ".yml" file](https://docs.greatexpectations.io/docs/guides/setup/configuring_data_contexts/how_to_instantiate_a_data_context_without_a_yml_file) documentation. I'm now trying to add a checkpoint:

```
context.add_checkpoint(
    name = "my_exmaple_checkpoint",
    config_version = 1.0,
    class_name = "SimpleCheckpoint",
    run_name_template= f'%Y%m%d-%H%M%S-my-run-name-template-{expectation_suite_name}', 
    validations = [
        {
            'expectation_suite_name': 'my_example_suite',
            'batch_request': {
              'datasource_name': batch_request.datasource_name, 
              'data_connector_name': batch_request.data_connector_name, 
              'data_asset_name': batch_request.data_asset_name, 
              'runtime_parameters': batch_request.runtime_parameters, 
              'batch_identifiers': batch_request.batch_identifiers, 
              'batch_spec_passthrough': batch_request.batch_spec_passthrough
            }
        }
    ],
    action_list= [
        {
            'name': 'store_validation_result', 
            'action': {
                'class_name': 'StoreValidationResultAction'
            }
        }, 
        {
            'name': 'store_evaluation_params', 
            'action': {
                'class_name': 'StoreEvaluationParametersAction'
            }
        }, 
        {
            'name': 'update_data_docs', 
            'action': {
                'class_name': 'UpdateDataDocsAction'
            }
        }
    ]
)
```

After attempting to execute this, I get an error:
> An error was encountered:
maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "/tmp/1631904963250-0/lib/python3.7/site-packages/great_expectations/data_context/data_context.py", line 3160, in add_checkpoint
    properties=checkpoint_config, clean_falsy=True
  File "/tmp/1631904963250-0/lib/python3.7/site-packages/great_expectations/util.py", line 947, in filter_properties_dict
    properties = copy.deepcopy(properties)
  File "/tmp/1631904963250-0/lib64/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/tmp/1631904963250-0/lib64/python3.7/copy.py", line 241, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/tmp/1631904963250-0/lib64/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/tmp/1631904963250-0/lib64/python3.7/copy.py", line 216, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/tmp/1631904963250-0/lib64/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/tmp/1631904963250-0/lib64/python3.7/copy.py", line 241, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/tmp/1631904963250-0/lib64/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/tmp/1631904963250-0/lib64/python3.7/copy.py", line 241, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/tmp/1631904963250-0/lib64/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/tmp/1631904963250-0/lib64/python3.7/copy.py", line 241, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/tmp/1631904963250-0/lib64/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/tmp/1631904963250-0/lib64/python3.7/copy.py", line 281, in _reconstruct
    state = deepcopy(state, memo)
  File "/tmp/1631904963250-0/lib64/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/tmp/1631904963250-0/lib64/python3.7/copy.py", line 241, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/tmp/1631904963250-0/lib64/python3.7/copy.py", line 161, in deepcopy
    y = copier(memo)
  File "/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1248, in __call__
    args_command, temp_args = self._build_args(*args)
  File "/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1212, in _build_args
    (new_args, temp_args) = self._get_args(args)
  File "/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1199, in _get_args
    temp_arg = converter.convert(arg, self.gateway_client)
  File "/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_collections.py", line 513, in convert
    java_map[key] = object[key]
  File "/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_collections.py", line 72, in __setitem__
    self.put(key, value)
  File "/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1248, in __call__
    args_command, temp_args = self._build_args(*args)
  File "/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1218, in _build_args
    [get_command_part(arg, self.pool) for arg in new_args])
  File "/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1218, in <listcomp>
    [get_command_part(arg, self.pool) for arg in new_args])
  File "/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 298, in get_command_part
    command_part = REFERENCE_TYPE + parameter._get_object_id()
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/dataframe.py", line 1305, in __getattr__
    if name not in self.columns:
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/dataframe.py", line 940, in columns
    return [f.name for f in self.schema.fields]
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/dataframe.py", line 254, in schema
    if self._schema is None:
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/dataframe.py", line 1305, in __getattr__
    if name not in self.columns:
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/dataframe.py", line 940, in columns
    return [f.name for f in self.schema.fields]
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/dataframe.py", line 254, in schema
    if self._schema is None:
...

**Comment by tnorlund-dsc** [comment]
This is currently being handled by [this issue](https://github.com/great-expectations/great_expectations/issues/3437).

**Comment by NathanFarmer** [comment]
Hi @tnorlund-dsc! I am reopening this issue as we seem to have both a bug and a gap in documentation here.

**Comment by NathanFarmer** [comment]
Various bugs in this workflow have been addressed by:
- https://github.com/great-expectations/great_expectations/pull/3680
- https://github.com/great-expectations/great_expectations/pull/3713
- https://github.com/great-expectations/great_expectations/pull/3718
- https://github.com/great-expectations/great_expectations/pull/3723

The documentation gaps have been addressed by:
- https://github.com/great-expectations/great_expectations/pull/3756
- https://github.com/great-expectations/great_expectations/pull/3787
