### ISSUE TITLE
Concurrent runs of build_data_docs throws an error on Databricks DBFS file store

### ISSUE THREAD

**Issue by amybachir** [fivetran/great_expectations#3487]
When I run 2 concurrent automated pipelines which validate data and update the data docs, I noticed that build_data_docs (version 0.13.33)  fails in one of the pipelines. The error thrown suggests the failure is related to `build_data_docs` attempting to write to the file system. I’m storing the data docs in a Databricks DBFS mount with Azure blob storage backend.

Here is the error:
```
Error running action with name update_data_docs
Traceback (most recent call last):
  File "/databricks/python/lib/python3.8/site-packages/great_expectations/validation_operators/validation_operators.py", line 392, in _run_actions
    action_result = self.actions[action["name"]].run(
  File "/databricks/python/lib/python3.8/site-packages/great_expectations/validation_operators/actions.py", line 52, in run
    return self._run(
  File "/databricks/python/lib/python3.8/site-packages/great_expectations/validation_operators/actions.py", line 640, in _run
    data_docs_index_pages = self.data_context.build_data_docs(
  File "/databricks/python/lib/python3.8/site-packages/great_expectations/core/usage_statistics/usage_statistics.py", line 261, in usage_statistics_wrapped_method
    result = func(*args, **kwargs)
  File "/databricks/python/lib/python3.8/site-packages/great_expectations/data_context/data_context.py", line 1747, in build_data_docs
    index_page_resource_identifier_tuple = site_builder.build(
  File "/databricks/python/lib/python3.8/site-packages/great_expectations/render/renderer/site_builder.py", line 287, in build
    self.target_store.copy_static_assets()
  File "/databricks/python/lib/python3.8/site-packages/great_expectations/data_context/store/html_site_store.py", line 353, in copy_static_assets
    self.copy_static_assets(new_source_dir)
  File "/databricks/python/lib/python3.8/site-packages/great_expectations/data_context/store/html_site_store.py", line 353, in copy_static_assets
    self.copy_static_assets(new_source_dir)
  File "/databricks/python/lib/python3.8/site-packages/great_expectations/data_context/store/html_site_store.py", line 379, in copy_static_assets
    self.store_backends["static_assets"].set(
  File "/databricks/python/lib/python3.8/site-packages/great_expectations/data_context/store/store_backend.py", line 117, in set
    return self._set(key, value, **kwargs)
  File "/databricks/python/lib/python3.8/site-packages/great_expectations/data_context/store/tuple_store_backend.py", line 291, in _set
    outfile.write(value)
OSError: [Errno 22] Invalid argument
```

And here what my data context looks like:

```
expectation_store_dir="/mnt/greatexpectations/expectations"
    validation_store_dir="/mnt/greatexpectations/validations"
    docs_store_dir="/mnt/greatexpectations/docs"

    project_config = DataContextConfig(
        config_version=2,
        plugins_directory=None,
        config_variables_file_path=None,

        datasources={
            "spark_datasource": {
                "data_asset_type": {
                    "class_name": "CustomSparkDFValidations",
                    "module_name": "SDPaaS_data_validation.validate",
                },
                "class_name": "SparkDFDatasource",
                "module_name": "great_expectations.datasource",
                "batch_kwargs_generators": {},
            }
        },
        stores={
        "expectations_store": {
            "class_name": "ExpectationsStore",
            "store_backend": {
                "class_name": "TupleFilesystemStoreBackend",
                "base_directory": "/dbfs" + expectation_store_dir,
            },
        },
        "validations_store": {
            "class_name": "ValidationsStore",
            "store_backend": {
                "class_name": "TupleFilesystemStoreBackend",
                "base_directory": "/dbfs" + validation_store_dir,
            },
        },
        "evaluation_parameter_store": {"class_name": "EvaluationParameterStore"},
    },
    expectations_store_name="expectations_store",
    validations_store_name="validations_store",
    evaluation_parameter_store_name="evaluation_parameter_store",
    data_docs_sites={
        "local_site": {
            "class_name": "SiteBuilder",
            "store_backend": {
                "class_name": "TupleFilesystemStoreBackend",
                "base_directory": "/dbfs" + docs_store_dir,
            },
            "site_index_builder": {
                "class_name": "DefaultSiteIndexBuilder",
                "show_cta_footer": True,
            },
        }
    },
    validation_operators={
    "action_list_operator": {
        "class_name": "ActionListValidationOperator",
        "action_list": [
            {
                "name": "store_validation_result",
                "action": {"class_name": "StoreValidationResultAction"},
            },
            {
                "name": "store_evaluation_params",
                "action": {"class_name": "StoreEvaluationParametersAction"},
            },
            {
                "name": "update_data_docs",
                "action": {"class_name": "UpdateDataDocsAction"},
            },
        ],
    }
    },
    anonymous_usage_statistics={
    "enabled": True
    }
    )

    context = BaseDataContext(project_config=project_config)
```

**Comment by NathanFarmer** [comment]
Hi @amybachir! Thanks for opening this issue. We will take a look and respond soon.

**Comment by talagluck** [comment]
Hi @amybachir - thanks again for opening this, and apologies for delays. After some internal discussion, we've concluded that we don't have a great way to support concurrent runs like this. Instead, we would recommend the creation of a `build_data_docs` task that only runs after both of your pipelines are complete.

I'm going to close this for now, but please don't hesitate to reach out if you have any further questions.
