### ISSUE TITLE
Error when rendering documentation for partitioned parquet file

### ISSUE THREAD

**Issue by maryletteroa** [fivetran/great_expectations#3605]
**Describe the bug**
An error occurs while building documentation from partitioned parquet tables. 

**To Reproduce**

(Steps 8-9 might be specific to my case but could be connected to the error, so just including it here)

1. Add partitioned parquet table as datasource `great_expectations datasource new`
2. Profile parquet table e.g. `great_expectations datasource profile raw_stores`
3. Build docs in terminal `great_expectations docs build`
4. Error occurs (see details below)
5. Locate the HTML docs (it is still written in `great_expectations/uncommitted/data_docs/local_site/index.html`)
6. Edit the rendered expectations from the profile e.g `great_expectations suite edit raw_stores.subdir_reader.p_ingest_date=2021-10-25.BasicDatasetProfile`
7. Error occurs again in the last cell where docs are being built,  (similar error below)
8. Locate the latest Validation Results in the HTML docs
9. Click latest validation result
10. Error occurs: Page does not load
11. Locate the validation HTML in the great_expectation docs directory
12. The HTML document for the validation result is present and loads

Error from Step 4
```
An unexpected Exception occurred during data docs rendering.  Because of this error, certain parts of data docs will not be rendered properly and/or may not appear altogether.  Please use the 
trace, included in this message, to diagnose and repair the underlying issue.  Detailed information follows:                                                                                    
                ValueError: "Unknown format code 'f' for object of type 'str'".  Traceback: "Traceback (most recent call last):                                                                 
  File "/home/maryletteroa/.local/share/virtualenvs/retail_data-IYBV7HJ8/lib/python3.9/site-packages/great_expectations/render/renderer/column_section_renderer.py", line 115, in render        
    getattr(self, content_block_function_name)(evrs)                                            
  File "/home/maryletteroa/.local/share/virtualenvs/retail_data-IYBV7HJ8/lib/python3.9/site-packages/great_expectations/render/renderer/column_section_renderer.py", line 324, in _render_stats_table                                                                                           
    table_rows.append(renderer_impl(result=evr))                                                
  File "/home/maryletteroa/.local/share/virtualenvs/retail_data-IYBV7HJ8/lib/python3.9/site-packages/great_expectations/render/renderer/renderer.py", line 13, in inner_func                    
    return renderer_fn(*args, **kwargs)                                                         
  File "/home/maryletteroa/.local/share/virtualenvs/retail_data-IYBV7HJ8/lib/python3.9/site-packages/great_expectations/expectations/core/expect_column_min_to_be_between.py", line 214, in _descriptive_stats_table_min_row_renderer                                                           
    "{:.2f}".format(result.result["observed_value"]),                                           
ValueError: Unknown format code 'f' for object of type 'str'                                    
".    
```
Error from Step 7
```
2021-10-27T08:46:36+0800 - ERROR - An unexpected Exception occurred during data docs rendering.  Because of this error, certain parts of data docs will not be rendered properly and/or may not appear altogether.  Please use the trace, included in this message, to diagnose and repair the underlying issue.  Detailed information follows:
                ValueError: "Unknown format code 'f' for object of type 'str'".  Traceback: "Traceback (most recent call last):
  File "/home/maryletteroa/.local/share/virtualenvs/retail_data-IYBV7HJ8/lib/python3.9/site-packages/great_expectations/render/renderer/column_section_renderer.py", line 115, in render
    getattr(self, content_block_function_name)(evrs)
  File "/home/maryletteroa/.local/share/virtualenvs/retail_data-IYBV7HJ8/lib/python3.9/site-packages/great_expectations/render/renderer/column_section_renderer.py", line 324, in _render_stats_table
    table_rows.append(renderer_impl(result=evr))
  File "/home/maryletteroa/.local/share/virtualenvs/retail_data-IYBV7HJ8/lib/python3.9/site-packages/great_expectations/render/renderer/renderer.py", line 13, in inner_func
    return renderer_fn(*args, **kwargs)
  File "/home/maryletteroa/.local/share/virtualenvs/retail_data-IYBV7HJ8/lib/python3.9/site-packages/great_expectations/expectations/core/expect_column_min_to_be_between.py", line 214, in _descriptive_stats_table_min_row_renderer
    "{:.2f}".format(result.result["observed_value"]),
ValueError: Unknown format code 'f' for object of type 'str'
".
2021-10-27T08:46:38+0800 - ERROR - An unexpected Exception occurred during data docs rendering.  Because of this error, certain parts of data docs will not be rendered properly and/or may not appear altogether.  Please use the trace, included in this message, to diagnose and repair the underlying issue.  Detailed information follows:
                ValueError: "Unknown format code 'f' for object of type 'str'".  Traceback: "Traceback (most recent call last):
  File "/home/maryletteroa/.local/share/virtualenvs/retail_data-IYBV7HJ8/lib/python3.9/site-packages/great_expectations/render/renderer/column_section_renderer.py", line 115, in render
    getattr(self, content_block_function_name)(evrs)
  File "/home/maryletteroa/.local/share/virtualenvs/retail_data-IYBV7HJ8/lib/python3.9/site-packages/great_expectations/render/renderer/column_section_renderer.py", line 324, in _render_stats_table
    table_rows.append(renderer_impl(result=evr))
  File "/home/maryletteroa/.local/share/virtualenvs/retail_data-IYBV7HJ8/lib/python3.9/site-packages/great_expectations/render/renderer/renderer.py", line 13, in inner_func
    return renderer_fn(*args, **kwargs)
  File "/home/maryletteroa/.local/share/virtualenvs/retail_data-IYBV7HJ8/lib/python3.9/site-packages/great_expectations/expectations/core/expect_column_min_to_be_between.py", line 214, in _descriptive_stats_table_min_row_renderer
    "{:.2f}".format(result.result["observed_value"]),
ValueError: Unknown format code 'f' for object of type 'str'
".
2021-10-27T08:46:38+0800 - ERROR - An unexpected Exception occurred during data docs rendering.  Because of this error, certain parts of data docs will not be rendered properly and/or may not appear altogether.  Please use the trace, included in this message, to diagnose and repair the underlying issue.  Detailed information follows:
                ValueError: "Unknown format code 'f' for object of type 'str'".  Traceback: "Traceback (most recent call last):
  File "/home/maryletteroa/.local/share/virtualenvs/retail_data-IYBV7HJ8/lib/python3.9/site-packages/great_expectations/render/renderer/column_section_renderer.py", line 115, in render
    getattr(self, content_block_function_name)(evrs)
  File "/home/maryletteroa/.local/share/virtualenvs/retail_data-IYBV7HJ8/lib/python3.9/site-packages/great_expectations/render/renderer/column_section_renderer.py", line 324, in _render_stats_table
    table_rows.append(renderer_impl(result=evr))
  File "/home/maryletteroa/.local/share/virtualenvs/retail_data-IYBV7HJ8/lib/python3.9/site-packages/great_expectations/render/renderer/renderer.py", line 13, in inner_func
    return renderer_fn(*args, **kwargs)
  File "/home/maryletteroa/.local/share/virtualenvs/retail_data-IYBV7HJ8/lib/python3.9/site-packages/great_expectations/expectations/core/expect_column_min_to_be_between.py", line 214, in _descriptive_stats_table_min_row_renderer
    "{:.2f}".format(result.result["observed_value"]),
ValueError: Unknown format code 'f' for object of type 'str'
".
```

**Expected behavior**
The documentation will be built without error, and the validation results will be accessible by clicking from the HTML docs

**Environment (please complete the following information):**
 - Operating System: Windows subsystem Linux Ubuntu 18.04 LTS 
 - Great Expectations Version: 0.13.38
 - Python version: 3.9
 - PySpark: 3.2.0

**Additional context**
N/A

**Comment by talagluck** [comment]
Hi @maryletteroa - thank you so much for raising this issue! I have a couple of follow-up questions.
- Are you able to tell the type of the data in the column that is failing?
- It appears that you are using the V2 API. Is there a specific reason for this? 

Thanks! We will review and be in touch.

**Comment by maryletteroa** [comment]
hi @talagluck , about V2 API, it's because I'm using profile in the commandline `great_expectations datasource profile <table` which is not currently available in V3. I get results from the BasicDatasetProfiler class. 

All my columns are StringType except for the ingest_datetime which is TimeStampType and p_ingest_date which is DateType

**Comment by talagluck** [comment]
Hi @maryletteroa - thanks for the follow-up. Just a heads-up, the BasicDatasetProfiler is not available for V3, but the UserConfigurableProfiler is, in case that is helpful for you.

It looks like this error might be occurring due to running `expect_column_min_to_be_between` on a string column. Is that something that is happening in your suite?

**Comment by maryletteroa** [comment]
hi @talagluck, I think it's possible that that's what is happening. I'll checkout UserConfigurableProfiler but is that something that I can access from the CLI or just through Python?

**Comment by talagluck** [comment]
Hi @maryletteroa, the UserConfigurableProfiler is the default profiler from the CLI. 

For V3, you can access it by running `great_expectations --v3-api suite new` and then selecting `3. Automatically, using a profiler`.

For V2, you can access it by running `great_expectations suite scaffold`.

**Comment by maryletteroa** [comment]
Great. Thanks @talagluck! Will try these methods.

**Comment by talagluck** [comment]
Sounds good, thanks @maryletteroa! I'm going to close this issue for now, as I believe it has to do with the data not being the right type for the expectation, but please feel free to re-open if that turns out to not be the case.
