### ISSUE TITLE
Error when trying to use mssql as expectations store and validations store

### ISSUE THREAD

**Issue by shizidushu** [fivetran/great_expectations#3615]
**Describe the bug**
Error when trying to configure SQL Server as validations store or expectations store.

**To Reproduce**

### 1. ValidationsStore
Configure `great_expectations.yml`
```yml
  validations_mssql_store:
    class_name: ValidationsStore
    store_backend:
      class_name: DatabaseStoreBackend
      connection_string: mssql+pyodbc://sa:*****@*****:1433/db_name?driver=ODBC Driver 17 for SQL Server
```

Run command 
```bash
great_expectations --v3-api store list
```

Get Error
```
Using v3 (Batch Request) API
Error Unable to connect to table ge_validations_store because of an error. It is possible your table needs to be migrated to a new schema.  SqlAlchemyError: (pyodbc.ProgrammingError) ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]表 'ge_validations_store' 中的列 'expectation_suite_name' 的类型不能用作索引中的键列。 (1919) (SQLExecDirectW)")
[SQL: 
CREATE TABLE ge_validations_store (
        expectation_suite_name VARCHAR(max) NOT NULL, 
        run_name VARCHAR(max) NOT NULL, 
        run_time VARCHAR(max) NOT NULL, 
        batch_identifier VARCHAR(max) NOT NULL, 
        value VARCHAR(max) NULL, 
        PRIMARY KEY (expectation_suite_name, run_name, run_time, batch_identifier)
)

]
(Background on this error at: http://sqlalche.me/e/13/f405) occurred while attempting to instantiate a store.
Traceback (most recent call last):
  File "/home/yong/deployment/airflow-in-docker-lh/venv/bin/great_expectations", line 8, in <module>
    sys.exit(main())
  File "/home/yong/deployment/airflow-in-docker-lh/venv/lib/python3.8/site-packages/great_expectations/cli/cli.py", line 161, in main
    cli()
  File "/home/yong/deployment/airflow-in-docker-lh/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/yong/deployment/airflow-in-docker-lh/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/yong/deployment/airflow-in-docker-lh/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/yong/deployment/airflow-in-docker-lh/venv/lib/python3.8/site-packages/click/core.py", line 1256, in invoke
    Command.invoke(self, ctx)
  File "/home/yong/deployment/airflow-in-docker-lh/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/yong/deployment/airflow-in-docker-lh/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/yong/deployment/airflow-in-docker-lh/venv/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/yong/deployment/airflow-in-docker-lh/venv/lib/python3.8/site-packages/great_expectations/cli/store.py", line 15, in store
    context: DataContext = toolkit.load_data_context_with_error_handling(
  File "/home/yong/deployment/airflow-in-docker-lh/venv/lib/python3.8/site-packages/great_expectations/cli/toolkit.py", line 413, in load_data_context_with_error_handling
    context: DataContext = DataContext(context_root_dir=directory)
  File "/home/yong/deployment/airflow-in-docker-lh/venv/lib/python3.8/site-packages/great_expectations/data_context/data_context.py", line 4051, in __init__
    super().__init__(
  File "/home/yong/deployment/airflow-in-docker-lh/venv/lib/python3.8/site-packages/great_expectations/core/usage_statistics/usage_statistics.py", line 263, in usage_statistics_wrapped_method
    result = func(*args, **kwargs)
  File "/home/yong/deployment/airflow-in-docker-lh/venv/lib/python3.8/site-packages/great_expectations/data_context/data_context.py", line 358, in __init__
    self._init_stores(self.project_config_with_variables_substituted.stores)
  File "/home/yong/deployment/airflow-in-docker-lh/venv/lib/python3.8/site-packages/great_expectations/data_context/data_context.py", line 450, in _init_stores
    self._build_store_from_config(store_name, store_config)
  File "/home/yong/deployment/airflow-in-docker-lh/venv/lib/python3.8/site-packages/great_expectations/data_context/data_context.py", line 429, in _build_store_from_config
    new_store = build_store_from_config(
  File "/home/yong/deployment/airflow-in-docker-lh/venv/lib/python3.8/site-packages/great_expectations/data_context/util.py", line 157, in build_store_from_config
    module_name = store_config["module_name"]
KeyError: 'module_name'
```

### 2. ExpectationsStore

Configure `great_expectations.yml`
```yml
  expectations_mssql_store:
    class_name: ExpectationsStore
    store_backend: DatabaseStoreBackend
    connection_string: mssql+pyodbc://sa:*****@*****:1433/db_name?driver=ODBC Driver 17 for SQL Server
```

Run command 
```bash
great_expectations --v3-api store list
```

Get Error
```
Using v3 (Batch Request) API
Traceback (most recent call last):
  File "/home/yong/deployment/airflow-in-docker-lh/venv/bin/great_expectations", line 8, in <module>
    sys.exit(main())
  File "/home/yong/deployment/airflow-in-docker-lh/venv/lib/python3.8/site-packages/great_expectations/cli/cli.py", line 161, in main
    cli()
  File "/home/yong/deployment/airflow-in-docker-lh/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/yong/deployment/airflow-in-docker-lh/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/yong/deployment/airflow-in-docker-lh/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/yong/deployment/airflow-in-docker-lh/venv/lib/python3.8/site-packages/click/core.py", line 1256, in invoke
    Command.invoke(self, ctx)
  File "/home/yong/deployment/airflow-in-docker-lh/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/yong/deployment/airflow-in-docker-lh/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/yong/deployment/airflow-in-docker-lh/venv/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/yong/deployment/airflow-in-docker-lh/venv/lib/python3.8/site-packages/great_expectations/cli/store.py", line 15, in store
    context: DataContext = toolkit.load_data_context_with_error_handling(
  File "/home/yong/deployment/airflow-in-docker-lh/venv/lib/python3.8/site-packages/great_expectations/cli/toolkit.py", line 413, in load_data_context_with_error_handling
    context: DataContext = DataContext(context_root_dir=directory)
  File "/home/yong/deployment/airflow-in-docker-lh/venv/lib/python3.8/site-packages/great_expectations/data_context/data_context.py", line 4051, in __init__
    super().__init__(
  File "/home/yong/deployment/airflow-in-docker-lh/venv/lib/python3.8/site-packages/great_expectations/core/usage_statistics/usage_statistics.py", line 263, in usage_statistics_wrapped_method
    result = func(*args, **kwargs)
  File "/home/yong/deployment/airflow-in-docker-lh/venv/lib/python3.8/site-packages/great_expectations/data_context/data_context.py", line 358, in __init__
    self._init_stores(self.project_config_with_variables_substituted.stores)
  File "/home/yong/deployment/airflow-in-docker-lh/venv/lib/python3.8/site-packages/great_expectations/data_context/data_context.py", line 450, in _init_stores
    self._build_store_from_config(store_name, store_config)
  File "/home/yong/deployment/airflow-in-docker-lh/venv/lib/python3.8/site-packages/great_expectations/data_context/data_context.py", line 427, in _build_store_from_config
    store_config["store_backend"].update({"suppress_store_backend_id": True})
AttributeError: 'str' object has no attribute 'update'
```

**Expected behavior**
No error.

**Environment (please complete the following information):**
 - Ubuntu 20
 - great-expectations==0.13.37

**Comment by talagluck** [comment]
Hi @shizidushu - just a heads-up, it looks like you may have saved sensitive information in your connection string in Step 2 - I would recommend editing this, and changing all passwords.

**Comment by talagluck** [comment]
Otherwise, thank you for raising this issue! We will review, and be in touch. In the meantime, are you able to try using credentials in your `.yml` without using a connection string?

**Comment by shizidushu** [comment]
@talagluck Thank you for point it. I will try to use `config_variables.yml` for this. May you remove this issue from the rep?

**Comment by talagluck** [comment]
Hi @shizidushu, I am closing this issue for now, but I am unable to delete the issue. Feel free to re-open if you still have any trouble!
