### ISSUE TITLE
[ERROR] TypeError: "Object of type date is not JSON serializable" when rendering HTML

### ISSUE THREAD

**Issue by BilalHaniff** [fivetran/great_expectations#3670]
When I run the renderer on my validations (from the profiler), I get the "Object of type date is not JSON serializable" error.  I have a date column in my dataset.  When I convert it to string, I don't get this error.

An unexpected Exception occurred during data docs rendering.  Because of this error, certain parts of data docs will not be rendered properly and/or may not appear altogether.  Please use the trace, included in this message, to diagnose and repair the underlying issue.  Detailed information follows:
                **TypeError: "Object of type date is not JSON serializable".**  Traceback: "Traceback (most recent call last):
  File "/databricks/python/lib/python3.8/site-packages/great_expectations/render/renderer/column_section_renderer.py", line 115, in render
    getattr(self, content_block_function_name)(evrs)
  File "/databricks/python/lib/python3.8/site-packages/great_expectations/render/renderer/column_section_renderer.py", line 395, in _render_value_counts_bar_chart
    return get_renderer_impl(
  File "/databricks/python/lib/python3.8/site-packages/great_expectations/render/renderer/renderer.py", line 13, in inner_func
    return renderer_fn(*args, **kwargs)
  File "/databricks/python/lib/python3.8/site-packages/great_expectations/expectations/core/expect_column_distinct_values_to_be_in_set.py", line 329, in _descriptive_value_counts_bar_chart_renderer
    chart = bars.to_json()
  File "/databricks/python/lib/python3.8/site-packages/altair/utils/schemapi.py", line 372, in to_json
    dct = self.to_dict(validate=validate, ignore=ignore, context=context)
  File "/databricks/python/lib/python3.8/site-packages/altair/vegalite/v4/api.py", line 363, in to_dict
    copy.data = _prepare_data(original_data, context)
  File "/databricks/python/lib/python3.8/site-packages/altair/vegalite/v4/api.py", line 92, in _prepare_data
    data = _consolidate_data(data, context)
  File "/databricks/python/lib/python3.8/site-packages/altair/vegalite/v4/api.py", line 59, in _consolidate_data
    name = _dataset_name(values)
  File "/databricks/python/lib/python3.8/site-packages/altair/vegalite/v4/api.py", line 35, in _dataset_name
    values_json = json.dumps(values, sort_keys=True)
  File "/usr/local/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type date is not JSON serializable (edited) 

**To Reproduce**
1. Create GE dataframe with a column of datatype Date
2. Run the basic profiler on your dataframe
    expectation_suite_based_on_profiling, validation_result_based_on_profiling = ge_df.profile(BasicDatasetProfiler)
3. Render the HTML
DefaultJinjaPageView().render(ExpectationSuitePageRenderer().render(fp_expectation_suite_based_on_profiling))

**Expected behavior**
No error

**Environment (please complete the following information):**
 - Operating System: Azure Databricks
 - Great Expectations Version:  0.13.41

**Additional context**

**Comment by talagluck** [comment]
Thanks for opening this issue, @BilalHaniff! We will review and be in touch. As a side note, this type of Profiler is somewhat out-of-date, and so moving forward we would recommend using either the `UserConfigurableProfiler` or a RuleBasedProfiler.

**Comment by talagluck** [comment]
Hi @BilalHaniff - we are going to close this issue for now, since we won't be able to prioritize work on the `BasicDatasetProfiler`. That said, if this turns out to be an issue elsewhere in your workflow, please feel free to open another issue.
