### ISSUE TITLE
Cannot create new suite: Error while processing DataContextConfig: concurrency

### ISSUE THREAD

**Issue by mrkoloev** [fivetran/great_expectations#3754]
**Describe the bug**
I cannot create new suite after creating the new datasource
_Error while processing DataContextConfig_ occurs

**To Reproduce**
1. CLI: `great expectation v3-api datasource new`  => Y
2. CLI: `great expectation --v3-api datasource new` =>  (2). Relational database (SQL) => (6). others
3. Jupyter notebook: I entered datasource name, connection_string and executed all the cells.
4. CLI: `great expectation --v3-api suite new` and then this error occurred:

```
Using v3 (Batch Request) API
Error while processing DataContextConfig: concurrency
Encountered errors during loading config.  See ValidationError for more details.
Traceback (most recent call last):
  File "/usr/local/bin/great_expectations", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/great_expectations/cli/cli.py", line 161, in main
    cli()
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1665, in invoke
    super().invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/great_expectations/cli/suite.py", line 40, in suite
    context: DataContext = toolkit.load_data_context_with_error_handling(
  File "/usr/local/lib/python3.9/site-packages/great_expectations/cli/toolkit.py", line 413, in load_data_context_with_error_handling
    context: DataContext = DataContext(context_root_dir=directory)
  File "/usr/local/lib/python3.9/site-packages/great_expectations/data_context/data_context.py", line 3757, in __init__
    project_config = self._load_project_config()
  File "/usr/local/lib/python3.9/site-packages/great_expectations/data_context/data_context.py", line 3795, in _load_project_config
    return DataContextConfig.from_commented_map(
  File "/usr/local/lib/python3.9/site-packages/great_expectations/data_context/types/base.py", line 84, in from_commented_map
    config = cls._get_schema_instance().load(commented_map)
  File "/usr/local/lib/python3.9/site-packages/great_expectations/marshmallow__shade/schema.py", line 735, in load
    return self._do_load(
  File "/usr/local/lib/python3.9/site-packages/great_expectations/marshmallow__shade/schema.py", line 916, in _do_load
    self.handle_error(exc, data, many=many, partial=partial)
  File "/usr/local/lib/python3.9/site-packages/great_expectations/data_context/types/base.py", line 945, in handle_error
    raise ge_exceptions.InvalidDataContextConfigError(
great_expectations.exceptions.exceptions.InvalidDataContextConfigError: Error while processing DataContextConfig: concurrency
```

**Environment:**
 - Operating System: MacOS 12.0.1
 - Great Expectations Version: 0.13.44
 - PyCharm: 2021.2.3
 - Python 3.9

**Comment by austiezr** [comment]
Hey @mrkoloev! Thanks for raising this; we'll begin to review internally. In the meantime, would you be able to share your `great_expectations.yml` (scrubbed of any sensitive info!) here? That would help us better diagnose what may be happening.

**Comment by mrkoloev** [comment]
Hi @austiezr ! Here is my great_expectations.yml https://pastebin.com/hZHwQhZ8

```YAML
datasources:
  ch:
    data_connectors:
      default_runtime_data_connector_name:
        class_name: RuntimeDataConnector
        module_name: great_expectations.datasource.data_connector
        batch_identifiers:
          - default_identifier_name
      default_inferred_data_connector_name:
        class_name: InferredAssetSqlDataConnector
        module_name: great_expectations.datasource.data_connector
    module_name: great_expectations.datasource
    execution_engine:
      connection_string: clickhouse+native://USER:PASSWORD@HOST:9000/?session_id='qwer123'
      module_name: great_expectations.execution_engine
      class_name: SqlAlchemyExecutionEngine
    class_name: Datasource
```

**Comment by mrkoloev** [comment]
I don't know what happened but I created a new virtual environment and now it works fine until step the method .head() execution in jupyter notebook (suite creation). 

But there is another problem that GE uses non-existing table in "default" database instead of temporary table.

_creating temp table_
```SQL
CREATE TEMPORARY TABLE "ge_temp_11a9bf31" AS SELECT * 
FROM sandbox._test_GE_A
```

_select from 'default' database by default if db name is not explicit._
```SQL
SELECT * FROM ge_temp_11a9bf31 LIMIT 5
```


DBMS: ClickHouse
