### ISSUE TITLE
result_format parameter returns column not serializable error for Snowflake Datasource

### ISSUE THREAD

**Issue by dammyai** [fivetran/great_expectations#4080]
When using the result_format parameter in checkpoint, it's returning column not serializable error:
`results = context.run_checkpoint(
    checkpoint_name="cms_cp",
    result_format={
        "result_format": "COMPLETE",
        "include_unexpected_rows": True
    }
)`

**STEPS TO REPRODUCE**
1. Used ge v3 api to create new Datasource (Snowflake)
2. After creating Datasource, used ge v3 api to automatically create new expectations for a Snowflake table
3. Next, we created a checkpoint using ge v3 api with the earlier created expectations
4. When running checkpoint results, the following error is encountered.
`Error running action with name store_validation_result
Traceback (most recent call last):
  File "/Users/user/.local/share/virtualenvs/user-UVNi8mV9/lib/python3.7/site-packages/great_expectations/validation_operators/validation_operators.py", line 455, in _run_actions
    checkpoint_identifier=checkpoint_identifier,
  File "/Users/user/.local/share/virtualenvs/user-UVNi8mV9/lib/python3.7/site-packages/great_expectations/checkpoint/actions.py", line 69, in run
    **kwargs,
  File "/Users/user/.local/share/virtualenvs/user-UVNi8mV9/lib/python3.7/site-packages/great_expectations/checkpoint/actions.py", line 784, in _run
    expectation_suite_id=expectation_suite_ge_cloud_id,
  File "/Users/user/.local/share/virtualenvs/user-UVNi8mV9/lib/python3.7/site-packages/great_expectations/data_context/store/store.py", line 163, in set
    self.key_to_tuple(key), self.serialize(key, value), **kwargs
  File "/Users/user/.local/share/virtualenvs/user-UVNi8mV9/lib/python3.7/site-packages/great_expectations/data_context/store/validations_store.py", line 169, in serialize
    value, indent=2, sort_keys=True
  File "/Users/user/.local/share/virtualenvs/user-UVNi8mV9/lib/python3.7/site-packages/great_expectations/marshmallow__shade/schema.py", line 586, in dumps
    serialized = self.dump(obj, many=many)
  File "/Users/user/.local/share/virtualenvs/user-UVNi8mV9/lib/python3.7/site-packages/great_expectations/marshmallow__shade/schema.py", line 562, in dump
    result = self._serialize(processed_obj, many=many)
  File "/Users/user/.local/share/virtualenvs/user-UVNi8mV9/lib/python3.7/site-packages/great_expectations/marshmallow__shade/schema.py", line 526, in _serialize
    value = field_obj.serialize(attr_name, obj, accessor=self.get_attribute)
  File "/Users/user/.local/share/virtualenvs/user-UVNi8mV9/lib/python3.7/site-packages/great_expectations/marshmallow__shade/fields.py", line 309, in serialize
    return self._serialize(value, attr, obj, **kwargs)
  File "/Users/user/.local/share/virtualenvs/user-UVNi8mV9/lib/python3.7/site-packages/great_expectations/marshmallow__shade/fields.py", line 697, in _serialize
    return [self.inner._serialize(each, attr, obj, **kwargs) for each in value]
  File "/Users/user/.local/share/virtualenvs/user-UVNi8mV9/lib/python3.7/site-packages/great_expectations/marshmallow__shade/fields.py", line 697, in <listcomp>
    return [self.inner._serialize(each, attr, obj, **kwargs) for each in value]
  File "/Users/user/.local/share/virtualenvs/user-UVNi8mV9/lib/python3.7/site-packages/great_expectations/marshmallow__shade/fields.py", line 564, in _serialize
    return schema.dump(nested_obj, many=many)
  File "/Users/user/.local/share/virtualenvs/user-UVNi8mV9/lib/python3.7/site-packages/great_expectations/marshmallow__shade/schema.py", line 557, in dump
    PRE_DUMP, obj, many=many, original_data=obj
  File "/Users/user/.local/share/virtualenvs/user-UVNi8mV9/lib/python3.7/site-packages/great_expectations/marshmallow__shade/schema.py", line 1077, in _invoke_dump_processors
    tag, pass_many=False, data=data, many=many, original_data=original_data
  File "/Users/user/.local/share/virtualenvs/user-UVNi8mV9/lib/python3.7/site-packages/great_expectations/marshmallow__shade/schema.py", line 1233, in _invoke_processors
    data = processor(data, many=many, **kwargs)
  File "/Users/user/.local/share/virtualenvs/user-UVNi8mV9/lib/python3.7/site-packages/great_expectations/core/expectation_validation_result.py", line 252, in convert_result_to_serializable
    data.result = convert_to_json_serializable(data.result)
  File "/Users/user/.local/share/virtualenvs/user-UVNi8mV9/lib/python3.7/site-packages/great_expectations/core/util.py", line 159, in convert_to_json_serializable
    new_dict[str(key)] = convert_to_json_serializable(data[key])
  File "/Users/user/.local/share/virtualenvs/user-UVNi8mV9/lib/python3.7/site-packages/great_expectations/core/util.py", line 166, in convert_to_json_serializable
    new_list.append(convert_to_json_serializable(val))
  File "/Users/user/.local/share/virtualenvs/user-UVNi8mV9/lib/python3.7/site-packages/great_expectations/core/util.py", line 252, in convert_to_json_serializable
    % (str(data), type(data).__name__)
TypeError: ('DP.NG18.D2127.T1710', 1, None, '6E972TA40', '117       ', 'JOHN                          ', 'L                             ', 'DOE                              ', '19460320', '123 SURE RD                                          ', '                                                       ', '                                                       ', 'GEE                                 ', 'PA', '16923', '9052', 'F', '20141220', '20161221', '1-800', 'T', 'N', '20141222', '1-800', 'T', 'N', 'P078 ', 'DS Generic Legal Name                                                 ', datetime.datetime(2022, 1, 27, 10, 3, 51, 896000), '55', '10', 'ICD ERR ON COLUMNS') is of type LegacyRow which cannot be serialized.
`

**Expected behavior**
Expected to see the validation results including all the unexpected rows that failed expectations

**Environment (please complete the following information):**
 - Operating System: MacOS 
 - Great Expectations Version:  0.13.47

**Additional context**
We are integrating GE with Prefect eventually.

**Comment by joshua-stauffer** [comment]
Hi @dammyai, thanks for raising this issue - we have some context for where this is coming from, and will try to prioritize a fix soon.

**Comment by dammyai** [comment]
Thank you so much. This will help our team a lot!!

Thanks,
Dammy

**Comment by joshua-stauffer** [comment]
Hi @dammyai, when I follow your steps using the demo `taxi_data` data set I'm unable to reproduce this error, both on GE 0.13.47 and latest (0.14.6). Which Expectation is causing this error? It looks like this might be due to a function being passed into the serializer: `datetime.datetime(2022, 1, 27, 10, 3, 51, 896000)`

**Comment by dammyai** [comment]
Hi @joshua-stauffer thank you for looking at this! I'm using one of the tables in our Snowflake data warehouse. I tried with multiple expectations, the failed ones return this error. One of the columns on the table is a timestamp format.

**Comment by joshua-stauffer** [comment]
@dammyai happy to look into it! could you provide me with an example of one of the expectations that is failing so I can reproduce this on my end?

**Comment by dammyai** [comment]
Sure! Here's one:
`validator.expect_column_values_to_be_unique(column='mbi_id',result_format={
       "result_format": "COMPLETE",
       "include_unexpected_rows": True
   })`

**Comment by joshua-stauffer** [comment]
Hi @dammyai, thanks for the additional context -- I wasn't able to reproduce the exact error you're seeing, but I did encounter `TypeError: Object of type datetime is not JSON serializable` when trying to use `timestamp` columns with Snowflake and GE 0.14.5 or earlier, which I expect has the same root cause. When I upgrade GE to latest (0.14.6) however, my checkpoint validates without problem, and I'm able to see the complete unexpected row list. Could you try upgrading your project to 0.14.6 and see if the error persists?

**Comment by dammyai** [comment]
Hi Josh, you are right! I upgraded like you suggested and the error is gone
now. Thank you so much!!!!

**Comment by joshua-stauffer** [comment]
great, glad to hear it!
