### ISSUE TITLE
Configuring an Expectation/Validations store to use Amazon S3

### ISSUE THREAD

**Issue by vipmaha1** [fivetran/great_expectations#4154]
**Describe the bug**
I referred to Great-expectations documentations [how_to_configure_an_expectation_store_in_amazon_s3](https://docs.greatexpectations.io/docs/guides/setup/configuring_metadata_stores/how_to_configure_an_expectation_store_in_amazon_s3) , I have manually uploaded the expectation json to MinIO bucket named as "dqa" [MinIO](https://play.min.io:9443/buckets/dqa/browse/ZXhwZWN0YXRpb25z), but unable to read it using CLI command "ge suite list".

**To Reproduce**
1. Configure the S3 bucket & upload expectation JSON:
   a. Run `aws configure` and specify the MinIO key information.
   b. Run `aws configure list` to validate the settings
```
      Name                    Value             Type    Location
      ----                    -----             ----    --------
   profile                <not set>             None    None
access_key     ****************3P2F shared-credentials-file    
secret_key     ****************Y3TG shared-credentials-file    
    region                us-east-1      config-file    ~/.aws/config
```
  c. Copy existing Expectation JSON files to the S3 bucket.
```
   $  aws --endpoint-url https://play.min.io:9000 s3 cp getting_started_expectation_suite_taxi.json s3://dqa/expectations/
```
  d. I can get file content via boto3 successfully.
```
  import boto3
  s3 =boto3.client(
      service_name='s3',
      endpoint_url='https://play.min.io:9000'
  )
  s3_file = s3.get_object(Bucket='dqa', Key='expectations/getting_started_expectation_suite_taxi.json')
  print(s3_file['Body'].read().decode('utf-8'))
```

2. Update your configuration file to include a new store for Expectations on S3.
```
expectations_store_name: expectations_S3_store
stores:
  expectations_S3_store:
    class_name: ExpectationsStore
    store_backend:
      class_name: TupleS3StoreBackend
      endpoint_url: "https://play.min.io:9000"
      bucket: 'dqa'
      prefix: 'expectations/'
```

3. Confirm that the new Expectations store has been added by running `great_expectations store list`
```
Invalid store configuration: Please check the configuration of your TupleS3StoreBackend named expectations_S3_store
Invalid store configuration: Please check the configuration of your TupleS3StoreBackend named validations_S3_store
4 active Stores found:

 - name: expectations_S3_store
   class_name: ExpectationsStore
   store_backend:
     class_name: TupleS3StoreBackend
     bucket: dqa
     endpoint_url: https://play.min.io:9000
     prefix: expectations/

 - name: validations_S3_store
   class_name: ValidationsStore
   store_backend:
     class_name: TupleS3StoreBackend
     bucket: dqa
     endpoint_url: https://play.min.io:9000
     prefix: validations/

  ......
```

4. Confirm that Expectations can be accessed from Amazon S3 by running `great_expectations suite list` that resulted in  below ERROR:
```
Using v3 (Batch Request) API
Invalid store configuration: Please check the configuration of your TupleS3StoreBackend named expectations_S3_store
Invalid store configuration: Please check the configuration of your TupleS3StoreBackend named validations_S3_store
Traceback (most recent call last):
  File "/Users/vipulmahajan/opt/anaconda3/bin/great_expectations", line 8, in <module>
    sys.exit(main())
  File "/Users/vipulmahajan/opt/anaconda3/lib/python3.8/site-packages/great_expectations/cli/cli.py", line 161, in main
    cli()
  File "/Users/vipulmahajan/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/vipulmahajan/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/vipulmahajan/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/vipulmahajan/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/vipulmahajan/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/vipulmahajan/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/vipulmahajan/opt/anaconda3/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/vipulmahajan/opt/anaconda3/lib/python3.8/site-packages/great_expectations/cli/suite.py", line 930, in suite_list
    raise e
  File "/Users/vipulmahajan/opt/anaconda3/lib/python3.8/site-packages/great_expectations/cli/suite.py", line 923, in suite_list
    suite_names: List[str] = context.list_expectation_suite_names()
  File "/Users/vipulmahajan/opt/anaconda3/lib/python3.8/site-packages/great_expectations/data_context/data_context.py", line 2213, in list_expectation_suite_names
    i.expectation_suite_name for i in self.list_expectation_suites()
  File "/Users/vipulmahajan/opt/anaconda3/lib/python3.8/site-packages/great_expectations/data_context/data_context.py", line 1995, in list_expectation_suites
    keys = self.expectations_store.list_keys()
  File "/Users/vipulmahajan/opt/anaconda3/lib/python3.8/site-packages/great_expectations/data_context/store/store.py", line 169, in list_keys
    for key in self._store_backend.list_keys()
  File "/Users/vipulmahajan/opt/anaconda3/lib/python3.8/site-packages/great_expectations/data_context/store/tuple_store_backend.py", line 610, in list_keys
    for page in page_iterator:
  File "/Users/vipulmahajan/opt/anaconda3/lib/python3.8/site-packages/botocore/paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "/Users/vipulmahajan/opt/anaconda3/lib/python3.8/site-packages/botocore/paginate.py", line 332, in _make_request
    return self._method(**current_kwargs)
  File "/Users/vipulmahajan/opt/anaconda3/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/vipulmahajan/opt/anaconda3/lib/python3.8/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidAccessKeyId) when calling the ListObjectsV2 operation: The AWS Access Key Id you provided does not exist in our records.
```

**Expected behavior**
Running `great_expectations suite list` should return the list of expectations uploaded to S3.

**Environment (please complete the following information):**
 - Operating System: MacOS Monterey 1.12
 - Great Expectations Version: 0.13.49

**Additional context**
In similar context , when I tried uploading the DataDocs and validations reports to S3 that resulted in similar ERROR.

**Comment by austiezr** [comment]
Hey @vipmaha1 ! Thank you for surfacing this issue. We currently don't have any direct support for MinIO; if you're able to solve this we would be happy to offer guidance and support through the contribution process but we won't be able to take this on internally at this time.

**Comment by vipmaha1** [comment]
The issue got resolved using below store config in great_expectation.yaml:

```
validations_minio_store:
    class_name: ValidationsStore
    store_backend:
      boto3_options:
        aws_access_key_id: ${MINIO_ACCESS_KEY}
        aws_secret_access_key: ${MINIO_SECRET_KEY}
        endpoint_url: ${MINIO_ENDPOINT}
      class_name: TupleS3StoreBackend
      bucket: 'BUCKETNAME'
      prefix: 'PREFIX'
```
