### ISSUE TITLE
SqlAlchemyQueryStore does not support connection_string

### ISSUE THREAD

**Issue by davidvanrooij** [fivetran/great_expectations#4223]
**Describe the bug**
SqlAlchemyQueryStore does not support connection_string as credentials. 

**To Reproduce**
1. Add the following to `great_expectation.yml`
 ```yaml
 stores:
  my_query_store:
    class_name: SqlAlchemyQueryStore
    credentials:
      connection_string: bigquery://dataset/table
    queries: "SELECT * FROM dataset.table;"
```
2. Use query store in expectation
3. Stacktrace:
``` 
Traceback (most recent call last):
  File "great_expectations/test.py", line 6, in <module>
    context = ge.get_context()
  File "python3.9/site-packages/great_expectations/util.py", line 1269, in get_context
    return DataContext()
  File "python3.9/site-packages/great_expectations/data_context/data_context.py", line 4184, in __init__
    super().__init__(
  File "python3.9/site-packages/great_expectations/core/usage_statistics/usage_statistics.py", line 306, in usage_statistics_wrapped_method
    result = func(*args, **kwargs)
  File "python3.9/site-packages/great_expectations/data_context/data_context.py", line 382, in __init__
    self._init_stores(self.project_config_with_variables_substituted.stores)
  File "python3.9/site-packages/great_expectations/data_context/data_context.py", line 474, in _init_stores
    self._build_store_from_config(store_name, store_config)
  File "python3.9/site-packages/great_expectations/data_context/data_context.py", line 453, in _build_store_from_config
    new_store = build_store_from_config(
  File "python3.9/site-packages/great_expectations/data_context/util.py", line 141, in build_store_from_config
    new_store = instantiate_class_from_config(
  File "python3.9/site-packages/great_expectations/data_context/util.py", line 115, in instantiate_class_from_config
    class_instance = class_(**config_with_defaults)
  File "python3.9/site-packages/great_expectations/data_context/store/query_store.py", line 80, in __init__
    drivername = credentials.pop("drivername")
KeyError: 'drivername'
```

**Expected behavior**
Support the connection string type of autherntication to facilitate using bigquery as backend. 

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version:  0.14.6

**Comment by davidvanrooij** [comment]
I created a PR for this issue: https://github.com/great-expectations/great_expectations/pull/4224
