### ISSUE TITLE
Configuring Validation Store: BlobNotFound Error

### ISSUE THREAD

**Issue by esfsbhagwat** [fivetran/great_expectations#4481]
Hi, I have installed great_expectations package on my local machine. Created the expectation suite, expectation store, validation results and finally able to get the data docs when I run the checkpoint. 
Now when I try to configure same in the Expectations Store by following the [link  ](https://docs.greatexpectations.io/docs/guides/setup/configuring_metadata_stores/how_to_configure_an_expectation_store_in_azure_blob_storage), by commenting out the expectation store for FileSystem, I was successful. Now when I tried to create the same for Validation store by following [link ](https://docs.greatexpectations.io/docs/guides/setup/configuring_metadata_stores/how_to_configure_a_validation_result_store_in_azure_blob_storage )and re-run the checkpoint I am being encountered with error message as "BlobNotFound". There are permissions set for the blob storage. Can someone please help.

C:\Users\venv\ge_demo>great_expectations checkpoint run Checkpoint_new_taxidata_new_az1
Using v3 (Batch Request) API
Calculating Metrics: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:52<00:00,  3.48s/it]
Error running action with name store_evaluation_params
Traceback (most recent call last):
  File "C:\Users\venv\lib\site-packages\great_expectations\validation_operators\validation_operators.py", line 455, in _run_actions
    checkpoint_identifier=checkpoint_identifier,
  File "C:\Users\venv\lib\site-packages\great_expectations\checkpoint\actions.py", line 77, in run
    **kwargs,
  File "C:\Users\venv\lib\site-packages\great_expectations\checkpoint\actions.py", line 902, in _run
    self.data_context.store_evaluation_parameters(validation_result_suite)
  File "C:\Users\venv\lib\site-packages\great_expectations\data_context\data_context.py", line 2357, in store_evaluation_parameters
    self._compile_evaluation_parameter_dependencies()
  File "C:\Users\venv\lib\site-packages\great_expectations\data_context\data_context.py", line 2391, in _compile_evaluation_parameter_dependencies
    expectation_suite_dict: dict = self.expectations_store.get(key)
  File "C:\Users\venv\lib\site-packages\great_expectations\data_context\store\expectations_store.py", line 176, in get
    return super().get(key)
  File "C:\Users\venv\lib\site-packages\great_expectations\data_context\store\store.py", line 150, in get
    value = self._store_backend.get(self.key_to_tuple(key))
  File "C:\Users\venv\lib\site-packages\great_expectations\data_context\store\store_backend.py", line 121, in get
    value = self._get(key, **kwargs)
  File "C:\Users\venv\lib\site-packages\great_expectations\data_context\store\tuple_store_backend.py", line 1014, in _get
    .download_blob(az_blob_key)
  File "C:\Users\venv\lib\site-packages\azure\core\tracing\decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "C:\Users\venv\lib\site-packages\azure\storage\blob\_container_client.py", line 1096, in download_blob
    return blob_client.download_blob(offset=offset, length=length, **kwargs)
  File "C:\Users\venv\lib\site-packages\azure\core\tracing\decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "C:\Users\venv\lib\site-packages\azure\storage\blob\_blob_client.py", line 848, in download_blob
    return StorageStreamDownloader(**options)
  File "C:\Users\venv\lib\site-packages\azure\storage\blob\_download.py", line 349, in __init__
    self._response = self._initial_request()
  File "C:\Users\venv\lib\site-packages\azure\storage\blob\_download.py", line 429, in _initial_request
    process_storage_error(error)
  File "C:\Users\venv\lib\site-packages\azure\storage\blob\_shared\response_handlers.py", line 177, in process_storage_error
    exec("raise error from None")   # pylint: disable=exec-used # nosec
  File "<string>", line 1, in <module>
  File "C:\Users\venv\lib\site-packages\azure\storage\blob\_download.py", line 392, in _initial_request
    **self._request_options
  File "C:\Users\venv\lib\site-packages\azure\storage\blob\_generated\operations\_blob_operations.py", line 184, in download
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "C:\Users\venv\lib\site-packages\azure\core\exceptions.py", line 105, in map_error
    raise error
**azure.core.exceptions.ResourceNotFoundError: The specified blob does not exist.**
RequestId:94ef4a60-201e-007d-7ef7-313424000000
Time:2022-03-07T07:48:06.0358361Z
ErrorCode:BlobNotFound
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:94ef4a60-201e-007d-7ef7-313424000000
Time:2022-03-07T07:48:06.0358361Z</Message></Error>
The specified blob does not exist.
RequestId:94ef4a60-201e-007d-7ef7-313424000000
Time:2022-03-07T07:48:06.0358361Z
**ErrorCode:BlobNotFound
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.**
RequestId:94ef4a60-201e-007d-7ef7-313424000000
Time:2022-03-07T07:48:06.0358361Z</Message></Error>

**Comment by austiezr** [comment]
@esfsbhagwat Thanks for raising this! We'll review and be in touch. Are you able to share any further context around your environment, configs, yaml files, etc?

**Comment by petehanssens** [comment]
I'm experiencing the same issue.

Here's my config:
`  validations_AZ_store:
    class_name: ValidationsStore
    store_backend:
      class_name: TupleAzureBlobStoreBackend
      connection_string: ${GE_RESULTS_CONNECTION_STRING}
      container: ${GE_RESULTS_CONTAINER}
      prefix: validations

  checkpoint_AZ_store:
    class_name: CheckpointStore
    store_backend:
      class_name: TupleAzureBlobStoreBackend
      connection_string: ${GE_RESULTS_CONNECTION_STRING}
      container: ${GE_RESULTS_CONTAINER}
      prefix: checkpoint

expectations_store_name: expectations_store
validations_store_name: validations_AZ_store
evaluation_parameter_store_name: evaluation_parameter_store
checkpoint_store_name: checkpoint_AZ_store`

**Comment by rdodev** [comment]
Hey @petehanssens is this still an issue?
