### ISSUE TITLE
Schema handling issues when connecting to redshift

### ISSUE THREAD

**Issue by akallai** [fivetran/great_expectations#4550]
**Describe the bug**

I'm not able to properly configure the datasource for a redshiftconnection without running into errors when using that datasource.

My configuration file looks like this:
```
redshift:
    data_connectors:
      default_runtime_data_connector_name:
        class_name: RuntimeDataConnector
        module_name: great_expectations.datasource.data_connector
        batch_identifiers:
          - default_identifier_name
      default_inferred_data_connector_name:
        class_name: InferredAssetSqlDataConnector
        include_schema_name: true
        module_name: great_expectations.datasource.data_connector
    execution_engine:
      credentials:
        host: host
        port: '5439'
        username: username
        password: password
        database: db_name
        schema_name: schema_name
        query:
          sslmode: prefer
        drivername: postgresql+psycopg2
      module_name: great_expectations.execution_engine
      class_name: SqlAlchemyExecutionEngine
    class_name: Datasource
    module_name: great_expectations.datasource
```

When running this for testing:
`context.test_yaml_config(yaml_config=example_yaml)`
Im running into this warning, but I'm able to see the data assets:
![image](https://user-images.githubusercontent.com/28675757/160114948-5fec2bf7-5e09-4a22-9418-b6e58c413a5f.png)
When trying to use the profiler to create a suite for a specific table I'm getting this error:
```
Traceback (most recent call last):
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\great_expectations\cli\cli.py", line 188, in <module>
    main()
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\great_expectations\cli\cli.py", line 184, in main
    cli()
  File "C:\Users\username\sync\Software\Anaconda\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\username\sync\Software\Anaconda\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\username\sync\Software\Anaconda\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\username\sync\Software\Anaconda\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\username\sync\Software\Anaconda\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\username\sync\Software\Anaconda\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\username\sync\Software\Anaconda\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\great_expectations\cli\suite.py", line 143, in suite_new
    batch_request=batch_request,
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\great_expectations\cli\suite.py", line 318, in _suite_new_workflow
    raise e
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\great_expectations\cli\suite.py", line 294, in _suite_new_workflow
    assume_yes=False,
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\great_expectations\cli\suite.py", line 844, in _suite_edit_workflow
    raise e
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\great_expectations\cli\suite.py", line 781, in _suite_edit_workflow
    batch_request=batch_request,
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\great_expectations\render\renderer\v3\suite_profile_notebook_renderer.py", line 40, in __init__
    expectation_suite_name=expectation_suite_name,
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\great_expectations\data_context\data_context.py", line 1854, in get_validator
    **kwargs,
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\great_expectations\core\usage_statistics\usage_statistics.py", line 300, in usage_statistics_wrapped_method
    result = func(*args, **kwargs)
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\great_expectations\data_context\data_context.py", line 1753, in get_batch_list
    return datasource.get_batch_list_from_batch_request(batch_request=batch_request)
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\great_expectations\datasource\new_datasource.py", line 195, in get_batch_list_from_batch_request
    batch_definition=batch_definition
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\great_expectations\datasource\data_connector\data_connector.py", line 111, in get_batch_data_and_metadata
    batch_spec=batch_spec
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\great_expectations\execution_engine\sqlalchemy_execution_engine.py", line 1157, in get_batch_data_and_markers
    batch_spec=batch_spec
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\great_expectations\execution_engine\sqlalchemy_execution_engine.py", line 1100, in _build_selectable_from_batch_spec
    sa.table(table_name, schema=batch_spec.get("schema_name", None))
TypeError: table() got an unexpected keyword argument 'schema'
```

**Environment (please complete the following information):**
 - Operating System: Windows
 - Great Expectations Version: 0.14.11
 - Redshift Version: PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.36433

**Additional context**
I have also tried this configuration and I'm getting the same errormessage there.
```
redshift_dev:
    data_connectors:
      default_runtime_data_connector_name:
        class_name: RuntimeDataConnector
        module_name: great_expectations.datasource.data_connector
        batch_identifiers:
          - default_identifier_name
      default_inferred_data_connector_name:
        class_name: InferredAssetSqlDataConnector
        include_schema_name: true
        module_name: great_expectations.datasource.data_connector
    execution_engine:
      connection_string: postgresql+psycopg2://username:password@host:port/db?sslmode=prefer
      module_name: great_expectations.execution_engine
      class_name: SqlAlchemyExecutionEngine
    class_name: Datasource
    module_name: great_expectations.datasource
```

**Comment by talagluck** [comment]
Hi @akallai - thanks for opening this! We will review and be in touch. Could you please share the `batch_request` you are using to create the Validator when running the Profiler?

**Comment by akallai** [comment]
Hi @talagluck - thanks for the response. 
Theese are the steps to reproduce, I'm using the CLI "v3 (Batch Request) API"

```
great_expectations suite new

How would you like to create your Expectation Suite?
    1. Manually, without interacting with a sample batch of data (default)
    2. Interactively, with a sample batch of data
    3. Automatically, using a profiler
: 3

Select a datasource
    1. redshiftR
    2. redshift_dev
: 1

You have a list of 1,160 data assets. Would you like to list them [l] or search [s]?
: l

Type [n] to see the next page or [p] for the previous. When you're ready to select an asset, enter the index.
: 3

Name the new Expectation Suite [my_schema_name.my_table_name.warning]:

Would you like to proceed? [Y/n]:
Y

```
 After this stepI'm getting the error described above. A notebook is not starting, the error is aborting the process.

However, the Expectations suite still got created.
This file got created (great_expectations/expectations/my_schema_name/my_table_name.warning):
```
{
  "data_asset_type": null,
  "expectation_suite_name": "my_schema_name.my_table_name.warning",
  "expectations": [],
  "ge_cloud_id": null,
  "meta": {
    "citations": [
      {
        "batch_request": {
          "data_asset_name": "my_schema_name.my_table_name",
          "data_connector_name": "default_inferred_data_connector_name",
          "datasource_name": "redshiftR",
          "limit": 1000
        },
        "citation_date": "2022-04-12T10:27:55.567945Z",
        "comment": "Created suite added via CLI"
      }
    ],
    "great_expectations_version": "0.14.12"
  }
}
```

**Comment by rdodev** [comment]
@akallai is this issue is still relevant? We have not been able to replicate it in our end. Have you looked at [this](https://github.com/great-expectations/great_expectations/blob/develop/tests/integration/docusaurus/connecting_to_your_data/database/redshift_python_example.py) example?
