### ISSUE TITLE
OpenLineage Action fails sending Openlineage Events

### ISSUE THREAD

**Issue by error418** [fivetran/great_expectations#4837]
**Describe the bug**

OpenLineage Action fails 

**To Reproduce**
1. Use Openlineage Action in a Checkpoint
2. Run Validation

**Expected behavior**
Openlineage Action sends a Openlineage Event when executing the action

**Environment (please complete the following information):**
 - Operating System: Linux WSL (Ubuntu)
 - Great Expectations Version: 0.15.0

**Additional context**

#### Checkpoint config

```yml
name: openlineagetest
config_version: 1.0
template_name:
module_name: great_expectations.checkpoint
class_name: Checkpoint
run_name_template: '%Y%m%d-%H%M%S-my-run-name-template'
expectation_suite_name:
batch_request: {}
action_list:
  - name: openlineage
    action:
      class_name: OpenLineageValidationAction
      module_name: openlineage.common.provider.great_expectations
      openlineage_host: ${OPENLINEAGE_URL}
      openlineage_apiKey: ${OPENLINEAGE_API_KEY}
      job_name: ge_validation # This is user-definable
      openlineage_namespace: dqm # This is user-definable
evaluation_parameters: {}
runtime_configuration: {}
validations:
  - batch_request:
      datasource_name: s3
      data_connector_name: s3_asset_connector
      data_asset_name: someasset
      data_connector_query:
        index: -1
    expectation_suite_name: openlineagetest
profilers: []
ge_cloud_id:
expectation_suite_ge_cloud_id:
```

#### Debugging observations

It seems the expectation suite meta is missing in the validation result

```
Traceback (most recent call last):
  File "/.venv/lib/python3.8/site-packages/great_expectations/validation_operators/validation_operators.py", line 449, in _run_actions
    action_result = self.actions[action["name"]].run(
  File "/.venv/lib/python3.8/site-packages/great_expectations/checkpoint/actions.py", line 72, in run
    return self._run(
  File "/.venv/lib/python3.8/site-packages/openlineage/common/provider/great_expectations/action.py", line 117, in _run
    {"great_expectations_meta": GreatExpectationsRunFacet(**validation_result_suite.meta)})
TypeError: __init__() missing 1 required positional argument: 'expectation_suite_meta'
```

if I add the metadata in `validator/validator.py`

https://github.com/great-expectations/great_expectations/blob/cc419d7ac758186854c50d3ba390a25039bd0635/great_expectations/validator/validator.py#L1956-L1964

by changing it to

```diff
                meta={
                    "great_expectations_version": ge_version,
                    "expectation_suite_name": expectation_suite_name,
+                   "expectation_suite_meta": convert_to_json_serializable(expectation_suite.meta),
                    "run_id": run_id,
                    "batch_spec": self.active_batch_spec,
                    "batch_markers": self.active_batch_markers,
                    "active_batch_definition": self.active_batch_definition,
                    "validation_time": validation_time,
                },
```

The run fails with an serialization error while sending the event to the openlineage backend

```
Error running action with name openlineage
Traceback (most recent call last):
  File "./.venv/lib/python3.8/site-packages/great_expectations/validation_operators/validation_operators.py", line 449, in _run_actions
    action_result = self.actions[action["name"]].run(
  File "./.venv/lib/python3.8/site-packages/great_expectations/checkpoint/actions.py", line 72, in run
    return self._run(
  File "./.venv/lib/python3.8/site-packages/openlineage/common/provider/great_expectations/action.py", line 142, in _run
    self.openlineage_client.emit(run_event)
  File "./.venv/lib/python3.8/site-packages/openlineage/client/client.py", line 53, in emit
    data = Serde.to_json(event)
  File "./.venv/lib/python3.8/site-packages/openlineage/client/serde.py", line 43, in to_json
    return json.dumps(cls.to_dict(obj), sort_keys=True)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type BatchDefinition is not JSON serializable
```

**Comment by talagluck** [comment]
Thanks for raising this, @error418! Tagging @rossturk who wrote the document and might have a better sense of how this should work.

**Comment by denimalpaca** [comment]
Hey @error418, this should be fixed in this [OL PR](https://github.com/OpenLineage/OpenLineage/pull/659) when it's released!

**Comment by error418** [comment]
Thanks for the pointer, @denimalpaca
