### ISSUE TITLE
Azure Blob Storage: Shared access signature (SAS) authorisation

### ISSUE THREAD

**Issue by psxmc6** [fivetran/great_expectations#4920]
Hi all,

I am intending to use Great Expectations on data that is stored in Azure Blob Storage (ASB) container using SAS token instead of access key. 

I have followed these instructions: https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/cloud/azure/spark

What I have established is that when account_url/account_key pair is specified in data_connectors part of the *.yaml configuration file (see below), verification of the new datasource as described in [step 5 of the tutorial](https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/cloud/azure/spark#5-test-your-new-datasource) succeeds. 

However, when account_url/SAS token pair is provided, I get:

 `java.lang.IllegalArgumentException: The String is not a valid Base64-encoded string.` error.

```
example_yaml = rf"""
name: my_azure_datasource
class_name: Datasource
execution_engine:
    class_name: SparkDFExecutionEngine
    azure_options:
        account_url: <mystorageaccount>.blob.core.windows.net
        credential: <SAS_TOKEN_OR_ACCOUNT_KEY>
data_connectors:
    default_runtime_data_connector_name:
        class_name: RuntimeDataConnector
        batch_identifiers:
            - default_identifier_name
    default_inferred_data_connector_name:
        class_name: InferredAssetAzureDataConnector
        azure_options:
            account_url: <mystorageaccount>.blob.core.windows.net
            credential: <SAS_TOKEN_OR_ACCOUNT_KEY>
        container: my-container
        name_starts_with: my_data
        default_regex:
            pattern: (.*)\.parquet
            group_names:
                - data_asset_name
"""
```

Furthermore, continuing with account_url/account_key pair, I tried to create an expectation suite using following commands:

```
**~$ great_expectations suite new**
Using v3 (Batch Request) API
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
22/04/21 16:36:38 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
22/04/21 16:36:39 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
22/04/21 16:36:39 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.

**How would you like to create your Expectation Suite?**
    1. Manually, without interacting with a sample batch of data (default)
    2. Interactively, with a sample batch of data
    3. Automatically, using a profiler
: 3

**A batch of data is required to edit the suite - let's help you to specify it.**

**Which data asset (accessible by data connector "default_inferred_data_connector_name") would you like to use?**
    1. somefile

Type [n] to see the next page or [p] for the previous. When you're ready to select an asset, enter the index.
: 1

Name the new Expectation Suite [somefile]: conf_test

Great Expectations will create a notebook, containing code cells that select from available columns in your dataset and
generate expectations about them to demonstrate some examples of assertions you can make about your data.

When you run this notebook, Great Expectations will store these expectations in a new Expectation Suite "exp_test" here:

  file:///home/<USER_NAME>/great_expectations/expectations/exp_test.json

Would you like to proceed? [Y/n]: Y
22/04/21 16:39:22 WARN FileStreamSink: Assume no metadata directory. Error while looking for metadata directory in the path: wasbs://my-file-system@<mystorageaccount>.blob.core.windows.net/somefile.csv.
java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.azure.NativeAzureFileSystem$Secure not found
        at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2667)
        at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3431)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
        at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
        at org.apache.spark.sql.execution.streaming.FileStreamSink$.hasMetadata(FileStreamSink.scala:53)
        at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:370)
        at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:274)
        at org.apache.spark.sql.DataFrameReader.$anonfun$load$3(DataFrameReader.scala:245)
        at scala.Option.getOrElse(Option.scala:189)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:245)
        at org.apache.spark.sql.DataFrameReader.csv(DataFrameReader.scala:571)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
        at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.azure.NativeAzureFileSystem$Secure not found
        at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2571)
        at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2665)
        ... 26 more
Traceback (most recent call last):
  File "/opt/conda/bin/great_expectations", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/great_expectations/cli/cli.py", line 184, in main
    cli()
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/great_expectations/cli/suite.py", line 143, in suite_new
    batch_request=batch_request,
  File "/opt/conda/lib/python3.7/site-packages/great_expectations/cli/suite.py", line 318, in _suite_new_workflow
    raise e
  File "/opt/conda/lib/python3.7/site-packages/great_expectations/cli/suite.py", line 294, in _suite_new_workflow
    assume_yes=False,
  File "/opt/conda/lib/python3.7/site-packages/great_expectations/cli/suite.py", line 844, in _suite_edit_workflow
    raise e
  File "/opt/conda/lib/python3.7/site-packages/great_expectations/cli/suite.py", line 781, in _suite_edit_workflow
    batch_request=batch_request,
  File "/opt/conda/lib/python3.7/site-packages/great_expectations/render/renderer/v3/suite_profile_notebook_renderer.py", line 40, in __init__
    expectation_suite_name=expectation_suite_name,
  File "/opt/conda/lib/python3.7/site-packages/great_expectations/data_context/data_context.py", line 1862, in get_validator
    **kwargs,
  File "/opt/conda/lib/python3.7/site-packages/great_expectations/core/usage_statistics/usage_statistics.py", line 287, in usage_statistics_wrapped_method
    result = func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/great_expectations/data_context/data_context.py", line 1749, in get_batch_list
    return datasource.get_batch_list_from_batch_request(batch_request=batch_request)
  File "/opt/conda/lib/python3.7/site-packages/great_expectations/datasource/new_datasource.py", line 195, in get_batch_list_from_batch_request
    batch_definition=batch_definition
  File "/opt/conda/lib/python3.7/site-packages/great_expectations/datasource/data_connector/data_connector.py", line 111, in get_batch_data_and_metadata
    batch_spec=batch_spec
  File "/opt/conda/lib/python3.7/site-packages/great_expectations/execution_engine/sparkdf_execution_engine.py", line 264, in get_batch_data_and_markers
    batch_data = reader_fn(path)
  File "/opt/conda/lib/python3.7/site-packages/pyspark/sql/readwriter.py", line 410, in csv
    return self._df(self._jreader.csv(self._spark._sc._jvm.PythonUtils.toSeq(path)))
  File "/opt/conda/lib/python3.7/site-packages/py4j/java_gateway.py", line 1322, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/opt/conda/lib/python3.7/site-packages/pyspark/sql/utils.py", line 111, in deco
    return f(*a, **kw)
  File "/opt/conda/lib/python3.7/site-packages/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling o113.csv.
: java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.azure.NativeAzureFileSystem$Secure not found
        at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2667)
        at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3431)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
        at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
        at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$1(DataSource.scala:747)
        at scala.collection.immutable.List.map(List.scala:293)
        at org.apache.spark.sql.execution.datasources.DataSource$.checkAndGlobPathIfNecessary(DataSource.scala:745)
        at org.apache.spark.sql.execution.datasources.DataSource.checkAndGlobPathIfNecessary(DataSource.scala:577)
        at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:408)
        at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:274)
        at org.apache.spark.sql.DataFrameReader.$anonfun$load$3(DataFrameReader.scala:245)
        at scala.Option.getOrElse(Option.scala:189)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:245)
        at org.apache.spark.sql.DataFrameReader.csv(DataFrameReader.scala:571)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
        at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.azure.NativeAzureFileSystem$Secure not found
        at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2571)
        at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2665)
        ... 29 more
```

Hence, I have two questions:

1. Is it possible to use SAS tokens in order to access data stored in ABS container or only account_url/account_key pair is allowed?

2. Given successful configuration of the data connector using account_url/account_key pair, what might cause problems during suite creation?

Kind regards

**Comment by psxmc6** [comment]
Hi,

I have identified that **credential** field of azure_options is being passed to spark.conf under:
`fs.azure.account.key.{storage_account_url}` key exclusively. 

To set permission using SAS token, there should be an option to set credential under:
`fs.azure.sas.{container_name}.<storageaccount>.blob.core.windows.net?<SAS_TOKEN>`

Please, see the following snippet: [sparkdf_execution_engine.py](https://github.com/great-expectations/great_expectations/blob/af0330233460c43c4daf5288ff99c8cb394503f4/great_expectations/execution_engine/sparkdf_execution_engine.py#L248)

Kind regards

**Comment by rdodev** [comment]
@psxmc6 hey given you believe you have a solution, would you mind creating a PR for it? Happy to help if you run into issues along the way.
