### ISSUE TITLE
Runtime rendering error in `parse_row_condition_string_pandas_engine` function associated with row_condition $PARAMETER parsing

### ISSUE THREAD

**Issue by mpolena** [fivetran/great_expectations#5174]
**Describe the bug**
When running the following expectation: 
` {

      "expectation_type": "expect_column_values_to_not_be_null",

      "kwargs": {

        "catch_exceptions": true,

        "column": "VALUE_NUMERIC",

        "condition_parser": "pandas",

        "result_format": {

          "result_format": "COMPLETE"

        },

        "row_condition": {

          "$PARAMETER" : "numeric_valued_items"

        }

      },

      "meta": {

        "action": "drop",

        "error_msg": "Unexpected NULL or non-numeric values in field.",

        "severity": "critical"

      }
    },`

the following **rendering runtime error** gets generated:
```Building Data Docs..
An unexpected Exception occurred during data docs rendering.  Because of this error, certain parts of data docs will not be rendered properly and/or may not appear altogether.  Please use the trace, included in this message, to diagnose and repair the underlying issue.  Detailed information follows:
        AttributeError: "'dict' object has no attribute 'replace'".  Traceback: "Traceback (most recent call last):
  File "/home/mpolena/.local/share/virtualenvs/bextract-tmwNqn9e/lib/python3.7/site-packages/great_expectations/render/renderer/content_block/content_block.py", line 109, in _render_list
    **kwargs,
  File "/home/mpolena/.local/share/virtualenvs/bextract-tmwNqn9e/lib/python3.7/site-packages/great_expectations/render/renderer/renderer.py", line 13, in inner_func
    return renderer_fn(*args, **kwargs)
  File "/home/mpolena/.local/share/virtualenvs/bextract-tmwNqn9e/lib/python3.7/site-packages/great_expectations/expectations/util.py", line 11, in inner_func
    rendered_string_template = render_func(*args, **kwargs)
  File "/home/mpolena/.local/share/virtualenvs/bextract-tmwNqn9e/lib/python3.7/site-packages/great_expectations/expectations/core/expect_column_values_to_not_be_null.py", line 204, in _prescriptive_renderer
    ) = parse_row_condition_string_pandas_engine(params["row_condition"])
  File "/home/mpolena/.local/share/virtualenvs/bextract-tmwNqn9e/lib/python3.7/site-packages/great_expectations/render/util.py", line 149, in parse_row_condition_string_pandas_engine
    condition_string.replace("&", " AND ")
AttributeError: 'dict' object has no attribute 'replace'
".
An unexpected Exception occurred during data docs rendering.  Because of this error, certain parts of data docs will not be rendered properly and/or may not appear altogether.  Please use the trace, included in this message, to diagnose and repair the underlying issue.  Detailed information follows:
        AttributeError: "'dict' object has no attribute 'replace'".  Traceback: "Traceback (most recent call last):
  File "/home/mpolena/.local/share/virtualenvs/bextract-tmwNqn9e/lib/python3.7/site-packages/great_expectations/render/renderer/content_block/content_block.py", line 109, in _render_list
    **kwargs,
  File "/home/mpolena/.local/share/virtualenvs/bextract-tmwNqn9e/lib/python3.7/site-packages/great_expectations/render/renderer/renderer.py", line 13, in inner_func
    return renderer_fn(*args, **kwargs)
  File "/home/mpolena/.local/share/virtualenvs/bextract-tmwNqn9e/lib/python3.7/site-packages/great_expectations/expectations/util.py", line 11, in inner_func
    rendered_string_template = render_func(*args, **kwargs)
  File "/home/mpolena/.local/share/virtualenvs/bextract-tmwNqn9e/lib/python3.7/site-packages/great_expectations/expectations/core/expect_column_values_to_not_be_null.py", line 204, in _prescriptive_renderer
    ) = parse_row_condition_string_pandas_engine(params["row_condition"])
  File "/home/mpolena/.local/share/virtualenvs/bextract-tmwNqn9e/lib/python3.7/site-packages/great_expectations/render/util.py", line 149, in parse_row_condition_string_pandas_engine
    condition_string.replace("&", " AND ")
AttributeError: 'dict' object has no attribute 'replace'
". ```

### To Reproduce
Steps to reproduce the behavior:
1. Run the expectation above.
2. $PARAMETER numeric_valued_items resolves to a string as follows f`{COLUMN_NAME} in {list_of_dynamically_generated_items}`
3. expectation gets evaluated correctly, however
4. During rendering the runtime error above gets generated.

**Expected behavior**
parsing/rendering for `row_condition` kwarg should be able to handle $PARAMETER configuration without generating a runtime error.

**Environment (please complete the following information):**
 - Operating System: Linux
 - Great Expectations Version: [e.g. 0.14.28]

**Additional context**
Add any other context about the problem here.

**Comment by rdodev** [comment]
Hey @mpolena taking a look here. Firstly, conditional expectations are presently in 'experimental' state, which means we suggest exercising extreme caution when using against production data. Secondly, `row_condition` should be a string value ([docs](https://docs.greatexpectations.io/docs/reference/expectations/conditional_expectations)), not an object even if it seems to be working somehow.

**Comment by rdodev** [comment]
@mpolena Another alternative to consider is to create a custom expectation. However, the failure, as is, given the configuration is working as expected.

I'm going to close this issue, please feel free to reach out if you have any other questions.
