### ISSUE TITLE
Core expectation expect_column_pair_values_to_be_equal is not implemented for SQLAlchemy datasources

### ISSUE THREAD

**Issue by Mmourato** [fivetran/great_expectations#5524]
**Description**

The core expectation `expect_column_pair_values_to_be_equal` , even though it is listed in the GE documentation as being tested for Production, for multiple SQL datasources, as per the image bellow, is not implemented.

If we go to the `sqlalchemy_dataset.py` , we can see that the expectation does not exist.

![image](https://user-images.githubusercontent.com/103369807/179505259-38a51103-da6f-430b-8bb3-42f5572b2eb5.png)

I believe this should be regarded as a bug and not feature request, since it is documented as having been tested for SQLAlchemy datasources.

**To Reproduce**
1. Create a simple asset that retrieves data from a table in an SQL datasource 
2. Create an expectation suite with the `expect_column_pair_values_to_be_equal` expectation inside
3. Run validation

**Expected behavior**
The expected is for the validation to fail with the following message:

```
Traceback (most recent call last):
File "/home/a/.local/lib/python3.6/site-packages/great_expectations/data_asset/data_asset.py", line 954, in validate
**evaluation_args
File "/home/a/.local/lib/python3.6/site-packages/great_expectations/dataset/dataset.py", line 4493, in expect_column_pair_values_to_be_equal
raise NotImplementedError
NotImplementedError
```

**Environment**
 - Operating System: Linux
 - Great Expectations Version: 0.13.48 ( but is expected to be the same for all versions)

**Comment by Mmourato** [comment]
Apologies, this behavior only happens for version V2 and the non compliance is well documented here: https://legacy.docs.greatexpectations.io/en/latest/reference/core_concepts/expectations/implemented_expectations.html
Closing the issue.
