### ISSUE TITLE
Rendering crashes for `expect_column_values_to_be_in_type_list` `type_list=None`

### ISSUE THREAD

**Issue by abegong** [fivetran/great_expectations#561]
DescriptiveOverviewSectionRenderer._get_column_types crashes when one of the EVRs is:

```
{'success': True, 'result': {'observed_value': 'DATE'}, 'exception_info': {'raised_exception': False, 'exception_message': None, 'exception_traceback': None}, 'expectation_config': {'expectation_type': 'expect_column_values_to_be_in_type_list', 'kwargs': {'column': 'release_date', 'type_list': None, 'result_format': 'SUMMARY'}, 'meta': {'BasicDatasetProfiler': {'confidence': 'very low'}}}}
```

**Comment by talagluck** [comment]
Previous error message was:
```
Traceback (most recent call last):
  File "/Users/talgluck/Documents/movie_db/venv/bin/great_expectations", line 11, in <module>
    load_entry_point('great-expectations', 'console_scripts', 'great_expectations')()
  File "/Users/talgluck/Documents/ge_main/great_expectations/great_expectations/cli/cli.py", line 300, in main
    cli()
  File "/Users/talgluck/Documents/movie_db/venv/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/talgluck/Documents/movie_db/venv/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/talgluck/Documents/movie_db/venv/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/talgluck/Documents/movie_db/venv/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/talgluck/Documents/movie_db/venv/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/talgluck/Documents/ge_main/great_expectations/great_expectations/cli/cli.py", line 271, in documentation
    build_documentation(context)
  File "/Users/talgluck/Documents/ge_main/great_expectations/great_expectations/cli/datasource.py", line 311, in build_documentation
    context.render_full_static_site()
  File "/Users/talgluck/Documents/ge_main/great_expectations/great_expectations/data_context/data_context.py", line 1515, in render_full_static_site
    model = DescriptivePageRenderer.render(validation)
  File "/Users/talgluck/Documents/ge_main/great_expectations/great_expectations/render/renderer/page_renderer.py", line 116, in render
    column_types = DescriptiveOverviewSectionRenderer._get_column_types(validation_results)
  File "/Users/talgluck/Documents/ge_main/great_expectations/great_expectations/render/renderer/other_section_renderer.py", line 261, in _get_column_types
    expected_types = set(evr["expectation_config"]["kwargs"]["type_list"])
TypeError: 'NoneType' object is not iterable
```
