### ISSUE TITLE
Error while running data quality rules against ~45GB of parquet data in S3

### ISSUE THREAD

**Issue by shakti-garg** [fivetran/great_expectations#5613]
**Describe the bug**
Got errors while executing data quality rules against ~45GB of parquet data in S3.
1. On first run, it gave below error when i ran checkpoint

```
expect_column_proportion_of_unique_values_to_be_between raised an exception:
Error while sending or receiving

Show exception traceback...
Traceback (most recent call last):
File "/usr/lib/spark/python/pyspark/sql/dataframe.py", line 694, in collect
sock_info = self._jdf.collectToPython()
File "/usr/lib/spark/python/lib/py4j-0.10.9.3-src.zip/py4j/java_gateway.py", line 1322, in __call__
answer, self.gateway_client, self.target_id, self.name)
File "/usr/lib/spark/python/pyspark/sql/utils.py", line 111, in deco
return f(*a, **kw)
File "/usr/lib/spark/python/lib/py4j-0.10.9.3-src.zip/py4j/protocol.py", line 336, in get_return_value
format(target_id, ".", name))
py4j.protocol.Py4JError: An error occurred while calling o2577.collectToPython

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/lib/spark/python/lib/py4j-0.10.9.3-src.zip/py4j/clientserver.py", line 475, in send_command
answer = smart_decode(self.stream.readline()[:-1])
File "/usr/lib64/python3.7/socket.py", line 589, in readinto
return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/hadoop/.local/lib/python3.7/site-packages/great_expectations/execution_engine/execution_engine.py", line 380, in resolve_metrics
**metric_provider_kwargs
File "/home/hadoop/.local/lib/python3.7/site-packages/great_expectations/expectations/metrics/metric_provider.py", line 34, in inner_func
return metric_fn(*args, **kwargs)
File "/home/hadoop/.local/lib/python3.7/site-packages/great_expectations/expectations/metrics/column_aggregate_metrics/column_value_counts.py", line 153, in _spark
value_counts = value_counts.collect()
File "/usr/lib/spark/python/pyspark/sql/dataframe.py", line 694, in collect
sock_info = self._jdf.collectToPython()
File "/usr/lib/spark/python/pyspark/traceback_utils.py", line 78, in __exit__
self._context._jsc.setCallSite(None)
File "/usr/lib/spark/python/lib/py4j-0.10.9.3-src.zip/py4j/java_gateway.py", line 1320, in __call__
answer = self.gateway_client.send_command(command)
File "/usr/lib/spark/python/lib/py4j-0.10.9.3-src.zip/py4j/java_gateway.py", line 1036, in send_command
connection = self._get_connection()
File "/usr/lib/spark/python/lib/py4j-0.10.9.3-src.zip/py4j/clientserver.py", line 281, in _get_connection
connection = self._create_new_connection()
File "/usr/lib/spark/python/lib/py4j-0.10.9.3-src.zip/py4j/clientserver.py", line 288, in _create_new_connection
connection.connect_to_java_server()
File "/usr/lib/spark/python/lib/py4j-0.10.9.3-src.zip/py4j/clientserver.py", line 407, in connect_to_java_server
self._authenticate_connection()
File "/usr/lib/spark/python/lib/py4j-0.10.9.3-src.zip/py4j/clientserver.py", line 423, in _authenticate_connection
answer = self.send_command(cmd)
File "/usr/lib/spark/python/lib/py4j-0.10.9.3-src.zip/py4j/clientserver.py", line 504, in send_command
"Error while sending or receiving", e, proto.ERROR_ON_RECEIVE)
py4j.protocol.Py4JNetworkError: Error while sending or receiving

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/hadoop/.local/lib/python3.7/site-packages/great_expectations/validator/validator.py", line 1298, in resolve_validation_graph
runtime_configuration=runtime_configuration,
File "/home/hadoop/.local/lib/python3.7/site-packages/great_expectations/validator/validator.py", line 2222, in _resolve_metrics
runtime_configuration=runtime_configuration,
File "/home/hadoop/.local/lib/python3.7/site-packages/great_expectations/execution_engine/execution_engine.py", line 384, in resolve_metrics
message=str(e), failed_metrics=(metric_to_resolve,)
great_expectations.exceptions.exceptions.MetricResolutionError: Error while sending or receiving
```

2. This got fixed once i increased the driver's memory to 8 GB from default 2 GB.
3. But got below pandas error in generated data-docs
```
fraction of unique values must be exactly 0.01333725409293432.

expect_column_proportion_of_unique_values_to_be_between raised an exception:
Unable to allocate 204. MiB for an array with shape (13357955,) and data type complex128

Show exception traceback...
Traceback (most recent call last):
File "/home/hadoop/.local/lib/python3.7/site-packages/great_expectations/execution_engine/execution_engine.py", line 380, in resolve_metrics
**metric_provider_kwargs
File "/home/hadoop/.local/lib/python3.7/site-packages/great_expectations/expectations/metrics/metric_provider.py", line 34, in inner_func
return metric_fn(*args, **kwargs)
File "/home/hadoop/.local/lib/python3.7/site-packages/great_expectations/expectations/metrics/column_aggregate_metrics/column_value_counts.py", line 157, in _spark
name="count",
File "/home/hadoop/.local/lib/python3.7/site-packages/pandas/core/series.py", line 439, in __init__
data = sanitize_array(data, index, dtype, copy)
File "/home/hadoop/.local/lib/python3.7/site-packages/pandas/core/construction.py", line 571, in sanitize_array
subarr = maybe_convert_platform(data)
File "/home/hadoop/.local/lib/python3.7/site-packages/pandas/core/dtypes/cast.py", line 126, in maybe_convert_platform
arr = lib.maybe_convert_objects(arr)
File "pandas/_libs/lib.pyx", line 2447, in pandas._libs.lib.maybe_convert_objects
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 204. MiB for an array with shape (13357955,) and data type complex128

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/hadoop/.local/lib/python3.7/site-packages/great_expectations/validator/validator.py", line 1298, in resolve_validation_graph
runtime_configuration=runtime_configuration,
File "/home/hadoop/.local/lib/python3.7/site-packages/great_expectations/validator/validator.py", line 2222, in _resolve_metrics
runtime_configuration=runtime_configuration,
File "/home/hadoop/.local/lib/python3.7/site-packages/great_expectations/execution_engine/execution_engine.py", line 384, in resolve_metrics
message=str(e), failed_metrics=(metric_to_resolve,)
great_expectations.exceptions.exceptions.MetricResolutionError: Unable to allocate 204. MiB for an array with shape (13357955,) and data type complex128
```

while the backend gave below error:
```
An unexpected Exception occurred during data docs rendering.  Because of this error, certain parts of data docs will not be rendered properly and/or may not appear altogether.  Please use the trace, included in this message, to diagnose and repair the underlying issue.  Detailed information follows:
                KeyError: "'observed_value'".  Traceback: "Traceback (most recent call last):
  File "/home/hadoop/.local/lib/python3.7/site-packages/great_expectations/render/renderer/site_builder.py", line 464, in build
    rendered_content = self.renderer_class.render(resource)
  File "/home/hadoop/.local/lib/python3.7/site-packages/great_expectations/render/renderer/page_renderer.py", line 128, in render
    columns,
  File "/home/hadoop/.local/lib/python3.7/site-packages/great_expectations/render/renderer/page_renderer.py", line 247, in _collect_rendered_document_content_sections
    ordered_columns = Renderer._get_column_list_from_evrs(validation_results)
  File "/home/hadoop/.local/lib/python3.7/site-packages/great_expectations/render/renderer/renderer.py", line 88, in _get_column_list_from_evrs
    "observed_value"
KeyError: 'observed_value'
```

**To Reproduce**
1. Open pyspark session
2. Configure data source to S3 and execution engine as spark
3. Batch is ~45 GB of parquet data
5. Expectations are simple with 2 default table ones(column names and row counts) and default generated rules on a single primary column.
6. create checkpoint and run

**Expected behavior**
The expectations shouldn't give error.

**Environment (please complete the following information):**
 - pyspark session on EMR
 - emr-6.7.0; spark 3.2.1

**Comment by AFineDayFor** [comment]
Howdy @shakti-garg 👋 thanks for bringing this to us 🙇 

We'll bring it up with the team, in conjunction with #5614 🔬

**Comment by AFineDayFor** [comment]
Howdy again. It's in our backlog; we don't have any further updates at this time, but do keep an eye out.
