### ISSUE TITLE
Circular import when trying to import BaseDataContext

### ISSUE THREAD

**Issue by stfines-clgx** [fivetran/great_expectations#5761]
**Describe the bug**

Code is not able to compile when importing BaseDataContext using 0.15.17

**To Reproduce**

Use this code:
```
from abc import abstractmethod

from pyhocon import ConfigFactory
from great_expectations.data_context.data_context.base_data_context import BaseDataContext
from great_expectations.core.util import *
from great_expectations.core.batch import BatchRequest
from great_expectations.core.expectation_suite import ExpectationSuite
from great_expectations.validator.validator import Validator
from great_expectations.profile.user_configurable_profiler import *


class BaseValidateDataset:

    def __init__(self, config:ConfigFactory):
        self.config = config

    @abstractmethod
    def _make_test_suite_name(self, fips: str) -> str:
        pass

    @abstractmethod
    def get_datasource(self, fips: str) -> BatchRequest:
        pass

    def create_expectation_suite(self, fips: str) -> ExpectationSuite:

        expectations = self.context.create_expectation_suite(
            expectation_suite_name=self._make_test_suite_name(fips), overwrite_existing=True
        )
        return expectations

    def validate(self, fips: str, batch_request: BatchRequest) -> Validator:

        validator = self.context.get_validator(
            batch_request=batch_request, expectation_suite_name=self._make_test_suite_name(fips)
        )

        return validator

    def profile(self, batch_request:BatchRequest, validator: Validator):
        ignored_columns = []
        not_null_only = True
        table_expectations_only = False
        value_set_threshold = "unique"

        profiler = UserConfigurableProfiler(
            profile_dataset=validator,
            ignored_columns=ignored_columns,
            not_null_only=not_null_only,
            table_expectations_only=table_expectations_only,
            value_set_threshold=value_set_threshold)

        suite = profiler.build_suite()
        return suite


class EnrichmentDataValidation(BaseValidateDataset):

    ENRICHMENT_EXPECTATION_PREFIX = "enrichment_expectations_"

    def __init__(self, config: ConfigFactory, context: BaseDataContext):
        self.context = context
        super().__init__(config)

    def get_datasource(self, fips: str) -> BatchRequest:
        table_name = f"enriched_data_{fips}"
        batch_request = BatchRequest(
            datasource_name="dataprep_datasource",
            data_connector_name="dataprep_inferred_data_connector",
            data_asset_name=table_name,  # this is the name of the table you want to retrieve
        )
        return batch_request

    def _make_test_suite_name(self, fips: str) -> str:
        return f"{self.ENRICHMENT_EXPECTATION_PREFIX}_{fips}"


```

**Expected behavior**
The code compiles.

**Environment (please complete the following information):**
 - Operating System: [e.g. Linux, MacOS, Windows]
 MacOs 12.0 
 - Great Expectations Version: [e.g. 0.13.2]
 - 0.15.17
 
Python 3.9.13

**Additional context**
STACK TRACE:

```
/Users/stfines/workspace/modelx/data_qa_process/.venv/bin/python /Users/stfines/workspace/modelx/data_qa_process/app/__main__.py
Traceback (most recent call last):
  File "/Users/stfines/workspace/modelx/data_qa_process/app/__main__.py", line 2, in <module>
    from great_expectations.data_context.data_context.base_data_context import BaseDataContext
  File "/Users/stfines/workspace/modelx/data_qa_process/.venv/lib/python3.9/site-packages/great_expectations/__init__.py", line 7, in <module>
    from great_expectations.data_context import DataContext
  File "/Users/stfines/workspace/modelx/data_qa_process/.venv/lib/python3.9/site-packages/great_expectations/data_context/__init__.py", line 1, in <module>
    from great_expectations.data_context.data_context import (
  File "/Users/stfines/workspace/modelx/data_qa_process/.venv/lib/python3.9/site-packages/great_expectations/data_context/data_context/__init__.py", line 1, in <module>
    from great_expectations.data_context.data_context.abstract_data_context import (
  File "/Users/stfines/workspace/modelx/data_qa_process/.venv/lib/python3.9/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 29, in <module>
    from great_expectations.core import ExpectationSuite
  File "/Users/stfines/workspace/modelx/data_qa_process/.venv/lib/python3.9/site-packages/great_expectations/core/__init__.py", line 3, in <module>
    from .expectation_suite import (
  File "/Users/stfines/workspace/modelx/data_qa_process/.venv/lib/python3.9/site-packages/great_expectations/core/expectation_suite.py", line 11, in <module>
    from great_expectations.core.evaluation_parameters import (
  File "/Users/stfines/workspace/modelx/data_qa_process/.venv/lib/python3.9/site-packages/great_expectations/core/evaluation_parameters.py", line 27, in <module>
    from great_expectations.core.util import convert_to_json_serializable
  File "/Users/stfines/workspace/modelx/data_qa_process/.venv/lib/python3.9/site-packages/great_expectations/core/util.py", line 17, in <module>
    from IPython import get_ipython
  File "/Users/stfines/workspace/modelx/data_qa_process/.venv/lib/python3.9/site-packages/IPython/__init__.py", line 53, in <module>
    from .terminal.embed import embed
  File "/Users/stfines/workspace/modelx/data_qa_process/.venv/lib/python3.9/site-packages/IPython/terminal/embed.py", line 17, in <module>
    from IPython.terminal.ipapp import load_default_config
  File "/Users/stfines/workspace/modelx/data_qa_process/.venv/lib/python3.9/site-packages/IPython/terminal/ipapp.py", line 29, in <module>
    from IPython.core.magics import (
  File "/Users/stfines/workspace/modelx/data_qa_process/.venv/lib/python3.9/site-packages/IPython/core/magics/__init__.py", line 21, in <module>
    from .execution import ExecutionMagics
  File "/Users/stfines/workspace/modelx/data_qa_process/.venv/lib/python3.9/site-packages/IPython/core/magics/execution.py", line 11, in <module>
    import cProfile as profile
  File "/usr/local/Cellar/python@3.9/3.9.13_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/cProfile.py", line 10, in <module>
    import profile as _pyprofile
  File "/Users/stfines/workspace/modelx/data_qa_process/app/profile/__init__.py", line 1, in <module>
    from app.profile.base_validate_dataset import *
  File "/Users/stfines/workspace/modelx/data_qa_process/app/profile/__init__.py", line 1, in <module>
    from app.profile.base_validate_dataset import *
  File "/Users/stfines/workspace/modelx/data_qa_process/app/profile/base_validate_dataset.py", line 4, in <module>
    from great_expectations.data_context.data_context.base_data_context import BaseDataContext
  File "/Users/stfines/workspace/modelx/data_qa_process/.venv/lib/python3.9/site-packages/great_expectations/data_context/data_context/base_data_context.py", line 15, in <module>
    from great_expectations.core.config_peer import ConfigPeer
  File "/Users/stfines/workspace/modelx/data_qa_process/.venv/lib/python3.9/site-packages/great_expectations/core/config_peer.py", line 6, in <module>
    from great_expectations.data_context.types.base import BaseYamlConfig
  File "/Users/stfines/workspace/modelx/data_qa_process/.venv/lib/python3.9/site-packages/great_expectations/data_context/types/base.py", line 16, in <module>
    from great_expectations.core.batch import BatchRequestBase, get_batch_request_as_dict
  File "/Users/stfines/workspace/modelx/data_qa_process/.venv/lib/python3.9/site-packages/great_expectations/core/batch.py", line 8, in <module>
    from great_expectations.core.util import convert_to_json_serializable
ImportError: cannot import name 'convert_to_json_serializable' from partially initialized module 'great_expectations.core.util' (most likely due to a circular import) (/Users/stfines/workspace/modelx/data_qa_process/.venv/lib/python3.9/site-packages/great_expectations/core/util.py)

```

**Comment by stfines-clgx** [comment]
A secondary issue here is why is it including the IPython magicks when this is not IPython code?

**Comment by rdodev** [comment]
hey @stfines-clgx 👋 

Thanks for issue report. Going to discuss it with the team.

**Comment by rdodev** [comment]
@stfines-clgx we aren't able to replicate the issue. We tried importing 

```
from abc import abstractmethod

from pyhocon import ConfigFactory
from great_expectations.data_context.data_context.base_data_context import BaseDataContext
from great_expectations.core.util import *
from great_expectations.core.batch import BatchRequest
from great_expectations.core.expectation_suite import ExpectationSuite
from great_expectations.validator.validator import Validator
from great_expectations.profile.user_configurable_profiler import *
```

And saw no errors. Is there anything in your environ that might be amiss here?

**Comment by rdodev** [comment]
Closing as we're unable to replicate.

**Comment by stfines-clgx** [comment]
I've been able to replicate it 3 times on 3 different machines all using poetry to do the install- each time they give me an import error related to 0.15.17 and IPython magicks (which I don't understand why they would be imported for a non-notebook use; unless by design you are saying you don't want production use)

**Comment by rdodev** [comment]
@stfines-clgx the core utils module contains IPython functions and code. Can you try tree-shaking your imports from that module (i.e. not `*`)? For reference 3 of us tried to replicate in two different OS, none got the circular reference error. So perhaps there is something in your environ/setup that's having issues with the code in `utils`.
