### ISSUE TITLE
Renderer Warnings

### ISSUE THREAD

**Issue by shivankitsharma** [fivetran/great_expectations#5790]
Getting multiple warnings with the renderer

`An unexpected Exception occurred during data docs rendering.  Because of this error, certain parts of data docs will not be rendered properly and/or may not appear altogether.  Please use the trace, included in this message, to diagnose and repair the underlying issue.  Detailed information follows:
                ValueError: "Unknown format code 'f' for object of type 'str'".  Traceback: "Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-65296af0-9f23-4514-a77d-834d1ee7333b/lib/python3.9/site-packages/great_expectations/render/renderer/column_section_renderer.py", line 109, in render
    getattr(self, content_block_function_name)(evrs)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-65296af0-9f23-4514-a77d-834d1ee7333b/lib/python3.9/site-packages/great_expectations/render/renderer/column_section_renderer.py", line 316, in _render_stats_table
    table_rows.append(renderer_impl(result=evr))
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-65296af0-9f23-4514-a77d-834d1ee7333b/lib/python3.9/site-packages/great_expectations/render/renderer/renderer.py", line 14, in inner_func
    return renderer_fn(*args, **kwargs)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-65296af0-9f23-4514-a77d-834d1ee7333b/lib/python3.9/site-packages/great_expectations/expectations/core/expect_column_min_to_be_between.py", line 400, in _descriptive_stats_table_min_row_renderer
    f"{result.result['observed_value']:.2f}",
ValueError: Unknown format code 'f' for object of type 'str'
".
An unexpected Exception occurred during data docs rendering.  Because of this error, certain parts of data docs will not be rendered properly and/or may not appear altogether.  Please use the trace, included in this message, to diagnose and repair the underlying issue.  Detailed information follows:
                ValueError: "Unknown format code 'f' for object of type 'str'".  Traceback: "Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-65296af0-9f23-4514-a77d-834d1ee7333b/lib/python3.9/site-packages/great_expectations/render/renderer/column_section_renderer.py", line 109, in render
    getattr(self, content_block_function_name)(evrs)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-65296af0-9f23-4514-a77d-834d1ee7333b/lib/python3.9/site-packages/great_expectations/render/renderer/column_section_renderer.py", line 316, in _render_stats_table
    table_rows.append(renderer_impl(result=evr))
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-65296af0-9f23-4514-a77d-834d1ee7333b/lib/python3.9/site-packages/great_expectations/render/renderer/renderer.py", line 14, in inner_func
    return renderer_fn(*args, **kwargs)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-65296af0-9f23-4514-a77d-834d1ee7333b/lib/python3.9/site-packages/great_expectations/expectations/core/expect_column_min_to_be_between.py", line 400, in _descriptive_stats_table_min_row_renderer
    f"{result.result['observed_value']:.2f}",
ValueError: Unknown format code 'f' for object of type 'str'
".
An unexpected Exception occurred during data docs rendering.  Because of this error, certain parts of data docs will not be rendered properly and/or may not appear altogether.  Please use the trace, included in this message, to diagnose and repair the underlying issue.  Detailed information follows:
                ValueError: "Unknown format code 'f' for object of type 'str'".  Traceback: "Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-65296af0-9f23-4514-a77d-834d1ee7333b/lib/python3.9/site-packages/great_expectations/render/renderer/column_section_renderer.py", line 109, in render
    getattr(self, content_block_function_name)(evrs)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-65296af0-9f23-4514-a77d-834d1ee7333b/lib/python3.9/site-packages/great_expectations/render/renderer/column_section_renderer.py", line 316, in _render_stats_table
    table_rows.append(renderer_impl(result=evr))
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-65296af0-9f23-4514-a77d-834d1ee7333b/lib/python3.9/site-packages/great_expectations/render/renderer/renderer.py", line 14, in inner_func
    return renderer_fn(*args, **kwargs)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-65296af0-9f23-4514-a77d-834d1ee7333b/lib/python3.9/site-packages/great_expectations/expectations/core/expect_column_min_to_be_between.py", line 400, in _descriptive_stats_table_min_row_renderer
    f"{result.result['observed_value']:.2f}",
ValueError: Unknown format code 'f' for object of type 'str'
".
An unexpected Exception occurred during data docs rendering.  Because of this error, certain parts of data docs will not be rendered properly and/or may not appear altogether.  Please use the trace, included in this message, to diagnose and repair the underlying issue.  Detailed information follows:
                ValueError: "Unknown format code 'f' for object of type 'str'".  Traceback: "Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-65296af0-9f23-4514-a77d-834d1ee7333b/lib/python3.9/site-packages/great_expectations/render/renderer/column_section_renderer.py", line 109, in render
    getattr(self, content_block_function_name)(evrs)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-65296af0-9f23-4514-a77d-834d1ee7333b/lib/python3.9/site-packages/great_expectations/render/renderer/column_section_renderer.py", line 316, in _render_stats_table
    table_rows.append(renderer_impl(result=evr))
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-65296af0-9f23-4514-a77d-834d1ee7333b/lib/python3.9/site-packages/great_expectations/render/renderer/renderer.py", line 14, in inner_func
    return renderer_fn(*args, **kwargs)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-65296af0-9f23-4514-a77d-834d1ee7333b/lib/python3.9/site-packages/great_expectations/expectations/core/expect_column_min_to_be_between.py", line 400, in _descriptive_stats_table_min_row_renderer
    f"{result.result['observed_value']:.2f}",
ValueError: Unknown format code 'f' for object of type 'str'
".
An unexpected Exception occurred during data docs rendering.  Because of this error, certain parts of data docs will not be rendered properly and/or may not appear altogether.  Please use the trace, included in this message, to diagnose and repair the underlying issue.  Detailed information follows:
                ValueError: "Unknown format code 'f' for object of type 'str'".  Traceback: "Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-65296af0-9f23-4514-a77d-834d1ee7333b/lib/python3.9/site-packages/great_expectations/render/renderer/column_section_renderer.py", line 109, in render
    getattr(self, content_block_function_name)(evrs)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-65296af0-9f23-4514-a77d-834d1ee7333b/lib/python3.9/site-packages/great_expectations/render/renderer/column_section_renderer.py", line 316, in _render_stats_table
    table_rows.append(renderer_impl(result=evr))
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-65296af0-9f23-4514-a77d-834d1ee7333b/lib/python3.9/site-packages/great_expectations/render/renderer/renderer.py", line 14, in inner_func
    return renderer_fn(*args, **kwargs)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-65296af0-9f23-4514-a77d-834d1ee7333b/lib/python3.9/site-packages/great_expectations/expectations/core/expect_column_min_to_be_between.py", line 400, in _descriptive_stats_table_min_row_renderer
    f"{result.result['observed_value']:.2f}",
ValueError: Unknown format code 'f' for object of type 'str'
".
An unexpected Exception occurred during data docs rendering.  Because of this error, certain parts of data docs will not be rendered properly and/or may not appear altogether.  Please use the trace, included in this message, to diagnose and repair the underlying issue.  Detailed information follows:
                ValueError: "Unknown format code 'f' for object of type 'str'".  Traceback: "Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-65296af0-9f23-4514-a77d-834d1ee7333b/lib/python3.9/site-packages/great_expectations/render/renderer/column_section_renderer.py", line 109, in render
    getattr(self, content_block_function_name)(evrs)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-65296af0-9f23-4514-a77d-834d1ee7333b/lib/python3.9/site-packages/great_expectations/render/renderer/column_section_renderer.py", line 316, in _render_stats_table
    table_rows.append(renderer_impl(result=evr))
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-65296af0-9f23-4514-a77d-834d1ee7333b/lib/python3.9/site-packages/great_expectations/render/renderer/renderer.py", line 14, in inner_func
    return renderer_fn(*args, **kwargs)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-65296af0-9f23-4514-a77d-834d1ee7333b/lib/python3.9/site-packages/great_expectations/expectations/core/expect_column_min_to_be_between.py", line 400, in _descriptive_stats_table_min_row_renderer
    f"{result.result['observed_value']:.2f}",
ValueError: Unknown format code 'f' for object of type 'str'`

**Comment by talagluck** [comment]
Hi @shivankitsharma - thank you for raising this. Could you please supply some background information? What was the code and configuration that lead to this warning? What version of Great Expectations are you running?

**Comment by shivankitsharma** [comment]
This tends to come when working with a datetime column. I think the reason is that python introduced f strings in version 3.6 and the great expectations code is unable to deal with .2f  

A quick patch to upgrade the code to newer versions of python with upgraded f string handling will fix it

https://stackoverflow.com/questions/52752654/unknown-format-code-f-for-object-of-type-str-folium
