### ISSUE TITLE
AWS Credentials error when building a Local Docs site

### ISSUE THREAD

**Issue by klashe1977** [fivetran/great_expectations#5899]
**Describe the bug**
Issuing the CLI command "great_expectations -v docs build --site-name local_site" (which is pointed to the local filesystem) fails when there is another data_doc site declared with class "TupleS3StoreBackend", stating there is no AWS Credentials entered.

**To Reproduce**
1. Modify your ge.yml data_docs_sites block to include two stores, one local and one S3.
```data_docs_sites:
 https://docs.greatexpectations.io/en/latest/reference/core_concepts/data_docs.html
  local_site:
    class_name: SiteBuilder
    show_how_to_buttons: true
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/data_docs/local_site/
    site_index_builder:
      class_name: DefaultSiteIndexBuilder
  s3_site:  
    class_name: SiteBuilder
    store_backend:
      class_name: TupleS3StoreBackend
      bucket: 'great-expectations-output'
      prefix: 'site_builder/data_docs/'
    site_index_builder:
      class_name: DefaultSiteIndexBuilder
      show_cta_footer: true
```
3. Issue command `great_expectations -v docs build --site-name local_site` from CLI
4. Command will fail if you have not entered in AWS Credentials
```Using v3 (Batch Request) API
Searching for config file /home/dtrivedi/Development/great-expectations-0.15.20/great_expectations (0 layer deep)
Searching for config file /home/dtrivedi/Development/great-expectations-0.15.20 (1 layer deep)
Found config file at /home/dtrivedi/Development/great-expectations-0.15.20/great_expectations/great_expectations.yml
Using project config: /home/dtrivedi/Development/great-expectations-0.15.20/great_expectations/great_expectations.yml
Traceback (most recent call last):
  File "/home/dtrivedi/Development/great-expectations-0.15.20/testenv/bin/great_expectations", line 8, in <module>
    sys.exit(main())
  File "/home/dtrivedi/Development/great-expectations-0.15.20/testenv/lib/python3.8/site-packages/great_expectations/cli/cli.py", line 190, in main
    cli()
  File "/home/dtrivedi/Development/great-expectations-0.15.20/testenv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/dtrivedi/Development/great-expectations-0.15.20/testenv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/dtrivedi/Development/great-expectations-0.15.20/testenv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dtrivedi/Development/great-expectations-0.15.20/testenv/lib/python3.8/site-packages/click/core.py", line 1654, in invoke
    super().invoke(ctx)
  File "/home/dtrivedi/Development/great-expectations-0.15.20/testenv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dtrivedi/Development/great-expectations-0.15.20/testenv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/dtrivedi/Development/great-expectations-0.15.20/testenv/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/dtrivedi/Development/great-expectations-0.15.20/testenv/lib/python3.8/site-packages/great_expectations/cli/docs.py", line 18, in docs
    ctx.obj.data_context = ctx.obj.get_data_context_from_config_file()
  File "/home/dtrivedi/Development/great-expectations-0.15.20/testenv/lib/python3.8/site-packages/great_expectations/cli/cli.py", line 42, in get_data_context_from_config_file
    context: DataContext = toolkit.load_data_context_with_error_handling(
  File "/home/dtrivedi/Development/great-expectations-0.15.20/testenv/lib/python3.8/site-packages/great_expectations/cli/toolkit.py", line 396, in load_data_context_with_error_handling
    context = DataContext(context_root_dir=directory)
  File "/home/dtrivedi/Development/great-expectations-0.15.20/testenv/lib/python3.8/site-packages/great_expectations/data_context/data_context/data_context.py", line 359, in __init__
    super().__init__(
  File "/home/dtrivedi/Development/great-expectations-0.15.20/testenv/lib/python3.8/site-packages/great_expectations/core/usage_statistics/usage_statistics.py", line 294, in usage_statistics_wrapped_method
    result = func(*args, **kwargs)
  File "/home/dtrivedi/Development/great-expectations-0.15.20/testenv/lib/python3.8/site-packages/great_expectations/data_context/data_context/base_data_context.py", line 309, in __init__
    self._data_context = FileDataContext(
  File "/home/dtrivedi/Development/great-expectations-0.15.20/testenv/lib/python3.8/site-packages/great_expectations/data_context/data_context/file_data_context.py", line 57, in __init__
    super().__init__(runtime_environment=runtime_environment)
  File "/home/dtrivedi/Development/great-expectations-0.15.20/testenv/lib/python3.8/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 180, in __init__
    self._init_stores(self.project_config_with_variables_substituted.stores)
  File "/home/dtrivedi/Development/great-expectations-0.15.20/testenv/lib/python3.8/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 272, in project_config_with_variables_substituted
    return self.get_config_with_variables_substituted()
  File "/home/dtrivedi/Development/great-expectations-0.15.20/testenv/lib/python3.8/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 514, in get_config_with_variables_substituted
    **substitute_all_config_variables(
  File "/home/dtrivedi/Development/great-expectations-0.15.20/testenv/lib/python3.8/site-packages/great_expectations/data_context/util.py", line 466, in substitute_all_config_variables
    return {
  File "/home/dtrivedi/Development/great-expectations-0.15.20/testenv/lib/python3.8/site-packages/great_expectations/data_context/util.py", line 467, in <dictcomp>
    k: substitute_all_config_variables(v, replace_variables_dict)
  File "/home/dtrivedi/Development/great-expectations-0.15.20/testenv/lib/python3.8/site-packages/great_expectations/data_context/util.py", line 466, in substitute_all_config_variables
    return {
  File "/home/dtrivedi/Development/great-expectations-0.15.20/testenv/lib/python3.8/site-packages/great_expectations/data_context/util.py", line 467, in <dictcomp>
    k: substitute_all_config_variables(v, replace_variables_dict)
  File "/home/dtrivedi/Development/great-expectations-0.15.20/testenv/lib/python3.8/site-packages/great_expectations/data_context/util.py", line 466, in substitute_all_config_variables
    return {
  File "/home/dtrivedi/Development/great-expectations-0.15.20/testenv/lib/python3.8/site-packages/great_expectations/data_context/util.py", line 467, in <dictcomp>
    k: substitute_all_config_variables(v, replace_variables_dict)
  File "/home/dtrivedi/Development/great-expectations-0.15.20/testenv/lib/python3.8/site-packages/great_expectations/data_context/util.py", line 466, in substitute_all_config_variables
    return {
  File "/home/dtrivedi/Development/great-expectations-0.15.20/testenv/lib/python3.8/site-packages/great_expectations/data_context/util.py", line 467, in <dictcomp>
    k: substitute_all_config_variables(v, replace_variables_dict)
  File "/home/dtrivedi/Development/great-expectations-0.15.20/testenv/lib/python3.8/site-packages/great_expectations/data_context/util.py", line 466, in substitute_all_config_variables
    return {
  File "/home/dtrivedi/Development/great-expectations-0.15.20/testenv/lib/python3.8/site-packages/great_expectations/data_context/util.py", line 467, in <dictcomp>
    k: substitute_all_config_variables(v, replace_variables_dict)
  File "/home/dtrivedi/Development/great-expectations-0.15.20/testenv/lib/python3.8/site-packages/great_expectations/data_context/util.py", line 474, in substitute_all_config_variables
    return substitute_config_variable(
  File "/home/dtrivedi/Development/great-expectations-0.15.20/testenv/lib/python3.8/site-packages/great_expectations/data_context/util.py", line 233, in substitute_config_variable
    template_str = substitute_value_from_secret_store(template_str)
  File "/home/dtrivedi/Development/great-expectations-0.15.20/testenv/lib/python3.8/site-packages/great_expectations/data_context/util.py", line 264, in substitute_value_from_secret_store
    return substitute_value_from_aws_secrets_manager(value)
  File "/home/dtrivedi/Development/great-expectations-0.15.20/testenv/lib/python3.8/site-packages/great_expectations/data_context/util.py", line 329, in substitute_value_from_aws_secrets_manager
    secret_response = client.get_secret_value(SecretId=secret_name)
  File "/home/dtrivedi/Development/great-expectations-0.15.20/testenv/lib/python3.8/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/dtrivedi/Development/great-expectations-0.15.20/testenv/lib/python3.8/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (UnrecognizedClientException) when calling the GetSecretValue operation: The security token included in the request is invalid```

**Expected behavior**
The command should not fail with AWS Credentials error when building a LOCAL site. 

**Environment (please complete the following information):**
 - Operating System: Linux
 - Great Expectations Version: 0.15.20

**Additional context**
Add any other context about the problem here.

**Comment by austiezr** [comment]
Hey @klashe1977 ! Thanks for raising this; we'll review internally and be in touch.

**Comment by adam-mrozik** [comment]
Hey, bumping this one, have encountered same issue as well

EDIT:

Probably related, but since it checks all buckets existence, it is basically impossible to configure for multiple environments. Each bucket for me is a different set of credentials, so everytime I try to run for dev, it fails on checking that `prod` bucket exists

**Comment by austiezr** [comment]
Hey @klashe1977 & @adam-mrozik! Looks to be related to #6441; the core team has taken this work under planning. 🙇

**Comment by cdkini** [comment]
Hey @klashe1977 and @adam-mrozik, thanks for your patience here!

We've worked to recreate this issue locally and have determined the culprit - Great Expectations evaluates the entire config greedily rather than lazily based on what parts are actually accessed. 

So in this particular situation, even though you're trying to evaluate `local_site`, any `${VARIABLE}` references elsewhere in your config will be evaluated during `DataContext` instantiation. Although I am not able to see the rest of your configuration, I'd imagine there is a `${VARIABLE}` reference that substitutes to an AWS Secret Store value, causing the particular issue we're seeing here.

While we'd like to be able to support this lazy evaluation down the line, we won't be able to prioritize it at this time due to competing priorities. To get your workflow functional, we'd recommend commenting out any configuration that may related to AWS when working within a local context.

Apologies for any difficulties here - please let us know if you're still running into issues with that workaround 🙇🏽
