### ISSUE TITLE
Clickhouse KeyError

### ISSUE THREAD

**Issue by marcelatoffernet** [fivetran/great_expectations#5906]
Using `clickhouse-sqlalchemy`, the profiler causes an issue:

``` python
...
validator.head(n_rows=5, fetch_all=False)
```

```console
2022-09-01T10:28:32+0200 - WARNING - Exceptions
{('table.head', 'batch_id=8a5811cca948ef555530e233973f214c', '04166707abe073177c1dd922d3584468'): {'metric_configuration': {
  "metric_name": "table.head",
  "metric_domain_kwargs": {
    "batch_id": "8a5811cca948ef555530e233973f214c"
  },
  "metric_domain_kwargs_id": "batch_id=8a5811cca948ef555530e233973f214c",
  "metric_value_kwargs": {
    "n_rows": 5,
    "fetch_all": false
  },
  "metric_value_kwargs_id": "04166707abe073177c1dd922d3584468",
  "id": [
    "table.head",
    "batch_id=8a5811cca948ef555530e233973f214c",
    "04166707abe073177c1dd922d3584468"
  ]
}, 'num_failures': 3, 'exception_info': {{'exception_traceback': 'Traceback (most recent call last):\n  File "/Users/marcelcoetzee/mambaforge/envs/ge/lib/python3.10/site-packages/clickhouse_sqlalchemy/drivers/native/connector.py", line 152, in execute\n    response = execute(\n  File "/Users/marcelcoetzee/mambaforge/envs/ge/lib/python3.10/site-packages/clickhouse_driver/client.py", line 304, in execute\n    rv = self.process_ordinary_query(\n  File "/Users/marcelcoetzee/mambaforge/envs/ge/lib/python3.10/site-packages/clickhouse_driver/client.py", line 491, in process_ordinary_query\n    return self.receive_result(with_column_types=with_column_types,\n  File "/Users/marcelcoetzee/mambaforge/envs/ge/lib/python3.10/site-packages/clickhouse_driver/client.py", line 151, in receive_result\n    return result.get_result()\n  File "/Users/marcelcoetzee/mambaforge/envs/ge/lib/python3.10/site-packages/clickhouse_driver/result.py", line 50, in get_result\n    for packet in self.packet_generator:\n  File "/Users/marcelcoetzee/mambaforge/envs/ge/lib/python3.10/site-packages/clickhouse_driver/client.py", line 167, in packet_generator\n    packet = self.receive_packet()\n  File "/Users/marcelcoetzee/mambaforge/envs/ge/lib/python3.10/site-packages/clickhouse_driver/client.py", line 184, in receive_packet\n    raise packet.exception\nclickhouse_driver.errors.ServerException: Code: 60.\nDB::Exception: Table touchpoint.ge_temp_8f4ec061 doesn\'t exist. Stack trace:\n\n0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) in /usr/bin/clickhouse\n1. DB::DatabaseCatalog::getTableImpl(DB::StorageID const&, std::__1::shared_ptr<DB::Context const>, std::__1::optional<DB::Exception>*) const in /usr/bin/clickhouse\n2. DB::DatabaseCatalog::getTable(DB::StorageID const&, std::__1::shared_ptr<DB::Context const>) const in /usr/bin/clickhouse\n3. DB::JoinedTables::getLeftTableStorage() in /usr/bin/clickhouse\n4. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::PreparedSets>) in /usr/bin/clickhouse\n5. DB::InterpreterSelectWithUnionQuery::buildCurrentChildInterpreter(std::__1::shared_ptr<DB::IAST> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) in /usr/bin/clickhouse\n6. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) in /usr/bin/clickhouse\n7. DB::InterpreterFactory::get(std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&) in /usr/bin/clickhouse\n8. ? in /usr/bin/clickhouse\n9. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) in /usr/bin/clickhouse\n10. DB::TCPHandler::runImpl() in /usr/bin/clickhouse\n11. DB::TCPHandler::run() in /usr/bin/clickhouse\n12. Poco::Net::TCPServerConnection::start() in /usr/bin/clickhouse\n13. Poco::Net::TCPServerDispatcher::run() in /usr/bin/clickhouse\n14. Poco::PooledThread::run() in /usr/bin/clickhouse\n15. Poco::ThreadImpl::runnableEntry(void*) in /usr/bin/clickhouse\n16. ? in ?\n17. clone in ?\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/marcelcoetzee/mambaforge/envs/ge/lib/python3.10/site-packages/great_expectations/execution_engine/execution_engine.py", line 393, in resolve_metrics\n    resolved_metrics[metric_to_resolve.id] = metric_fn(\n  File "/Users/marcelcoetzee/mambaforge/envs/ge/lib/python3.10/site-packages/great_expectations/expectations/metrics/metric_provider.py", line 34, in inner_func\n    return metric_fn(*args, **kwargs)\n  File "/Users/marcelcoetzee/mambaforge/envs/ge/lib/python3.10/site-packages/great_expectations/expectations/metrics/table_metrics/table_head.py", line 138, in _sqlalchemy\n    df = pd.read_sql(sql, con=execution_engine.engine)\n  File "/Users/marcelcoetzee/mambaforge/envs/ge/lib/python3.10/site-packages/pandas/io/sql.py", line 592, in read_sql\n    return pandas_sql.read_query(\n  File "/Users/marcelcoetzee/mambaforge/envs/ge/lib/python3.10/site-packages/pandas/io/sql.py", line 1557, in read_query\n    result = self.execute(*args)\n  File "/Users/marcelcoetzee/mambaforge/envs/ge/lib/python3.10/site-packages/pandas/io/sql.py", line 1402, in execute\n    return self.connectable.execution_options().execute(*args, **kwargs)\n  File "<string>", line 2, in execute\n  File "/Users/marcelcoetzee/mambaforge/envs/ge/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 402, in warned\n    return fn(*args, **kwargs)\n  File "/Users/marcelcoetzee/mambaforge/envs/ge/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3257, in execute\n    return connection.execute(statement, *multiparams, **params)\n  File "/Users/marcelcoetzee/mambaforge/envs/ge/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1380, in execute\n    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)\n  File "/Users/marcelcoetzee/mambaforge/envs/ge/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 475, in _execute_on_connection\n    return connection._execute_compiled(\n  File "/Users/marcelcoetzee/mambaforge/envs/ge/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1625, in _execute_compiled\n    ret = self._execute_context(\n  File "/Users/marcelcoetzee/mambaforge/envs/ge/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context\n    self._handle_dbapi_exception(\n  File "/Users/marcelcoetzee/mambaforge/envs/ge/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2128, in _handle_dbapi_exception\n    util.raise_(exc_info[1], with_traceback=exc_info[2])\n  File "/Users/marcelcoetzee/mambaforge/envs/ge/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_\n    raise exception\n  File "/Users/marcelcoetzee/mambaforge/envs/ge/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context\n    self.dialect.do_execute(\n  File "/Users/marcelcoetzee/mambaforge/envs/ge/lib/python3.10/site-packages/clickhouse_sqlalchemy/drivers/base.py", line 411, in do_execute\n    cursor.execute(statement, parameters, context=context)\n  File "/Users/marcelcoetzee/mambaforge/envs/ge/lib/python3.10/site-packages/clickhouse_sqlalchemy/drivers/native/connector.py", line 158, in execute\n    raise DatabaseException(orig)\nclickhouse_sqlalchemy.exceptions.DatabaseException: Orig exception: Code: 60.\nDB::Exception: Table touchpoint.ge_temp_8f4ec061 doesn\'t exist. Stack trace:\n\n0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) in /usr/bin/clickhouse\n1. DB::DatabaseCatalog::getTableImpl(DB::StorageID const&, std::__1::shared_ptr<DB::Context const>, std::__1::optional<DB::Exception>*) const in /usr/bin/clickhouse\n2. DB::DatabaseCatalog::getTable(DB::StorageID const&, std::__1::shared_ptr<DB::Context const>) const in /usr/bin/clickhouse\n3. DB::JoinedTables::getLeftTableStorage() in /usr/bin/clickhouse\n4. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::PreparedSets>) in /usr/bin/clickhouse\n5. DB::InterpreterSelectWithUnionQuery::buildCurrentChildInterpreter(std::__1::shared_ptr<DB::IAST> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) in /usr/bin/clickhouse\n6. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) in /usr/bin/clickhouse\n7. DB::InterpreterFactory::get(std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&) in /usr/bin/clickhouse\n8. ? in /usr/bin/clickhouse\n9. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) in /usr/bin/clickhouse\n10. DB::TCPHandler::runImpl() in /usr/bin/clickhouse\n11. DB::TCPHandler::run() in /usr/bin/clickhouse\n12. Poco::Net::TCPServerConnection::start() in /usr/bin/clickhouse\n13. Poco::Net::TCPServerDispatcher::run() in /usr/bin/clickhouse\n14. Poco::PooledThread::run() in /usr/bin/clickhouse\n15. Poco::ThreadImpl::runnableEntry(void*) in /usr/bin/clickhouse\n16. ? in ?\n17. clone in ?\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/marcelcoetzee/mambaforge/envs/ge/lib/python3.10/site-packages/great_expectations/validator/validator.py", line 1324, in resolve_validation_graph\n    self._resolve_metrics(\n  File "/Users/marcelcoetzee/mambaforge/envs/ge/lib/python3.10/site-packages/great_expectations/validator/validator.py", line 2247, in _resolve_metrics\n    return execution_engine.resolve_metrics(\n  File "/Users/marcelcoetzee/mambaforge/envs/ge/lib/python3.10/site-packages/great_expectations/execution_engine/execution_engine.py", line 397, in resolve_metrics\n    raise ge_exceptions.MetricResolutionError(\ngreat_expectations.exceptions.exceptions.MetricResolutionError: Orig exception: Code: 60.\nDB::Exception: Table touchpoint.ge_temp_8f4ec061 doesn\'t exist. Stack trace:\n\n0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) in /usr/bin/clickhouse\n1. DB::DatabaseCatalog::getTableImpl(DB::StorageID const&, std::__1::shared_ptr<DB::Context const>, std::__1::optional<DB::Exception>*) const in /usr/bin/clickhouse\n2. DB::DatabaseCatalog::getTable(DB::StorageID const&, std::__1::shared_ptr<DB::Context const>) const in /usr/bin/clickhouse\n3. DB::JoinedTables::getLeftTableStorage() in /usr/bin/clickhouse\n4. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::PreparedSets>) in /usr/bin/clickhouse\n5. DB::InterpreterSelectWithUnionQuery::buildCurrentChildInterpreter(std::__1::shared_ptr<DB::IAST> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) in /usr/bin/clickhouse\n6. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) in /usr/bin/clickhouse\n7. DB::InterpreterFactory::get(std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&) in /usr/bin/clickhouse\n8. ? in /usr/bin/clickhouse\n9. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) in /usr/bin/clickhouse\n10. DB::TCPHandler::runImpl() in /usr/bin/clickhouse\n11. DB::TCPHandler::run() in /usr/bin/clickhouse\n12. Poco::Net::TCPServerConnection::start() in /usr/bin/clickhouse\n13. Poco::Net::TCPServerDispatcher::run() in /usr/bin/clickhouse\n14. Poco::PooledThread::run() in /usr/bin/clickhouse\n15. Poco::ThreadImpl::runnableEntry(void*) in /usr/bin/clickhouse\n16. ? in ?\n17. clone in ?\n\n', 'exception_message': "Orig exception: Code: 60.\nDB::Exception: Table touchpoint.ge_temp_8f4ec061 doesn't exist. Stack trace:\n\n0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) in /usr/bin/clickhouse\n1. DB::DatabaseCatalog::getTableImpl(DB::StorageID const&, std::__1::shared_ptr<DB::Context const>, std::__1::optional<DB::Exception>*) const in /usr/bin/clickhouse\n2. DB::DatabaseCatalog::getTable(DB::StorageID const&, std::__1::shared_ptr<DB::Context const>) const in /usr/bin/clickhouse\n3. DB::JoinedTables::getLeftTableStorage() in /usr/bin/clickhouse\n4. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::PreparedSets>) in /usr/bin/clickhouse\n5. DB::InterpreterSelectWithUnionQuery::buildCurrentChildInterpreter(std::__1::shared_ptr<DB::IAST> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) in /usr/bin/clickhouse\n6. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) in /usr/bin/clickhouse\n7. DB::InterpreterFactory::get(std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&) in /usr/bin/clickhouse\n8. ? in /usr/bin/clickhouse\n9. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) in /usr/bin/clickhouse\n10. DB::TCPHandler::runImpl() in /usr/bin/clickhouse\n11. DB::TCPHandler::run() in /usr/bin/clickhouse\n12. Poco::Net::TCPServerConnection::start() in /usr/bin/clickhouse\n13. Poco::Net::TCPServerDispatcher::run() in /usr/bin/clickhouse\n14. Poco::PooledThread::run() in /usr/bin/clickhouse\n15. Poco::ThreadImpl::runnableEntry(void*) in /usr/bin/clickhouse\n16. ? in ?\n17. clone in ?\n", 'raised_exception': True}}}}
occurred while resolving metrics.
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Input In [2], in <cell line: 43>()
     41 column_names = [f'"{column_name}"' for column_name in validator.columns()]
     42 print(f"Columns: {', '.join(column_names)}.")
---> 43 validator.head(n_rows=5, fetch_all=False)

File ~/mambaforge/envs/ge/lib/python3.10/site-packages/great_expectations/validator/validator.py:2187, in Validator.head(self, n_rows, domain_kwargs, fetch_all)
   2182 if domain_kwargs is None:
   2183     domain_kwargs = {
   2184         "batch_id": self.execution_engine.active_batch_data_id,
   2185     }
-> 2187 data: Any = self.get_metric(
   2188     metric=MetricConfiguration(
   2189         metric_name="table.head",
   2190         metric_domain_kwargs=domain_kwargs,
   2191         metric_value_kwargs={
   2192             "n_rows": n_rows,
   2193             "fetch_all": fetch_all,
   2194         },
   2195     )
   2196 )
   2198 df: pd.DataFrame
   2199 if isinstance(
   2200     self.execution_engine, (PandasExecutionEngine, SqlAlchemyExecutionEngine)
   2201 ):

File ~/mambaforge/envs/ge/lib/python3.10/site-packages/great_expectations/validator/validator.py:921, in Validator.get_metric(self, metric, force_no_progress_bar)
    915 def get_metric(
    916     self,
    917     metric: MetricConfiguration,
    918     force_no_progress_bar: bool = False,
    919 ) -> Any:
    920     """return the value of the requested metric."""
--> 921     return self.get_metrics(
    922         metrics={metric.metric_name: metric},
    923         force_no_progress_bar=force_no_progress_bar,
    924     )[metric.metric_name]

File ~/mambaforge/envs/ge/lib/python3.10/site-packages/great_expectations/validator/validator.py:882, in Validator.get_metrics(self, metrics, force_no_progress_bar)
    869 """
    870 Args:
    871     metrics: Dictionary of desired metrics to be resolved, with metric_name as key and MetricConfiguration as value.
   (...)
    875     Return Dictionary with requested metrics resolved, with metric_name as key and computed metric as value.
    876 """
    877 resolved_metrics: Dict[Tuple[str, str, str], Any] = self.compute_metrics(
    878     metric_configurations=list(metrics.values()),
    879     force_no_progress_bar=force_no_progress_bar,
    880 )
--> 882 return {
    883     metric_configuration.metric_name: resolved_metrics[metric_configuration.id]
    884     for metric_configuration in metrics.values()
    885 }

File ~/mambaforge/envs/ge/lib/python3.10/site-packages/great_expectations/validator/validator.py:883, in <dictcomp>(.0)
    869 """
    870 Args:
    871     metrics: Dictionary of desired metrics to be resolved, with metric_name as key and MetricConfiguration as value.
   (...)
    875     Return Dictionary with requested metrics resolved, with metric_name as key and computed metric as value.
    876 """
    877 resolved_metrics: Dict[Tuple[str, str, str], Any] = self.compute_metrics(
    878     metric_configurations=list(metrics.values()),
    879     force_no_progress_bar=force_no_progress_bar,
    880 )
    882 return {
--> 883     metric_configuration.metric_name: resolved_metrics[metric_configuration.id]
    884     for metric_configuration in metrics.values()
    885 }

KeyError: ('table.head', 'batch_id=8a5811cca948ef555530e233973f214c', '04166707abe073177c1dd922d3584468')
```

**Comment by austiezr** [comment]
Hey @marcelatoffernet ! Thanks for raising this. Support for Clickhouse is currently Experimental, and there may be some instability inherent in that. We have eyes on improving functionality in this area, but if you are interested in making a contribution towards a solution here, we would be happy to provide support and guidance.

**Comment by marcelatoffernet** [comment]
HI @austiezr . I would be willing to contribute, having vested interested in getting this to work and access to some Clickhouse experts as well who can advise on the CH side of things.

How can I start?

**Comment by pcontrerasnun** [comment]
I was able to connect to CH with some way arounds (see this discussion https://discuss.greatexpectations.io/t/is-anyone-using-great-expectations-with-the-clickhouse-dbms/654), although had other issues with expectations https://github.com/great-expectations/great_expectations/issues/5832

**Comment by Pipboyguy** [comment]
@pcontrerasnun thank you! 

It worked as per your suggestion by adding the following key to `batch_request`:

```python
"batch_spec_passthrough": {"create_temp_table": False}
```

**Comment by Plozano94** [comment]
Hi @austiezr , I'm working  in clickhouse compatibility and I'm in an advanced state. Planning to make the PR soon

**Comment by molliemarie** [comment]
Hello @marcelatoffernet. With the upcoming launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
