### ISSUE TITLE
Neither 'ColumnClause' object nor 'Comparator' object has an attribute 'is_not'

### ISSUE THREAD

**Issue by adam-mrozik** [fivetran/great_expectations#5991]
**Describe the bug**
When trying to run `build_suite` method against my CH datasource I get the error mentioned in the topic. Seems like some SQLAlchemy Query builder issue. 
It works when I manually edit the code to use `isnot` instead of `is_not`

**Environment (please complete the following information):**
 - Operating System: Ubuntu 21.04
 - Great Expectations Version: great_expectations, version 0.15.22
 - SQLAlchemy-1.3.19
 - clickhouse-sqlalchemy 0.1.10

**Additional context**

Error:
```
The above exception was the direct cause of the following exception:

AttributeError                            Traceback (most recent call last)
~/.local/share/virtualenvs/my-repo/lib/python3.9/site-packages/great_expectations/execution_engine/execution_engine.py in resolve_metrics(self, metrics_to_resolve, metrics, runtime_configuration)
    392                 # NOTE: DH 20220328: This is where we can introduce the Batch Metrics Store (BMS)
--> 393                 resolved_metrics[metric_to_resolve.id] = metric_fn(
    394                     **metric_provider_kwargs

~/.local/share/virtualenvs/my-repo/lib/python3.9/site-packages/great_expectations/expectations/metrics/metric_provider.py in inner_func(*args, **kwargs)
     33         def inner_func(*args, **kwargs):
---> 34             return metric_fn(*args, **kwargs)
     35 

~/.local/share/virtualenvs/my-repo/lib/python3.9/site-packages/great_expectations/expectations/metrics/column_aggregate_metrics/column_value_counts.py in _sqlalchemy(cls, execution_engine, metric_domain_kwargs, metric_value_kwargs, **kwargs)
    105             )
--> 106             .where(sa.column(column).is_not(None))
    107             .group_by(sa.column(column))

~/.local/share/virtualenvs/my-repo/lib/python3.9/site-packages/sqlalchemy/sql/elements.py in __getattr__(self, key)
    748         except AttributeError as err:
--> 749             util.raise_(
    750                 AttributeError(

~/.local/share/virtualenvs/my-repo/lib/python3.9/site-packages/sqlalchemy/util/compat.py in raise_(***failed resolving arguments***)
    181         try:
--> 182             raise exception
    183         finally:

AttributeError: Neither 'ColumnClause' object nor 'Comparator' object has an attribute 'is_not'
```

**Comment by talagluck** [comment]
Hi @adam-mrozik - thanks for your question! We don't currently have much support for ClickHouse - technically it is possible to use it through our SqlAlchemy connection, but there are several different parts of the codebase that are specific to different SQL dialects, and few, if any, of those have been specifically implemented for ClickHouse. If you are interested in adding better support for ClickHouse, please let us know!

**Comment by serg-music** [comment]
I face the same issue with GE 0.15.27 and am interested in adding better support for ClickHouse.

**Comment by itaise** [comment]
Hi @talagluck, we are facing the same issue with Trino, with SQLAlchemy.
We are using this expectation: 
```
{
        "expectation_type": "expect_column_distinct_values_to_equal_set",
        "kwargs": {
            "column": "survived",
            "value_set": [0, 1]
        }
    }
```
And getting the same SQLAlchemy error - 

```
File "/Users/itaise/.pyenv/versions/3.7.13/lib/python3.7/site-packages/great_expectations/expectations/metrics/column_aggregate_metrics/column_value_counts.py", line 106, in _sqlalchemy
.where(sa.column(column).is_not(None))
File "/Users/itaise/github/wix-data-dev/python/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 758, in __getattr__
replace_context=err,
File "/Users/itaise/github/wix-data-dev/python/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
raise exception
AttributeError: Neither 'ColumnClause' object nor 'Comparator' object has an attribute 'is_not'
```

can you please check? thanks!

**Comment by kenwade4** [comment]
https://github.com/great-expectations/great_expectations/pull/6318
