### ISSUE TITLE
JsonSchemaProfiler doesn't handle a property with "type": "object"

### ISSUE THREAD

**Issue by OphelieC** [fivetran/great_expectations#6109]
**Description**
When running the `JsonSchemaProfiler` on schemas where a property has the `"type": "object"`, the profiler throws the following error:

>  Traceback (most recent call last):
  File "json_profiler.py", line 43, in <module>
    suite = profiler.profile(schema, suite_name)
  File "/Users/ophelie/repos/data-platform/venv/lib/python3.8/site-packages/great_expectations/profile/base.py", line 157, in profile
    expectation_suite = self._profile(item_to_profile, suite_name=suite_name)
  File "/Users/ophelie/repos/data-platform/venv/lib/python3.8/site-packages/great_expectations/profile/json_schema_profiler.py", line 78, in _profile
    type_expectation = self._create_type_expectation(key, details)
  File "/Users/ophelie/repos/data-platform/venv/lib/python3.8/site-packages/great_expectations/profile/json_schema_profiler.py", line 196, in _create_type_expectation
    type_list.extend(self.PROFILER_TYPE_LIST_BY_JSON_SCHEMA_TYPE[type_])
KeyError: 'object'

**To Reproduce**
1. Add a property with `"type": "object"` in a schema file
2. Run the `JsonSchemaProfiler` on that schema file

**Expected behaviour**
The `JsonSchemaProfiler` should have an OBJECT_TYPE_NAMES mapping to recognise the object type. 

**Environment**
 - Operating System: MacOS Monterey v12.6
 - Great Expectations Version: 0.15.22

**Additional information**
I resolved this on my local venv and will push a PR shortly to resolve this issue.

**Comment by austiezr** [comment]
Hey @OphelieC ! Thanks for raising this (and the Contribution)! We'll review both and be in touch.

**Comment by austiezr** [comment]
Closed by #6110 ; thanks @OphelieC !
