### ISSUE TITLE
Lost connection to MySQL server during query ([Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by footprintAvens** [fivetran/great_expectations#6306]
**Describe the bug**
Our total verification time is about two hours, and 14 concurrent threads can maintain concurrent execution in the first hour, but after one hour, only one thread is running, so our verification time changes. More, the number of threads decreases is consistent with the time when this bug appeared, so I think it may be related to the connection hold time, but I don't know how to solve it, can anyone help me?

error is following:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 669, in do_rollback
    dbapi_connection.rollback()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 480, in rollback
    self._read_ok_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 443, in _read_ok_packet
    pkt = self._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 692, in _read_packet
    packet_header = self._read_bytes(4)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 738, in _read_bytes
    raise err.OperationalError(
pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query ([Errno 104] Connection reset by peer)')

**Comment by austiezr** [comment]
Hey @footprintAvens ! Thanks for reaching out. Are you able to share some more information about your use-case and environment? There may be ways to optimize your GX deployment to improve execution time, but we aren't able to provide much help if the issue is with your MySQL environment.
