### ISSUE TITLE
Problem Connecting to S3 Services (other than AWS S3)

### ISSUE THREAD

**Issue by cdoron** [fivetran/great_expectations#6506]
**Describe the bug**
When connecting to an S3 service (other than AWS S3), great-expectations code (or a library uses) ignores the specified endpoint URL. Instead, it constructs a `amazonaws` endpoint URL from the bucket name, region, and object name (resulting in, for example: `https://demo-om.s3.eu-de.amazonaws.com/PS_20174392719_1491204439457_log.csv`)

**To Reproduce - Shorter version**
I am trying to follow the instructions in https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/cloud/s3/pandas to connect great-expectations to data on S3. I am not using amazon S3, but an S3 IBM Cloud service.

Everything up until (and including) `context.test_yaml_config(yaml.dump(datasource_config))` seems to work perfectly. Under `Available data_asset_names (2 of 2):` I get a list of 2 csv objects in the bucket I specified.

Things go wrong when I run
```
validator = context.get_validator(
    batch_request=batch_request, expectation_suite_name="test_suite"
)
```
I get the following error:
```
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://demo-om.s3.eu-de.amazonaws.com/PS_20174392719_1491204439457_log.csv"
```

**To Reproduce - Longer Version**
This is the python script I am running (without the secret credentials):
```
from ruamel import yaml

import great_expectations as ge
from great_expectations.core.batch import Batch, BatchRequest, RuntimeBatchRequest

context = ge.get_context()

datasource_config = {
    "name": "my_s3_datasource",
    "class_name": "Datasource",
    "execution_engine": {"class_name": "PandasExecutionEngine"},
    "data_connectors": {
        "default_runtime_data_connector_name": {
            "class_name": "RuntimeDataConnector",
            "batch_identifiers": ["default_identifier_name"],
        },
        "default_inferred_data_connector_name": {
            "class_name": "InferredAssetS3DataConnector",
            "bucket": "demo-om",
            "prefix": "",
            "default_regex": {
                "pattern": "(.*)\\.csv",
                "group_names": ["data_asset_name"],
            },
            "boto3_options": {
              "endpoint_url": "https://s3.eu-de.cloud-object-storage.appdomain.cloud/",
              "aws_access_key_id": "myaccesskey",
              "aws_secret_access_key": "mysecretkey",
            }
        },
    },
}

context.test_yaml_config(yaml.dump(datasource_config))

context.add_datasource(**datasource_config)

batch_request = BatchRequest(
    datasource_name="my_s3_datasource",
    data_connector_name="default_inferred_data_connector_name",
    data_asset_name="PS_20174392719_1491204439457_log",
)

context.create_expectation_suite(
    expectation_suite_name="test_suite", overwrite_existing=True
)
validator = context.get_validator(
    batch_request=batch_request, expectation_suite_name="test_suite"
)
print(validator.head())
```

Output:
```
$ python3 ge_s3.py 
Attempting to instantiate class from config...
	Instantiating as a Datasource, since class_name is Datasource
	Successfully instantiated Datasource


ExecutionEngine class name: PandasExecutionEngine
Data Connectors:
	default_inferred_data_connector_name : InferredAssetS3DataConnector

	Available data_asset_names (2 of 2):
		PS_20174392719_1491204439457_log (1 of 1): ['PS_20174392719_1491204439457_log.csv']
		alexey (1 of 1): ['alexey.csv']

	Unmatched data_references (0 of 0):[]

	default_runtime_data_connector_name:RuntimeDataConnector

	Available data_asset_names (0 of 0):
		Note : RuntimeDataConnector will not have data_asset_names until they are passed in through RuntimeBatchRequest

	Unmatched data_references (0 of 0): []

Traceback (most recent call last):
  File "/home/cdoron/.local/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/cdoron/.local/lib/python3.8/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 914, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cdoron/.local/lib/python3.8/site-packages/botocore/httpsession.py", line 345, in send
    urllib_response = conn.urlopen(
  File "/home/cdoron/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/home/cdoron/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 525, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/cdoron/.local/lib/python3.8/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/home/cdoron/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/cdoron/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/cdoron/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/home/cdoron/.local/lib/python3.8/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/home/cdoron/.local/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <botocore.awsrequest.AWSHTTPSConnection object at 0x7f50127c7640>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ge_s3.py", line 47, in <module>
    validator = context.get_validator(
  File "/home/cdoron/.local/lib/python3.8/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 1409, in get_validator
    self.get_batch_list(
  File "/home/cdoron/.local/lib/python3.8/site-packages/great_expectations/core/usage_statistics/usage_statistics.py", line 304, in usage_statistics_wrapped_method
    result = func(*args, **kwargs)
  File "/home/cdoron/.local/lib/python3.8/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 1591, in get_batch_list
    return datasource.get_batch_list_from_batch_request(batch_request=batch_request)
  File "/home/cdoron/.local/lib/python3.8/site-packages/great_expectations/datasource/new_datasource.py", line 205, in get_batch_list_from_batch_request
    ) = data_connector.get_batch_data_and_metadata(
  File "/home/cdoron/.local/lib/python3.8/site-packages/great_expectations/datasource/data_connector/data_connector.py", line 116, in get_batch_data_and_metadata
    batch_data, batch_markers = self._execution_engine.get_batch_data_and_markers(
  File "/home/cdoron/.local/lib/python3.8/site-packages/great_expectations/execution_engine/pandas_execution_engine.py", line 253, in get_batch_data_and_markers
    s3_object = s3_engine.get_object(Bucket=s3_url.bucket, Key=s3_url.key)
  File "/home/cdoron/.local/lib/python3.8/site-packages/botocore/client.py", line 388, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/cdoron/.local/lib/python3.8/site-packages/botocore/client.py", line 694, in _make_api_call
    http, parsed_response = self._make_request(
  File "/home/cdoron/.local/lib/python3.8/site-packages/botocore/client.py", line 714, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/home/cdoron/.local/lib/python3.8/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/cdoron/.local/lib/python3.8/site-packages/botocore/endpoint.py", line 136, in _send_request
    while self._needs_retry(attempts, operation_model, request_dict,
  File "/home/cdoron/.local/lib/python3.8/site-packages/botocore/endpoint.py", line 252, in _needs_retry
    responses = self._event_emitter.emit(
  File "/home/cdoron/.local/lib/python3.8/site-packages/botocore/hooks.py", line 357, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/cdoron/.local/lib/python3.8/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/home/cdoron/.local/lib/python3.8/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/home/cdoron/.local/lib/python3.8/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/home/cdoron/.local/lib/python3.8/site-packages/botocore/retryhandler.py", line 250, in __call__
    should_retry = self._should_retry(attempt_number, response,
  File "/home/cdoron/.local/lib/python3.8/site-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/home/cdoron/.local/lib/python3.8/site-packages/botocore/retryhandler.py", line 316, in __call__
    checker_response = checker(attempt_number, response,
  File "/home/cdoron/.local/lib/python3.8/site-packages/botocore/retryhandler.py", line 222, in __call__
    return self._check_caught_exception(
  File "/home/cdoron/.local/lib/python3.8/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "/home/cdoron/.local/lib/python3.8/site-packages/botocore/endpoint.py", line 199, in _do_get_response
    http_response = self._send(request)
  File "/home/cdoron/.local/lib/python3.8/site-packages/botocore/endpoint.py", line 268, in _send
    return self.http_session.send(request)
  File "/home/cdoron/.local/lib/python3.8/site-packages/botocore/httpsession.py", line 374, in send
    raise EndpointConnectionError(endpoint_url=request.url, error=e)
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://demo-om.s3.eu-de.amazonaws.com/PS_20174392719_1491204439457_log.csv"
```

**Expected behavior**
Great expectations should use the `endpoint_url` value specified under `boto3_options` in the data connector configuration.

**Environment:**
 - Operating System: Linux Ubuntu 18.04.6 LTS
 - Great Expectations Version: 0.15.34

**Comment by rdodev** [comment]
Hey @cdoron 👋

 GX uses standard `boto3` as the connector to AWS S3. `boto3` only supports AWS S3, not other S3-like object stores. IBM has its own fork of `boto3` to connect to IBM Cloud Storage. If you're so inclined you could open a [discussion](https://github.com/great-expectations/great_expectations/discussions) in this repo to gauge interest in adding support to this storage backend.

**Comment by rdodev** [comment]
@cdoron as possible work around we suggest you create a sync folder (locally) and have the IBMCOS sdk sync with the bucket/container with the data objects you want. Then use a GX [filesystem](https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/filesystem/pandas/) provider to load and analyze the data.

**Comment by cdoron** [comment]
@rdodev : I just found out that you opened https://github.com/IBM/ibm-cos-sdk-python/issues/53
Thank you for that!
It turns out that `boto3` does support S3 services other than AWS S3, which might explain why `context.test_yaml_config(yaml.dump(datasource_config))` worked perfectly against the IBM S3 service.
Is there any plan to reopen https://github.com/great-expectations/great_expectations/issues/6506 ?

**Comment by rdodev** [comment]
Reopening since the issue lies in GX not respecting user-provided service URLs.

**Comment by blaze225** [comment]
Hi, facing the same issue. Is there any update on this?

**Comment by rdodev** [comment]
Hey @blaze225 

This work hasn't been prioritized, so we don't have a timeline for the fix.

**Comment by fbardos** [comment]
You can have a look at my workaround here: https://github.com/great-expectations/great_expectations/issues/2420#issuecomment-1365905877

After that, GE saved all the relevant Stores on my Minio instance.

**Comment by talagluck** [comment]
Thanks for this @fbardos! Closing, since there is a workaround linked above.
