### ISSUE TITLE
GE error when adding a second expectation to a validator and specifying its result_format

### ISSUE THREAD

**Issue by rguso** [fivetran/great_expectations#6565]
**Describe the bug**
If asking GE for a complete result with `expect_column_values_to_be_in_set` defined after `expect_column_distinct_values_to_equal_set`  an error is thrown in the result.

**To Reproduce**

Using the minimal example from the [result format documentation](https://docs.greatexpectations.io/docs/reference/expectations/result_format/#result_format-examples).
 Using in memory data connexion to pandas ([documentation](https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/in_memory/pandas)).

```python
import pandas as pd

import great_expectations as ge
from great_expectations.render import DefaultJinjaPageView
from great_expectations.render.renderer import ValidationResultsPageRenderer
from great_expectations.core.batch import RuntimeBatchRequest

df = pd.DataFrame(['A', 'B', 'B', 'C', 'C', 'C', 'D', 'D', 'D', 'D', 'E', 'E', 'E', 'E', 'E', 'F', 'F', 'F', 'F', 'F', 'F', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H'], columns=["var"])
    
context = ge.get_context()
datasource_config = {
    "name": "pandas_df",
    "class_name": "Datasource",
    "module_name": "great_expectations.datasource",
    "execution_engine": {
        "module_name": "great_expectations.execution_engine",
        "class_name": "PandasExecutionEngine",
    },
    "data_connectors": {
        "default_runtime_data_connector_name": {
            "class_name": "RuntimeDataConnector",
            "module_name": "great_expectations.datasource.data_connector",
            "batch_identifiers": ["default_identifier_name"],
        },
    },
}
batch_request = RuntimeBatchRequest(
    datasource_name="pandas_df",
    data_connector_name="default_runtime_data_connector_name",
    data_asset_name="pandas_df",
    runtime_parameters={"batch_data": df},
    batch_identifiers={"default_identifier_name": "default_identifier"},
)
validator = context.get_validator(
    batch_request=batch_request,
)

validator.expect_column_distinct_values_to_equal_set(
                                            "var",
                                            ["B", "C", "D", "F", "G", "H"],
                                            )  

validator.expect_column_values_to_be_in_set(
                                            "var",
                                            ["B", "C", "D", "F", "G", "H"],
                                            result_format ={'result_format': 'COMPLETE'}  # GE throws aan exception in the JSON result
                                            )

ge_result = validator.validate()

document_model = ValidationResultsPageRenderer().render(ge_result)
with open('data_doc.html', 'w', encoding="utf-8") as writer:
    writer.write(DefaultJinjaPageView().render(document_model))
```

Error message in ge_result: 

```
Traceback (most recent call last):
File "C:\Users\gueuletrma\Anaconda3\envs\classification_master\lib\site-packages\great_expectations\validator\validator.py", line 1013, in graph_validate
result = configuration.metrics_validate(
File "C:\Users\gueuletrma\Anaconda3\envs\classification_master\lib\site-packages\great_expectations\core\expectation_configuration.py", line 1404, in metrics_validate
return expectation_impl(self).metrics_validate(
File "C:\Users\gueuletrma\Anaconda3\envs\classification_master\lib\site-packages\great_expectations\expectations\expectation.py", line 973, in metrics_validate
provided_metrics[name] = metrics[metric_edge_key.id]
KeyError: ('column_values.in_set.unexpected_values', '97abf5d13bf8ef6fa5d0dfb57f46f05e', '0ebbf6a356ae422f6eb29fd53377d230')
```

**Expected behavior**
To return a result and not fail.
It doesn't fail either if:
- 'result_format' is not defined
- `expect_column_values_to_be_in_set` is defined before `expect_column_distinct_values_to_equal_set`

**Environment**
 - Operating System: Windows
 - Great Expectations Version: 0.15.34
 - Pandas Version: 1.4.4

**Comment by austiezr** [comment]
Hey @rguso! Thanks for raising this. We'll review & assess.

**Comment by tmilitino** [comment]
@austiezr, I can work on this issue if that's ok with the dev team.

**Comment by rguso** [comment]
Hi @tmilitino, hi @austiezr!
Have you had a look on this issue already? Thanks for your help!

**Comment by milithino** [comment]
hi @rguso, I'll look today!!
