### ISSUE TITLE
Datadocs rendering error and (probably related) expectation suite not being rendered on the Datadocs page

### ISSUE THREAD

**Issue by DKorman** [fivetran/great_expectations#6567]
**Describe the bug**
This is the error I am receiving:
```
11:05:42.108 | ERROR   | great_expectations.render.renderer.site_builder - An unexpected Exception occurred during data docs rendering.  Because of this error, certain parts of data docs will not be rendered properly and/or may not appear altogether.  Please use the trace, included in this message, to diagnose and repair the underlying issue.  Detailed information follows:
                TypeError: "unhashable type: 'dict'".  Traceback: "Traceback (most recent call last):
  File "/Users/davor/opt/anaconda3/envs/database/lib/python3.8/site-packages/great_expectations/render/renderer/site_builder.py", line 464, in build
    rendered_content = self.renderer_class.render(resource)
  File "/Users/davor/opt/anaconda3/envs/database/lib/python3.8/site-packages/great_expectations/render/renderer/page_renderer.py", line 675, in render
    ) = expectations.get_grouped_and_ordered_expectations_by_column()
  File "/Users/davor/opt/anaconda3/envs/database/lib/python3.8/site-packages/great_expectations/core/expectation_suite.py", line 923, in get_grouped_and_ordered_expectations_by_column
    if column not in expectations_by_column:
TypeError: unhashable type: 'dict'
".
11:05:51.719 | ERROR   | great_expectations.render.renderer.site_builder - An unexpected Exception occurred during data docs rendering.  Because of this error, certain parts of data docs will not be rendered properly and/or may not appear altogether.  Please use the trace, included in this message, to diagnose and repair the underlying issue.  Detailed information follows:
                TypeError: "unhashable type: 'dict'".  Traceback: "Traceback (most recent call last):
  File "/Users/davor/opt/anaconda3/envs/database/lib/python3.8/site-packages/great_expectations/render/renderer/site_builder.py", line 464, in build
    rendered_content = self.renderer_class.render(resource)
  File "/Users/davor/opt/anaconda3/envs/database/lib/python3.8/site-packages/great_expectations/render/renderer/page_renderer.py", line 675, in render
    ) = expectations.get_grouped_and_ordered_expectations_by_column()
  File "/Users/davor/opt/anaconda3/envs/database/lib/python3.8/site-packages/great_expectations/core/expectation_suite.py", line 923, in get_grouped_and_ordered_expectations_by_column
    if column not in expectations_by_column:
TypeError: unhashable type: 'dict'
".
```
think it happens during the `update_data_docs` action of the Simple checkpoint I am running. My DataDocs is of type TupleS3StoreBackend , while my expectation store backend is TupleFilesystemStoreBackend.  

In summary, the expectations do get tested on the batch of the data, but i) this error always gets printed out and ii) the Expectation suite is not being updated on the DataDocs S3 webpage (which is something I need)

**Expected behavior**
I would expect not to have this warnings and have the ExpectationSuite overview on the Datadocs page.

**Environment (please complete the following information):**
 - Operating System: Appears both on Mac and Windows 11
 - Great Expectations Version: great-expectations==0.15.32

**Additional context**
Happy to provide any info regarding how I configured checkpoint, eval parameter inputs, data context and etc. Didn't wanna clutter here with everything from the getgo since there is a lot of config overall.

**Comment by austiezr** [comment]
Hey @DKorman ! Thanks for raising this. If you can, please share your checkpoing config, expectation suite, data context, etc. That will help us to better understand what may be happening here.

**Comment by talagluck** [comment]
Closing due to inactivity.
