### ISSUE TITLE
When building documentation: AttributeError: 'dict' object has no attribute 'issubset'

### ISSUE THREAD

**Issue by dinedal** [fivetran/great_expectations#679]
Version: 0.7.7
System: OS X 10.14.5
Python: 3.7.4

```
Building documentation...
        Rendering profiling for data asset snowflake/default/rainbow_pr.stg_coral_schedules
Traceback (most recent call last):
  File "/Users/paul/source/rainbow/venv/bin/great_expectations", line 10, in <module>
    sys.exit(main())
  File "/Users/paul/source/rainbow/venv/lib/python3.7/site-packages/great_expectations/cli/cli.py", line 319, in main
    cli()
  File "/Users/paul/source/rainbow/venv/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/paul/source/rainbow/venv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/paul/source/rainbow/venv/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/paul/source/rainbow/venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/paul/source/rainbow/venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/paul/source/rainbow/venv/lib/python3.7/site-packages/great_expectations/cli/cli.py", line 290, in build_documentation
    build_documentation_impl(context, site_name=site_name, data_asset_name=data_asset_name)
  File "/Users/paul/source/rainbow/venv/lib/python3.7/site-packages/great_expectations/cli/datasource.py", line 317, in build_documentation
    index_page_locator_infos = context.build_data_documentation(site_names=site_names, data_asset_name=data_asset_name)
  File "/Users/paul/source/rainbow/venv/lib/python3.7/site-packages/great_expectations/data_context/data_context.py", line 1681, in build_data_documentation
    index_page_locator_info = SiteBuilder.build(self, complete_site_config, specified_data_asset_name=data_asset_name)
  File "/Users/paul/source/rainbow/venv/lib/python3.7/site-packages/great_expectations/render/renderer/site_builder.py", line 139, in build
    model = profiling_renderer_class.render(validation)
  File "/Users/paul/source/rainbow/venv/lib/python3.7/site-packages/great_expectations/render/renderer/page_renderer.py", line 333, in render
    column_types = ProfilingResultsOverviewSectionRenderer._get_column_types(validation_results)
  File "/Users/paul/source/rainbow/venv/lib/python3.7/site-packages/great_expectations/render/renderer/other_section_renderer.py", line 280, in _get_column_types
    if expected_types.issubset(BasicDatasetProfiler.INT_TYPE_NAMES):
AttributeError: 'dict' object has no attribute 'issubset'
```

**Comment by dinedal** [comment]
I just ran the Profiler to create the expectations, so perhaps it generated something wrong?

**Comment by jcampbell** [comment]
Thanks @dinedal : this is a bug in GE that appears to be caused by being unable to recognize the type of a column. Since it looks like you're running in snowflake, I suspect that we didn't have a type in our list of types that we check in the profiler.

Of course, it should handle that situation more gracefully, and I'm putting in a fix for that now. If you'd be willing to share the type of the relevant column, that'll help us improve the profiler.

**Comment by dinedal** [comment]
Per our conversation on Slack: https://greatexpectationstalk.slack.com/archives/C7Q0W2NHL/p1567511434010400

It appears this is because of the Snowflake specific `VARIANT` type, and while unusual types should be handled gracefully, this column should be handled as either JSON data, or the same as TEXT/VARCHAR data.

**Comment by jcampbell** [comment]
Thanks again, @dinedal!
