### ISSUE TITLE
Profile Failure  altair.utils.data.MaxRowsError

### ISSUE THREAD

**Issue by bkraft4257** [fivetran/great_expectations#808]
I was working with the Profiler in version 0.8.0 and encountered this Traceback Error on a large dataset.         

Rendering profiling for data asset TestData
Traceback (most recent call last):
  File "/Applications/anaconda3/envs/dc_school_budgets/bin/great_expectations", line 10, in <module>
    sys.exit(main())
  File "/Applications/anaconda3/envs/dc_school_budgets/lib/python3.7/site-packages/great_expectations/cli/cli.py", line 495, in main
    cli()
  File "/Applications/anaconda3/envs/dc_school_budgets/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Applications/anaconda3/envs/dc_school_budgets/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Applications/anaconda3/envs/dc_school_budgets/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Applications/anaconda3/envs/dc_school_budgets/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Applications/anaconda3/envs/dc_school_budgets/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Applications/anaconda3/envs/dc_school_budgets/lib/python3.7/site-packages/great_expectations/cli/cli.py", line 225, in init
    profile_datasource(context, data_source_name)
  File "/Applications/anaconda3/envs/dc_school_budgets/lib/python3.7/site-packages/great_expectations/cli/datasource.py", line 334, in profile_datasource
    build_docs(context)
  File "/Applications/anaconda3/envs/dc_school_budgets/lib/python3.7/site-packages/great_expectations/cli/datasource.py", line 350, in build_docs
    index_page_locator_infos = context.build_data_docs(site_names=site_names)
  File "/Applications/anaconda3/envs/dc_school_budgets/lib/python3.7/site-packages/great_expectations/data_context/data_context.py", line 1579, in build_data_docs
    index_page_locator_info = site_builder.build(resource_identifiers)[0]
  File "/Applications/anaconda3/envs/dc_school_budgets/lib/python3.7/site-packages/great_expectations/render/renderer/site_builder.py", line 192, in build
    resource_identifiers=resource_identifiers
  File "/Applications/anaconda3/envs/dc_school_budgets/lib/python3.7/site-packages/great_expectations/render/renderer/site_builder.py", line 279, in build
    rendered_content = self.renderer_class.render(resource)
  File "/Applications/anaconda3/envs/dc_school_budgets/lib/python3.7/site-packages/great_expectations/render/renderer/page_renderer.py", line 423, in render
    ) for column in ordered_columns
  File "/Applications/anaconda3/envs/dc_school_budgets/lib/python3.7/site-packages/great_expectations/render/renderer/page_renderer.py", line 423, in <listcomp>
    ) for column in ordered_columns
  File "/Applications/anaconda3/envs/dc_school_budgets/lib/python3.7/site-packages/great_expectations/render/renderer/column_section_renderer.py", line 72, in render
    content_blocks.append(self._render_histogram(evrs))
  File "/Applications/anaconda3/envs/dc_school_budgets/lib/python3.7/site-packages/great_expectations/render/renderer/column_section_renderer.py", line 462, in _render_histogram
    chart = bars.to_json()
  File "/Applications/anaconda3/envs/dc_school_budgets/lib/python3.7/site-packages/altair/utils/schemapi.py", line 334, in to_json
    dct = self.to_dict(validate=validate, ignore=ignore, context=context)
  File "/Applications/anaconda3/envs/dc_school_budgets/lib/python3.7/site-packages/altair/vegalite/v3/api.py", line 365, in to_dict
    copy.data = _prepare_data(original_data, context)
  File "/Applications/anaconda3/envs/dc_school_budgets/lib/python3.7/site-packages/altair/vegalite/v3/api.py", line 84, in _prepare_data
    data = pipe(data, data_transformers.get())
  File "/Applications/anaconda3/envs/dc_school_budgets/lib/python3.7/site-packages/toolz/functoolz.py", line 634, in pipe
    data = func(data)
  File "/Applications/anaconda3/envs/dc_school_budgets/lib/python3.7/site-packages/toolz/functoolz.py", line 303, in __call__
    return self._partial(*args, **kwargs)
  File "/Applications/anaconda3/envs/dc_school_budgets/lib/python3.7/site-packages/altair/vegalite/data.py", line 13, in default_data_transformer
    return pipe(data, limit_rows(max_rows=max_rows), to_values)
  File "/Applications/anaconda3/envs/dc_school_budgets/lib/python3.7/site-packages/toolz/functoolz.py", line 634, in pipe
    data = func(data)
  File "/Applications/anaconda3/envs/dc_school_budgets/lib/python3.7/site-packages/toolz/functoolz.py", line 303, in __call__
    return self._partial(*args, **kwargs)
  File "/Applications/anaconda3/envs/dc_school_budgets/lib/python3.7/site-packages/altair/utils/data.py", line 72, in limit_rows
    'in Altair, see the documentation'.format(max_rows))
altair.utils.data.MaxRowsError: The number of rows in your dataset is greater than the maximum allowed (5000). For information on how to plot larger datasets in Altair, see the documentation

**Comment by abegong** [comment]
@bkraft4257 Is it possible to share the data you were profiling?

Given Altair the error Altair is throwing, it looks like maybe we're overwhelming the histogram function with too many distinct values...?

**Comment by abegong** [comment]
@Aylr Regardless of the resolution for this specific bug, I'm thinking we should trap errors in the profiler, then re-raise with an informative message about the column and expectation that failed.

That'll make them easier to isolate and debug.

Thoughts?

**Comment by ian-whitestone** [comment]
I ran into the same issue today while going through the `great_expecations init` flow. Full trace:

        Rendering profiling for data asset price_rank_data
Traceback (most recent call last):
  File "/Users/ianwhitestone/.local/share/virtualenvs/domi--PPqv68y/bin/great_expectations", line 10, in <module>
    sys.exit(main())
  File "/Users/ianwhitestone/.local/share/virtualenvs/domi--PPqv68y/lib/python3.7/site-packages/great_expectations/cli/cli.py", line 527, in main
    cli()
  File "/Users/ianwhitestone/.local/share/virtualenvs/domi--PPqv68y/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ianwhitestone/.local/share/virtualenvs/domi--PPqv68y/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/ianwhitestone/.local/share/virtualenvs/domi--PPqv68y/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ianwhitestone/.local/share/virtualenvs/domi--PPqv68y/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ianwhitestone/.local/share/virtualenvs/domi--PPqv68y/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/ianwhitestone/.local/share/virtualenvs/domi--PPqv68y/lib/python3.7/site-packages/great_expectations/cli/cli.py", line 230, in init
    profile_datasource(context, data_source_name, open_docs=view)
  File "/Users/ianwhitestone/.local/share/virtualenvs/domi--PPqv68y/lib/python3.7/site-packages/great_expectations/cli/datasource.py", line 531, in profile_datasource
    build_docs(context)
  File "/Users/ianwhitestone/.local/share/virtualenvs/domi--PPqv68y/lib/python3.7/site-packages/great_expectations/cli/datasource.py", line 547, in build_docs
    index_page_locator_infos = context.build_data_docs(site_names=site_names)
  File "/Users/ianwhitestone/.local/share/virtualenvs/domi--PPqv68y/lib/python3.7/site-packages/great_expectations/data_context/data_context.py", line 1647, in build_data_docs
    index_page_locator_info = site_builder.build(resource_identifiers)[0]
  File "/Users/ianwhitestone/.local/share/virtualenvs/domi--PPqv68y/lib/python3.7/site-packages/great_expectations/render/renderer/site_builder.py", line 194, in build
    resource_identifiers=resource_identifiers
  File "/Users/ianwhitestone/.local/share/virtualenvs/domi--PPqv68y/lib/python3.7/site-packages/great_expectations/render/renderer/site_builder.py", line 283, in build
    rendered_content = self.renderer_class.render(resource)
  File "/Users/ianwhitestone/.local/share/virtualenvs/domi--PPqv68y/lib/python3.7/site-packages/great_expectations/render/renderer/page_renderer.py", line 478, in render
    ) for column in ordered_columns
  File "/Users/ianwhitestone/.local/share/virtualenvs/domi--PPqv68y/lib/python3.7/site-packages/great_expectations/render/renderer/page_renderer.py", line 478, in <listcomp>
    ) for column in ordered_columns
  File "/Users/ianwhitestone/.local/share/virtualenvs/domi--PPqv68y/lib/python3.7/site-packages/great_expectations/render/renderer/column_section_renderer.py", line 72, in render
    content_blocks.append(self._render_histogram(evrs))
  File "/Users/ianwhitestone/.local/share/virtualenvs/domi--PPqv68y/lib/python3.7/site-packages/great_expectations/render/renderer/column_section_renderer.py", line 462, in _render_histogram
    chart = bars.to_json()
  File "/Users/ianwhitestone/.local/share/virtualenvs/domi--PPqv68y/lib/python3.7/site-packages/altair/utils/schemapi.py", line 334, in to_json
    dct = self.to_dict(validate=validate, ignore=ignore, context=context)
  File "/Users/ianwhitestone/.local/share/virtualenvs/domi--PPqv68y/lib/python3.7/site-packages/altair/vegalite/v3/api.py", line 365, in to_dict
    copy.data = _prepare_data(original_data, context)
  File "/Users/ianwhitestone/.local/share/virtualenvs/domi--PPqv68y/lib/python3.7/site-packages/altair/vegalite/v3/api.py", line 84, in _prepare_data
    data = pipe(data, data_transformers.get())
  File "/Users/ianwhitestone/.local/share/virtualenvs/domi--PPqv68y/lib/python3.7/site-packages/toolz/functoolz.py", line 634, in pipe
    data = func(data)
  File "/Users/ianwhitestone/.local/share/virtualenvs/domi--PPqv68y/lib/python3.7/site-packages/toolz/functoolz.py", line 303, in __call__
    return self._partial(*args, **kwargs)
  File "/Users/ianwhitestone/.local/share/virtualenvs/domi--PPqv68y/lib/python3.7/site-packages/altair/vegalite/data.py", line 13, in default_data_transformer
    return pipe(data, limit_rows(max_rows=max_rows), to_values)
  File "/Users/ianwhitestone/.local/share/virtualenvs/domi--PPqv68y/lib/python3.7/site-packages/toolz/functoolz.py", line 634, in pipe
    data = func(data)
  File "/Users/ianwhitestone/.local/share/virtualenvs/domi--PPqv68y/lib/python3.7/site-packages/toolz/functoolz.py", line 303, in __call__
    return self._partial(*args, **kwargs)
  File "/Users/ianwhitestone/.local/share/virtualenvs/domi--PPqv68y/lib/python3.7/site-packages/altair/utils/data.py", line 72, in limit_rows
    'in Altair, see the documentation'.format(max_rows))
altair.utils.data.MaxRowsError: The number of rows in your dataset is greater than the maximum allowed (5000). For information on how to plot larger datasets in Altair, see the documentation

**Comment by ian-whitestone** [comment]
> @bkraft4257 Is it possible to share the data you were profiling?
> 
> Given Altair the error Altair is throwing, it looks like maybe we're overwhelming the histogram function with too many distinct values...?

Haven't dug into the code yet, but this sounds right. I'm playing with the NPI dataset so I can get something up and running that is working, and I've noticed that the histograms are being produced for `float` type columns..

![image](https://user-images.githubusercontent.com/11096727/68486422-07644c00-020f-11ea-9a54-913045a67503.png)

Won't this type of error occur frequently, given that float type columns are generally continuous variables in nature, and hence will have lots of distinct values?

**Comment by roblim** [comment]
This is addressed in https://github.com/great-expectations/great_expectations/releases/tag/0.9.0b1
